actions-add = Ajouter
actions-all-selected = Tous les sélectionnés
actions-any-selected = Toute sélection
actions-cancel = Annuler
actions-choose = Choisir
actions-close = Fermer
actions-copy = Copier
actions-create-copy = Créer une copie
actions-custom-study = Révisions personnalisées
actions-decks = Paquets
actions-delete = Supprimer
actions-export = Exporter
actions-filter = Filtrer
actions-help = Aide
actions-import = Importer
actions-manage = Gérer...
actions-name = Nom :
actions-new = Nouvelles
actions-new-name = Nouveau nom :
actions-options = Options
actions-options-for = Options pour { $val }
actions-preview = Aperçu
actions-rebuild = Reconstruire
actions-rename = Renommer
actions-rename-deck = Renommer le paquet
actions-rename-tag = Renommer le tag
actions-rename-with-parents = Renommer avec les parents
actions-remove-tag = Enlever le tag
actions-replay-audio = Rejouer le son
actions-reposition = Repositionner
actions-save = Enregistrer
actions-search = Chercher
actions-select = Sélectionner
actions-shortcut-key = Raccourci : { $val }
actions-suspend-card = Suspendre la carte
actions-set-due-date = Définir une date d'échéance
actions-answer-card = Réponse
actions-unbury-unsuspend = Déterrer/Enlever la suspension
actions-add-deck = Ajouter un paquet
actions-add-note = Ajouter une note
actions-update-tag = Modifier le tag
actions-update-note = Modifier la note
actions-update-card = Modifier la carte
actions-update-deck = Modifier le paquet
actions-forget-card = Oublier la carte
actions-build-filtered-deck = Construire le paquet
actions-add-notetype = Ajouter un type de note
actions-remove-notetype = Enlever le type de note
actions-update-notetype = Modifier le type de note
actions-update-config = Modifier la configuration
actions-card-info = Info carte
actions-previous-card-info = Informations de la carte précédente
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action } ...
actions-currently-unsupported = Cette action est actuellement non supportée sur votre système.

## Flags

actions-flag-number = Marqueur { $number }
actions-flag-red = Rouge
actions-flag-orange = Orange
actions-flag-green = Vert
actions-flag-blue = Bleu
actions-flag-pink = Rose
actions-flag-turquoise = Turquoise
actions-flag-purple = Violet
actions-set-flag = Définir le marqueur
