preferences-automatically-sync-on-profile-openclose = Synchroniser automatiquement à l’ouverture et à la fermeture
preferences-backups = Sauvegardes
preferences-basic = Basique
preferences-change-deck-depending-on-note-type = Changer le paquet selon le type de note
preferences-changes-will-take-effect-when-you = Les modifications prendront effet au redémarrage d'Anki.
preferences-hours-past-midnight = heure(s) après minuit
preferences-interface-language = Langue de l’interface
preferences-interrupt-current-audio-when-answering = Interrompre l’audio en cours de lecture lors de la réponse
preferences-learn-ahead-limit = Réviser en avance de
preferences-mins = minute(s)
preferences-network = Réseau
preferences-next-day-starts-at = Le jour suivant démarre à
preferences-note-media-is-not-backed-up = Information : les médias ne sont pas restaurés. Il serait sage de sauvegarder régulièrement votre dossier Anki.
preferences-on-next-sync-force-changes-in = À la prochaine synchronisation, forcer les changements dans une direction.
preferences-paste-clipboard-images-as-png = Coller les images du presse-papier en PNG.
preferences-paste-without-shift-key-strips-formatting = Coller sans maintenir la touche Maj retire le formatage
preferences-periodically-sync-media = Synchroniser périodiquement les médias
preferences-please-restart-anki-to-complete-language = Veuillez redémarrer Anki pour finaliser le changement de langue.
preferences-preferences = Préférences
preferences-scheduling = Replanifier
preferences-show-learning-cards-with-larger-steps = Montrer les cartes en cours d’apprentissage avec de plus grand pas avant de les revoir
preferences-show-next-review-time-above-answer = Afficher la date de la prochaine révision au dessus des boutons
preferences-show-play-buttons-on-cards-with = Afficher les boutons de lecture sur les cartes avec de l’audio
preferences-show-remaining-card-count-during-review = Afficher le nombre de cartes restantes durant la révision
preferences-some-settings-will-take-effect-after = Certains réglages ne s’appliqueront qu’après le redémarrage d’Anki.
preferences-synchronisation = <b>Synchronisation</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Synchronisation</b><br> Désactivée pour le moment ; pour l’activer cliquez sur le bouton de synchronisation dans la fenêtre principale.
preferences-synchronize-audio-and-images-too = Synchroniser l’audio et les images également
preferences-timebox-time-limit = Montrer la progression toutes les
preferences-user-interface-size = Taille de l’interface
preferences-when-adding-default-to-current-deck = Ajouter par défaut au paquet courant
preferences-you-can-restore-backups-via-fileswitch = Vous pouvez restaurer les sauvegardes en passant par Fichier > Changer de compte.
preferences-legacy-timezone-handling = Ancienne gestion des fuseaux horaires (bugué, mais nécessaire pour AnkiDroid <= 2.14)
preferences-default-search-text = Texte de recherche par défaut
preferences-default-search-text-example = par exemple: 'deck:current'
preferences-theme-label = Thème:{ $theme }
preferences-theme-follow-system = Suivre le système
preferences-theme-light = Clair
preferences-theme-dark = Sombre
preferences-v3-scheduler = Planificateur V3
preferences-ignore-accents-in-search = Ignorer les accents lors de la recherche (plus lent)
preferences-backup-explanation =
    Anki sauvegarde périodiquement votre collection. Lorsque les sauvegardes ont plus de 2 jours,¶
    Anki commencera à supprimer certaines d'entre elles pour libérer de l'espace disque.
preferences-daily-backups = Sauvegardes journalières à conserver:
preferences-weekly-backups = Sauvegardes hebdomadaires à conserver:
preferences-monthly-backups = Sauvegardes mensuelles à conserver:
preferences-minutes-between-backups = Minutes entre les sauvegardes automatiques :
preferences-reduce-motion = Réduire le mouvement
preferences-reduce-motion-tooltip = Désactiver les animations et transitions de l'interface utilisateur
preferences-theme = Thème
preferences-editing = Modification
