actions-add = Añadir
actions-all-selected = Todo seleccionado
actions-any-selected = Nada seleccionado
actions-cancel = Cancelar
actions-choose = Seleccionar
actions-close = Cerrar
actions-copy = Copiar
actions-create-copy = Crear copia
actions-custom-study = Estudio personalizado
actions-decks = Mazos
actions-decrement-value = Disminuir valor
actions-delete = Eliminar
actions-export = Exportar
actions-filter = Filtrar
actions-help = Ayuda
actions-increment-value = Aumentar valor
actions-import = Importar
actions-manage = Gestionar…
actions-name = Nombre
actions-new = Nuevas
actions-new-name = Nombre nuevo:
actions-options = Opciones
actions-options-for = Opciones para { $val }
actions-preview = Previsualizar
actions-rebuild = Reconstruir
actions-rename = Renombrar
actions-rename-deck = Renombrar mazo
actions-rename-tag = Renombrar etiqueta
actions-rename-with-parents = Renombrar con los Parientes
actions-remove-tag = Remover etiqueta
actions-replay-audio = Reproducir sonido
actions-reposition = Reposición
actions-save = Guardar
actions-search = Buscar
actions-select = Seleccione
actions-shortcut-key = Tecla de atajo: { $val }
actions-suspend-card = Suspender tarjeta
actions-set-due-date = Establecer fecha de revisión
actions-answer-card = Contestar tarjeta
actions-unbury-unsuspend = Desenterrar/Deshacer suspensión
actions-add-deck = Añadir mazo
actions-add-note = Añadir nota
actions-update-tag = Actualizar etiqueta
actions-update-note = Actualizar nota
actions-update-card = Actualizar tarjeta
actions-update-deck = Actualizar mazo
actions-forget-card = Olvidar Tarjeta
actions-build-filtered-deck = Crear Mazo
actions-add-notetype = Añadir tipo de nota
actions-remove-notetype = Eliminar tipo de nota
actions-update-notetype = Actualizar tipo de nota
actions-update-config = Actualizar configuración
actions-card-info = Información de la tarjeta
actions-previous-card-info = Información de la tarjeta anterior
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action } ...
actions-currently-unsupported = Esta acción actualmente no es compatible con su sistema.

## Flags

actions-flag-number = Marcador { $number }
actions-flag-red = Rojo
actions-flag-orange = Naranja
actions-flag-green = Verde
actions-flag-blue = Azul
actions-flag-pink = Rosado
actions-flag-turquoise = Turquesa
actions-flag-purple = Morado
actions-set-flag = Elegir marcador
