adding-add-shortcut-ctrlandenter = Añadir (atajo: ctrl+enter)
adding-added = Añadidas
adding-close-and-lose-current-input = ¿Cerrar y perder la información actual?
adding-edit = Editar "{ $val }"
adding-history = Historia
adding-note-deleted = (Nota borrada)
adding-shortcut = Atajo: { $val }
adding-the-first-field-is-empty = El primer campo está vacío.
adding-you-have-a-cloze-deletion-note = Tienes un tipo de nota de huecos pero no has insertado ningún hueco. ¿Quieres continuar?
adding-cloze-outside-cloze-notetype = Solo se puede anidar una respuesta en notas de tipo Respuesta Anidada
adding-cloze-outside-cloze-field = El anidamiento de una respuesta solo se puede usar en campos que usan el filtro 'Respuesta Anidada:'. Este suele ser el primer campo (Texto).
