decks-add-new-deck-ctrlandn = Añadir nuevo mazo (Ctrl+N)
decks-build = Construir
decks-cards-selected-by = tarjetas seleccionadas por
decks-create-deck = Crear mazo
decks-custom-steps-in-minutes = Pasos personalizados (en minutos)
decks-deck = Mazo
decks-decreasing-intervals = Intervalos decrecientes
decks-delete-deck = Eliminar mazo
decks-enable-second-filter = Activar el filtro secundario
decks-filter = Filtrar:
decks-filter-2 = Filtro 2
decks-get-shared = Descargar mazos compartidos
decks-import-file = Importar archivo
decks-increasing-intervals = Intervalos crecientes
decks-latest-added-first = Últimas añadidas primero
decks-limit-to = Limitar a
decks-minutes = minutos
decks-most-lapses = Más veces olvidadas
decks-new-deck-name = Nombre del nuevo mazo:
decks-no-deck = [sin baraja]
decks-oldest-seen-first = Mostrar antes las más viejas
decks-order-added = Orden añadido
decks-order-due = Orden de programadas
decks-please-select-something = Por favor, selecciona algo.
decks-random = Aleatorio
decks-relative-overdueness = Atraso relativo
decks-repeat-failed-cards-after = Repetir tarjetas fallidas tras
decks-reschedule-cards-based-on-my-answers = Reprogramar tarjetas en función de mis respuestas en este mazo
decks-study = Estudiar
decks-study-deck = Estudiar mazo
decks-filtered-deck-search-empty = No se encontraron tarjetas coincidentes. Algunas tarjetas pueden quedar excluidas de la búsqueda porque están suspendidas o en un mazo filtrado diferente.
decks-unmovable-cards = Mostrar cualquier tarjeta excluida
