editing-actual-size = Activar/Desactivar tamaño real
editing-add-media = Añadir archivos multimedia
editing-align-left = Alinear a la izquierda
editing-align-right = Alinear a la derecha
editing-an-error-occurred-while-opening = Ocurrió un error al abrir { $val }
editing-attach-picturesaudiovideo = Adjuntar imágenes/audio/video
editing-bold-text = Texto en negrita
editing-cards = Tarjetas
editing-center = Centrar
editing-change-color = Cambiar el color
editing-cloze-deletion = Nuevo nido de respuesta anidada (nueva tarjeta)
editing-cloze-deletion-repeat = Mismo nido de respuesta anidada (misma tarjeta)
editing-couldnt-record-audio-have-you-installed = No se pudo grabar el audio. Tienes instalado "lame"?
editing-customize-card-templates = Personalizar plantillas de tarjetas
editing-customize-fields = Personalizar campos
editing-cut = Cortar
editing-double-click-image = Haga doble clic en la imagen
editing-double-click-to-expand = (doble clic para expandir)
editing-double-click-to-collapse = doble clic para reducir
editing-edit-current = Editar actual
editing-edit-html = Editar HTML
editing-fields = Campos
editing-float-left = Flotante a la izquierda
editing-float-right = Flotante a la derecha
editing-float-none = No flotante
editing-indent = Aumentar la sangría
editing-italic-text = Texto en cursiva
editing-jump-to-tags-with-ctrlandshiftandt = Saltar a etiquetas con Ctrl+Mayús+T
editing-justify = Justificar
editing-latex = LaTeX
editing-latex-equation = Ecuación LaTeX
editing-latex-math-env = Entorno matemático LaTeX
editing-mathjax-block = Bloque de MathJacx
editing-mathjax-chemistry = Química MathJax
editing-mathjax-inline = MathJacx en línea
editing-mathjax-placeholder = Presione { $accept } para aceptar, { $newline } para nueva línea.
editing-media = Multimedia
editing-ordered-list = Lista numerada
editing-outdent = Disminuir la sangría
editing-paste = Pegar
editing-record-audio = Grabar audio
editing-remove-formatting = Quitar formato
editing-restore-original-size = Restaurar tamaño original
editing-select-remove-formatting = Seleccionar formato para eliminar
editing-show-duplicates = Mostrar duplicados
editing-subscript = Subíndice
editing-superscript = Índice superior
editing-tags = Etiquetas
editing-tags-add = Agregar etiqueta
editing-tags-copy = Copiar etiquetas
editing-tags-remove = Remover etiquetas
editing-tags-select-all = Seleccionar todas las etiquetas
editing-text-color = Color de texto
editing-text-highlight-color = Color de resaltado de texto
editing-to-make-a-cloze-deletion-on = Para crear preguntas anidadas en una nota existente, primero debe cambiarla a un tipo de nota de Respuesta Anidada, mediante 'Editar>Cambiar tipo de nota'.
editing-toggle-html-editor = Activar/Desactivar editor HTML
editing-toggle-visual-editor = Ocultar/mostrar el Editor Visual
editing-toggle-sticky = Activar/Desactivar anclaje del texto
editing-expand = Expandir
editing-collapse = Reducir
editing-expand-field = Expandir campo
editing-collapse-field = Colapsar campo
editing-underline-text = Subrayar texto
editing-unordered-list = Lista con viñetas
editing-warning-cloze-deletions-will-not-work = Cuidado, los huecos no funcionarán a menos que cambies el tipo de nota a Huecos.
editing-mathjax-preview = MathJax Vista previa
editing-shrink-images = Reducir imágenes
editing-close-html-tags = Etiquetas HTML de cierre automático

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Editor HTML
