fields-add-field = Añadir campo
fields-delete-field-from = ¿Eliminar campo de { $val }?
fields-editing-font = Editando fuente
fields-field = Campo:
fields-field-name = Nombre del campo:
fields-description = Descripción
fields-description-placeholder = Información para mostrar junto al nombre del campo en la pantalla de edición
fields-fields-for = Campos para { $val }
fields-font = Fuente:
fields-new-position-1 = Nueva posición (1...{ $val }):
fields-notes-require-at-least-one-field = Las notas requieren al menos un campo.
fields-reverse-text-direction-rtl = Dirección inversa de texto (RTL)
fields-collapse-by-default = Colapsar por defecto
fields-html-by-default = Usar editor HTML por defecto
fields-size = Tamaño:
fields-sort-by-this-field-in-the = Ordenar según este campo en el explorador
fields-that-field-name-is-already-used = Ese nombre de campo ya está siendo usado.
fields-name-first-letter-not-valid = El nombre del campo no debe comenzar con #, ^ o /.
fields-name-invalid-letter = El nombre del campo no debe contener  :, ", { "{" } or { "}" }.
