preferences-automatically-sync-on-profile-openclose = Sincronizar automáticamente al abrir/cerrar el perfil
preferences-backups = Copias de seguridad
preferences-basic = Básico
preferences-change-deck-depending-on-note-type = Cambiar mazo en función del tipo de nota
preferences-changes-will-take-effect-when-you = Los cambios se aplicarán cuando reinicies Anki.
preferences-hours-past-midnight = horas pasada la medianoche
preferences-language = Idioma
preferences-interrupt-current-audio-when-answering = Interrumpir el audio actual al responder
preferences-learn-ahead-limit = Límite del estudio por adelantado
preferences-mins = mins
preferences-network = Red
preferences-next-day-starts-at = El siguiente día empieza a las
preferences-media-is-not-backed-up = No existe ninguna copia de seguridad de los archivos multimedia. Por motivos de seguridad, haz una copia de la carpeta Anki periódicamente.
preferences-on-next-sync-force-changes-in = Forzar cambios en una dirección en la próxima sincronización
preferences-paste-clipboard-images-as-png = Pegar imágenes del portapapeles como PNG
preferences-paste-without-shift-key-strips-formatting = Pegar sin la tecla Mayús elimina el formato
preferences-periodically-sync-media = Sincronizar archivos multimedia periódicamente
preferences-please-restart-anki-to-complete-language = Por favor, reinicia Anki para completar el cambio de idioma.
preferences-preferences = Preferencias
preferences-scheduling = Programación
preferences-show-learning-cards-with-larger-steps = Mostrar las tarjetas en aprendizaje con pasos mayores antes de los repasos
preferences-show-next-review-time-above-answer = Mostrar intervalo de próximo repaso encima de los botones de respuesta
preferences-show-play-buttons-on-cards-with = Mostrar botones de reproducción en tarjetas con audio
preferences-show-remaining-card-count = Mostrar el número de tarjetas restantes
preferences-some-settings-will-take-effect-after = Algunos ajustes tendrán efecto después de reiniciar Anki.
preferences-tab-synchronisation = Sincronización
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sincronización</b><br> Actualmente no está activada; haz clic en el botón de sincronizar en la pantalla principal para activarla.
preferences-synchronize-audio-and-images-too = Sincronizar también los sonidos y las imágenes
preferences-timebox-time-limit = Límite de sesión de estudio
preferences-user-interface-size = Tamaño de interfaz de usuario
preferences-when-adding-default-to-current-deck = Al añadir, hacerlo en el mazo actual de manera predeterminada
preferences-you-can-restore-backups-via-fileswitch = Puedes restaurar copias de seguridad con Archivo>Cambiar perfil.
preferences-legacy-timezone-handling = Gestión de zonas horarias antiguas (con errores, pero necesario para AnkiDroid <= 2.14)
preferences-default-search-text = Texto de búsqueda predeterminado
preferences-default-search-text-example = Por ejemplo: 'mazo:actual '
preferences-theme = Tema
preferences-theme-follow-system = Seguir el sistema
preferences-theme-light = Claro
preferences-theme-dark = Oscuro
preferences-v3-scheduler = Algoritmo de planificación V3
preferences-ignore-accents-in-search = Ignorar acentos en la búsqueda (más lento)
preferences-backup-explanation =
    Anki periódicamente hace una copia de seguridad de tu colección. Después de que las 
    copias de seguridad tengan más de 2 días, Anki comenzará a eliminar algunas de ellas 
    para liberar espacio en el disco.
preferences-daily-backups = Copias de seguridad diarias para mantener:
preferences-weekly-backups = Copias de seguridad semanales para mantener:
preferences-monthly-backups = Número de copias de seguridad mensuales a mantener:
preferences-minutes-between-backups = Tiempo entre copias de seguridad automáticas (en minutos):
preferences-reduce-motion = Reducir el movimiento
preferences-reduce-motion-tooltip = Deshabilita las animaciones y transiciones de la interfaz de usuario
preferences-custom-sync-url = Servidor de sincronización propio
preferences-custom-sync-url-disclaimer = Si eres un usuario avanzado, consulta el manual.
preferences-hide-top-bar-during-review = Esconder la barra superior durante los repasos
preferences-hide-bottom-bar-during-review = Esconder la barra inferior durante los repasos
preferences-always = Siempre
preferences-full-screen-only = Solo a pantalla completa
preferences-appearance = Apariencia
preferences-general = General
preferences-style = Estilo
preferences-review = Repasar
preferences-reviewer = Revisor
preferences-distractions = Distracciones
preferences-minimalist-mode = Modo minimalista
preferences-editing = Edición
preferences-browsing = Navegación
preferences-default-deck = Mazo por defecto
preferences-account = Cuenta de AnkiWeb
preferences-media = Multimedia
preferences-note = Nota
preferences-scheduler = Planificador
preferences-user-interface = Interfaz de usuario
preferences-import-export = Importar/Exportar
