actions-add = Přidat
actions-all-selected = Všechny vybrané
actions-any-selected = Kterýkoli vybraný
actions-cancel = Zrušit
actions-choose = Zvolit
actions-close = Zavřít
actions-copy = Kopírovat
actions-create-copy = Vytvořit kopii
actions-custom-study = Vlastní studium
actions-decks = Balíčky
actions-decrement-value = Snížit hodnotu
actions-delete = Odstranit
actions-export = Exportovat
actions-filter = Filtrovat
actions-help = Nápověda
actions-increment-value = Zvýšit hodnotu
actions-import = Importovat
actions-manage = Spravovat...
actions-name = Název:
actions-new = Nové
actions-new-name = Nový název:
actions-options = Možnosti
actions-options-for = Možnosti pro { $val }
actions-preview = Náhled
actions-rebuild = Znovu sestavit
actions-rename = Přejmenovat
actions-rename-deck = Přejmenovat balíček
actions-rename-tag = Přejmenovat štítek
actions-rename-with-parents = Přejmenovat včetně nadřazených
actions-remove-tag = Odstranit štítek
actions-replay-audio = Přehrát zvuk
actions-reposition = Změnit pořadí
actions-save = Uložit
actions-search = Hledat
actions-select = Vybrat
actions-shortcut-key = Zkratka: { $val }
actions-suspend-card = Vyřadit kartu
actions-set-due-date = Nastavit datum zkoušení
actions-answer-card = Zodpovědět kartu
actions-unbury-unsuspend = Zrušit přeskočení/vyřazení
actions-add-deck = Přidat balíček
actions-add-note = Přidat poznámku
actions-update-tag = Aktualizovat štítek
actions-update-note = Aktualizovat poznámku
actions-update-card = Aktualizovat kartu
actions-update-deck = Aktualizovat balíček
actions-forget-card = Zapomenout kartu
actions-build-filtered-deck = Sestavit balíček
actions-add-notetype = Přidat typ poznámky
actions-remove-notetype = Odstranit typ poznámky
actions-update-notetype = Aktualizovat typ poznámky
actions-update-config = Aktualizovat nastavení
actions-card-info = Informace o kartě
actions-previous-card-info = Informace o předchozí kartě
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = Tato akce v současnosti není na Vašem systému podporována.

## Flags

actions-flag-number = Příznak { $number }
actions-flag-red = Červený
actions-flag-orange = Oranžový
actions-flag-green = Zelený
actions-flag-blue = Modrý
actions-flag-pink = Růžový
actions-flag-turquoise = Tyrkysový
actions-flag-purple = Purpurový
actions-set-flag = Nastavit příznak
