adding-add-shortcut-ctrlandenter = Přidat (zkratka: ctrl+enter)
adding-added = Přidáno
adding-close-and-lose-current-input = Zavřít a zrušit momentálně vkládaná data?
adding-edit = Upravit "{ $val }"
adding-history = Historie
adding-note-deleted = (Poznámka odstraněna)
adding-shortcut = Zkratka: { $val }
adding-the-first-field-is-empty = První pole je prázdné.
adding-you-have-a-cloze-deletion-note = Máte zvolený typ poznámky doplňovačka, ale žádné doplňovačky v poznámce nemáte. Pokračovat?
adding-cloze-outside-cloze-notetype = Doplňovačka se může použít pouze na typu poznámek doplňovačka.
adding-cloze-outside-cloze-field = Doplňovačka se může použít pouze v polích, které používají filtr „cloze:“. To je obvykle první pole.
