preferences-automatically-sync-on-profile-openclose = Automaticky synchronizovat při otevření a zavření profilu
preferences-backups = Zálohy
preferences-basic = Základní
preferences-change-deck-depending-on-note-type = Změnit balíček v závislosti na typu poznámky
preferences-changes-will-take-effect-when-you = Změny se projeví až po restartování Anki.
preferences-hours-past-midnight = hodin po půlnoci
preferences-language = Jazyk
preferences-interrupt-current-audio-when-answering = Po odpovědi přerušit aktuální zvuk
preferences-learn-ahead-limit = Učit se navíc
preferences-mins = minut
preferences-network = Síť
preferences-next-day-starts-at = Další den začíná v
preferences-media-is-not-backed-up = Média se nezálohují. Prosím vytvořte si pravidelné zálohy vašeho adresáře Anki.
preferences-on-next-sync-force-changes-in = Při příští synchronizaci vynutit změny v jednom směru
preferences-paste-clipboard-images-as-png = Vložit obrázek ze schránky jako PNG
preferences-paste-without-shift-key-strips-formatting = Vložit bez klávesy shift bez formátování
preferences-periodically-sync-media = Pravidelně synchronizovat multimédia
preferences-please-restart-anki-to-complete-language = Pro dokončení změny jazyka prosím Anki restartujte.
preferences-preferences = Předvolby
preferences-scheduling = Plánování
preferences-show-learning-cards-with-larger-steps = Zobrazit karty k učení s delšími kroky před opakováním
preferences-show-next-review-time-above-answer = Zobrazovat čas do příštího opakování nad tlačítky
preferences-show-play-buttons-on-cards-with = Zobrazovat tlačítka přehrát na kartách, které obsahují zvuk
preferences-some-settings-will-take-effect-after = Některá nastavení se projeví až po restartu Anki.
preferences-tab-synchronisation = Synchronizace
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Synchronizace</b><br> Neni momentálně povolena; pro zapnutí kliknětě na tlačítko „Synchronizace“ v hlavním okně.
preferences-synchronize-audio-and-images-too = Synchronizovat i obrázky a zvuky
preferences-timebox-time-limit = Limit pro časový box
preferences-user-interface-size = Velikost uživatelského rozhraní
preferences-when-adding-default-to-current-deck = Při přidávání standardně nastaven aktuální balíček
preferences-you-can-restore-backups-via-fileswitch = Můžete obnovit ze zálohy přes Soubor > Přepnout profil.
preferences-legacy-timezone-handling = Zastaralé zpracování časového pásma (zabugované, ale požadováno pro AnkiDroid <= 2.14)
preferences-default-search-text = Výchozí text vyhledání
preferences-default-search-text-example = např. „deck:current“
preferences-theme = Motiv
preferences-theme-follow-system = Podle systému
preferences-theme-light = Světlý
preferences-theme-dark = Tmavý
preferences-v3-scheduler = V3 plánovač
preferences-ignore-accents-in-search = Ignorovat diakritiku ve vyhledávání (pomalejší)
preferences-backup-explanation =
    Anki pravidelně zálohuje Vaši kolekci. Jestliže jsou zálohy více než 2 dny staré,
    Anki začne odstraňovat některé z nich, aby uvolnil místo na disku.
preferences-daily-backups = Počet denních záloh, které se mají zachovat:
preferences-weekly-backups = Počet týdenních záloh, které se mají zachovat:
preferences-monthly-backups = Počet měsíčních záloh, které se mají zachovat:
preferences-minutes-between-backups = Počet minut mezi automatickými zálohami:
preferences-reduce-motion = Omezit pohyb
preferences-reduce-motion-tooltip = Zakázat různé animace a přechody uživatelského rozhraní
preferences-custom-sync-url = Vlastní synchronizační server
preferences-custom-sync-url-disclaimer = Pro pokročilé uživatele, viz příručku
preferences-hide-top-bar-during-review = Skrýt horní lištu během opakování
preferences-hide-bottom-bar-during-review = Skrýt dolní lištu během opakování
preferences-appearance = Vzhled
preferences-general = Obecné
preferences-style = Styl
preferences-review = Opakování
preferences-distractions = Rozptylování
preferences-minimalist-mode = Minimalistický režim
preferences-editing = Editování
preferences-browsing = Prohlížení
preferences-default-deck = Výchozí balíček
preferences-account = Účet AnkiWeb
preferences-note = Poznámka
preferences-scheduler = Plánovač
preferences-user-interface = Uživatelské rozhraní
preferences-import-export = Import/Export
