actions-add = הוסף
actions-all-selected = כל אלו שנבחרו
actions-any-selected = כל אחד שנבחר
actions-cancel = ביטול
actions-choose = בחר
actions-close = סגירה
actions-copy = העתק
actions-create-copy = צור עותק
actions-custom-study = לימוד מותאם
actions-decks = חפיסות
actions-decrement-value = הפחת ערך
actions-delete = מחק
actions-export = ייצוא
actions-filter = סנן
actions-help = עזרה
actions-increment-value = הגדל ערך
actions-import = ייבוא
actions-manage = נהל...
actions-name = שם:
actions-new = חדשים
actions-new-name = שם חדש:
actions-options = אפשרויות
actions-options-for = אפשרויות ל-{ $val }
actions-preview = תצוגה מקדימה
actions-rebuild = בנה מחדש
actions-rename = שנה שם
actions-rename-deck = שנה שם חפיסה
actions-rename-tag = שנה תגית
actions-rename-with-parents = שנה שם עם הורים
actions-remove-tag = הסר תגית
actions-replay-audio = נגן אודיו מחדש
actions-reposition = שנה מיקום
actions-save = שמור
actions-search = חיפוש
actions-select = בחירה
actions-shortcut-key = מקש קיצור: { $val }
actions-suspend-card = השהה כרטיס
actions-set-due-date = הגדר תאריך יעד
actions-answer-card = ענה על כרטיס
actions-unbury-unsuspend = הוצא מהטמנה/השהיה
actions-add-deck = הוסף חפיסה
actions-add-note = הוסף רשומה
actions-update-tag = עדכן תגית
actions-update-note = עדכן רשומה
actions-update-card = עדכן כרטיס
actions-update-deck = עדכן חפיסה
actions-forget-card = שכח כרטיס (איפוס תזמונים)
actions-build-filtered-deck = בנה חפיסה
actions-add-notetype = הוסף סוג רשומה
actions-remove-notetype = הסר סוג רשומה
actions-update-notetype = עדכן סוג רשומה
actions-update-config = עדכן הגדרה
actions-card-info = מידע כרטיס
actions-previous-card-info = מידע כרטיס קודם
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = פעולה זו אינה נתמכת במערכת שלך נכון לעכשיו.

## Flags

actions-flag-number = דגל#{ $number }
actions-flag-red = אדום
actions-flag-orange = כתום
actions-flag-green = ירוק
actions-flag-blue = כחול
actions-flag-pink = ורוד
actions-flag-turquoise = טורקיז
actions-flag-purple = סגול
actions-set-flag = הגדר דגל
