editing-actual-size = שנה גודל
editing-add-media = הוסף מדיה
editing-align-left = יישור לשמאל
editing-align-right = יישור לימין
editing-an-error-occurred-while-opening = שגיאה התרחשה בזמן פתיחת { $val }
editing-attach-picturesaudiovideo = צרף תמונות/שמע/וידאו
editing-bold-text = טקסט מודגש
editing-cards = כרטיסים
editing-center = מרכז
editing-change-color = שינוי צבע
editing-cloze-deletion = השלם את החסר
editing-cloze-deletion-repeat = הסתרת טקסט (באותו כרטיס)
editing-couldnt-record-audio-have-you-installed = הקלטת אודיו נכשלה. האם התקנת 'lame'?
editing-customize-card-templates = שנה תבניות כרטיס
editing-customize-fields = התאם אישית שדות
editing-cut = גזור
editing-double-click-image = לחץ פעמיים על התמונה
editing-double-click-to-expand = (לחץ פעמיים כדי להרחיב)
editing-double-click-to-collapse = לחיצה כפולה כדי לכווץ
editing-edit-current = ערוך נוכחי
editing-edit-html = ערוך HTML
editing-fields = שדות
editing-float-left = הצמד לשמאל
editing-float-right = הצמד לימין
editing-float-none = ללא הצמדה
editing-indent = הגדל הזחה
editing-italic-text = טקסט נטוי
editing-jump-to-tags-with-ctrlandshiftandt = עבור לתגיות עם Ctrl+Shift+T
editing-justify = יישור לשני הצדדים
editing-latex = LaTeX
editing-latex-equation = משוואת LaTeX
editing-latex-math-env = סביבת מתמטיקה באמצעות LaTeX
editing-mathjax-block = בלוק MathJax
editing-mathjax-chemistry = כימיה באמצעות MathJax
editing-mathjax-inline = MathJax כחלק משורה
editing-mathjax-placeholder = לחץ על { $accept } כדי לאשר, { $newline } עבור שורה חדשה.
editing-media = מדיה
editing-ordered-list = רשימה (מספרים)
editing-outdent = הקטן הזחה
editing-paste = הדבק
editing-record-audio = הקלט שמע
editing-remove-formatting = הסר עיצוב
editing-restore-original-size = שחזר את הגודל המקורי
editing-select-remove-formatting = בחר עיצוב להסרה
editing-show-duplicates = הצג כפילויות
editing-subscript = כתב תחתי
editing-superscript = ‏‏כתב עילי
editing-tags = תגיות
editing-tags-add = הוסף תגית
editing-tags-copy = העתק תגיות
editing-tags-remove = הסר תגיות
editing-tags-select-all = בחר את כל התגיות
editing-text-color = צבע טקסט
editing-text-highlight-color = צבע רקע לטקסט
editing-to-make-a-cloze-deletion-on = ליצור השלם את החסר ברשומה קיימת, תצטרך לשנות את סוג הרשומה להשלם את החסר, דרך 'רשומות>שנה סוג רשומה'
editing-toggle-html-editor = עורך HTML
editing-toggle-visual-editor = הצגת עורך טקסט
editing-toggle-sticky = שמור שדה לשאלה הבאה
editing-expand = הרחב
editing-collapse = כווץ
editing-expand-field = הרחב את השדה
editing-collapse-field = כיווץ שדה
editing-underline-text = קו תחתון
editing-unordered-list = רשימה (נקודות)
editing-warning-cloze-deletions-will-not-work = אזהרה, השלם את החסר לא יעבוד עד שתשנה את הסוג למעלה להשלם את החסר.
editing-mathjax-preview = תצוגה מקדימה של MathJax
editing-shrink-images = כווץ תמונות
editing-close-html-tags = סגירה אוטומטית של תגיות HTML

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = עורך HTML
