fields-add-field = הוסף שדה
fields-delete-field-from = מחק שדה מ-{ $val }?
fields-editing-font = ערוך גופן
fields-field = שדה:
fields-field-name = שם שדה:
fields-description = הסבר
fields-description-placeholder = הסבר המוצג בריחוף עכבר לצד שם השדה במסך העריכה
fields-fields-for = שדות עבור { $val }
fields-font = גופן:
fields-new-position-1 = מיקום חדש (1...{ $val }):
fields-notes-require-at-least-one-field = רשומות חייבות להכיל לפחות שדה אחת
fields-reverse-text-direction-rtl = הפוך כיוון טקסט (יישור מימין-לשמאל)
fields-collapse-by-default = כווץ כברירת מחדל
fields-html-by-default = השתמש בעורך HTML כברירת מחדל
fields-size = גודל:
fields-sort-by-this-field-in-the = מיין לפי שדה זה בדפדוף בכרטיסים
fields-that-field-name-is-already-used = שם השדה כבר בשימוש.
fields-name-first-letter-not-valid = שם השדה לא יכול להתחיל ב #, ^ או /.
fields-name-invalid-letter = שם השדה אינו יכול להכיל: , ", { "{" } או { "}" }.
