preferences-automatically-sync-on-profile-openclose = סנכרן אוטומטית בעת פתיחה\סגירה של פרופיל
preferences-backups = גיבויים
preferences-change-deck-depending-on-note-type = שנה חפיסה בהתאם לסוג רשומה
preferences-changes-will-take-effect-when-you = השינויים ייכנסו לתוקף כשתתחיל את Anki מחדש.
preferences-hours-past-midnight = שעות לאחר חצות
preferences-language = שפה
preferences-interrupt-current-audio-when-answering = הפסק שמע נוכחי בעת תשובה
preferences-learn-ahead-limit = לימוד מעבר למכסה
preferences-mins = דקות
preferences-network = רשת
preferences-next-day-starts-at = היום הבא מתחיל ב-
preferences-media-is-not-backed-up = קבצי מדיה אינם מגובים. כדי למנוע איבוד חומר צור גיבוי תקופתי בתיקיית Anki.
preferences-on-next-sync-force-changes-in = בסינכרון הבא, הכרח שינויים בכיוון אחד
preferences-paste-clipboard-images-as-png = הדבק תמונה מהלוח כ-PNG
preferences-paste-without-shift-key-strips-formatting = הדבקה ללא עיצוב (לשינוי לחץ shift)
preferences-periodically-sync-media = סינכרון מדיה תקופתי
preferences-please-restart-anki-to-complete-language = התחל מחדש את Anki כדי להשלים החלפת שפה.
preferences-preferences = העדפות
preferences-scheduling = תזמון
preferences-show-learning-cards-with-larger-steps = הצג כרטיסים בלמידה שיש להם צעדים גדולים, לפני החזרות
preferences-show-next-review-time-above-answer = הצג את זמן החזרה הבאה מעל כפתורי התשובה
preferences-show-play-buttons-on-cards-with = הצג כפתורי הפעלה על כרטיסים עם אודיו
preferences-show-remaining-card-count = הצג את ספירת הכרטיסים שנותרו
preferences-some-settings-will-take-effect-after = מספר הגדרות יחולו רק לאחר אתחול Anki.
preferences-tab-synchronisation = סינכרון
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>סנכרון</b><br> לא מופעל כרגע; לחץ על כפתור "סנכרן" בחלון הראשי כדי להפעיל.‏
preferences-synchronize-audio-and-images-too = סנכרן גם אודיו ותמונות
preferences-timebox-time-limit = הגבלת זמן בתיבת הזמן
preferences-user-interface-size = גודל ממשק המשתמש
preferences-when-adding-default-to-current-deck = בעת הוספה, ברירת המחדל היא הוספה לחפיסה הנוכחית
preferences-you-can-restore-backups-via-fileswitch = באפשרותך לשחזר מגיבוי דרך קובץ>החלף פרופיל.
preferences-legacy-timezone-handling = תאריך ושעה ידניים (פחות יציב, אך נדרש עבור AnkiDroid בגרסאות <= 2.14).
preferences-default-search-text = טקסט או פקודת ברירת המחדל לחיפוש
preferences-default-search-text-example = למשל: 'deck:current ' (להצגת חפיסה נוכחית)
preferences-theme = ערכת נושא
preferences-theme-follow-system = עקוב אחר מערכת
preferences-theme-light = בהיר
preferences-theme-dark = כהה
preferences-v3-scheduler = מתזמן V3
preferences-ignore-accents-in-search = התעלם ממבטאים בחיפוש (איטי יותר)
preferences-backup-explanation =
    אנקי מגבה מדי פעם את האוסף שלך כשהוא סגור. לאחר שהגיבויים הם בני יותר מ2 ימים,
    Anki יסיר חלק מהם כדי לפנות מקום בזיכרון.
preferences-daily-backups = גיבויים יומיים לשמירה:
preferences-weekly-backups = גיבויים שבועיים לשמירה:
preferences-monthly-backups = גיבויים חודשיים לשמירה:
preferences-minutes-between-backups = מרווח דקות בין גיבויים אוטומטיים:
preferences-reduce-motion = הפחת תנועה
preferences-reduce-motion-tooltip = בטל אנימציות ומעברים שונים של ממשק המשתמש
preferences-custom-sync-url = שרת סנכרון עצמי
preferences-custom-sync-url-disclaimer = למשתמשים מתקדמים בלבד - בבקשה קרא את המדריך
preferences-hide-top-bar-during-review = הסתר את הסרגל העליון במהלך המבחן
preferences-hide-bottom-bar-during-review = הסתר את הסרגל התחתון המהלך מבחן
preferences-always = תמיד
preferences-full-screen-only = במצב מסך מלא
preferences-appearance = מראה
preferences-general = כללי
preferences-style = עיצוב
preferences-review = חזרה
preferences-distractions = הסחות דעת
preferences-minimalist-mode = מצב מינימלי
preferences-editing = עריכה
preferences-browsing = דפדוף
preferences-default-deck = חפיסת ברירת מחדל
preferences-account = חשבון AnkiWeb
preferences-note = הערה
preferences-scheduler = מתזמן
preferences-user-interface = ממשק משתמש
preferences-import-export = ייבוא/ייצוא
preferences-network-timeout = פסק זמן לרשת
preferences-reset-window-sizes = אפס גדלי חלונות
preferences-reset-window-sizes-complete = גודלי ומיקומי החלונות אופסו.

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = בסיסי
preferences-reviewer = מסך החזרה
preferences-media = מדיה
