[package]
name = "tugger-rust-toolchain"
version = "0.13.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Discover, download, and use Rust toolchains"
keywords = ["rustup"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[dependencies]
anyhow = "1.0"
flate2 = "1.0"
fs2 = "0.4"
hex = "0.4"
log = "0.4"
once_cell = "1.7"
pgp = "0.8"
sha2 = "0.10"
simple-file-manifest = "0.11"
tar = "0.4"
toml = "0.5"
xz2 = { version = "0.1", features = ["static"] }
zstd = "0.11"

[dependencies.tugger-common]
version = "0.10.0-pre"
path = "../tugger-common"

[dev-dependencies]
dirs = "4.0"
tempfile = "3.2"
