[package]
name = "release"
version = "0.1.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
description = "Performs a release of PyOxidizer"
license = "MPL-2.0"
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"

[dependencies]
anyhow = "1"
cargo-lock = "8"
cargo_toml = "0"
clap = "4"
duct = "0"
# We don't need network functionality.
git2 = { version = "0", default-features = false }
once_cell = "1"
pulldown-cmark = "0.9"
rustdoc-types = "0.18"
semver = "1"
serde_json = "1"
tempfile = "3"
toml = "0"
url = "2"
