on:
  push:
    branches-ignore:
      - 'ci-test'
    tags-ignore:
      - '**'
  pull_request:
  schedule:
    - cron: '13 15 * * *'
  workflow_dispatch:
jobs:
  sphinx:
    strategy:
      fail-fast: false
      matrix:
        dir:
          - python-oxidized-importer/docs
          - pyembed/docs
          - pyoxy/docs
          - tugger/docs
          - docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run Sphinx
        run: |
          python3.9 -m pip install Sphinx==4.2.0
          make -C ${{ matrix.dir }} html
