actions-add = Dodaj
actions-all-selected = Wszystkie wybrane
actions-any-selected = Jakiekolwiek wybrane
actions-cancel = Anuluj
actions-choose = Wybierz
actions-close = Zamknij
actions-copy = Kopiuj
actions-create-copy = Stwórz kopię
actions-custom-study = Nauka własna
actions-decks = Talie
actions-decrement-value = Zmniejszenie wartości
actions-delete = Usuń
actions-export = Eksportuj
actions-filter = Filtr
actions-help = Pomoc
actions-increment-value = Zwiększenie wartości
actions-import = Importuj
actions-manage = Zarządzaj...
actions-name = Nazwa:
actions-new = Nowe
actions-new-name = Nowa nazwa:
actions-options = Opcje
actions-options-for = Opcje dla { $val }
actions-preview = Podgląd
actions-rebuild = Przebuduj
actions-rename = Zmień nazwę
actions-rename-deck = Zmień nazwę talii
actions-rename-tag = Zmień nazwę etykiety
actions-rename-with-parents = Zmiana nazwy wraz z rodzicami
actions-remove-tag = Usunięcie etykiety
actions-replay-audio = Odtworzenie dźwięku
actions-reposition = Zmiana pozycji
actions-save = Zapis
actions-search = Szukanie
actions-select = Wybór
actions-shortcut-key = Skrót klawiszowy: { $val }
actions-suspend-card = Zawieszenie karty
actions-set-due-date = Ustawienie terminu
actions-answer-card = Odpowiedź do karty
actions-unbury-unsuspend = Odkopanie/odwieszenie
actions-add-deck = Dodanie talii
actions-add-note = Dodanie notatki
actions-update-tag = Aktualizacja etykiety
actions-update-note = Aktualizacja notatki
actions-update-card = Aktualizacja karty
actions-update-deck = Aktualizacja talii
actions-forget-card = Zapomnienie karty
actions-build-filtered-deck = Zbudowanie talii
actions-add-notetype = Dodanie typu notatki
actions-remove-notetype = Usunięcie typu notatki
actions-update-notetype = Aktualizacja typu notatki
actions-update-config = Aktualizacja konfiguracji
actions-card-info = Informacje o karcie
actions-previous-card-info = Informacje o poprzedniej karcie
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = Tego działania nie można wykonać na twoim systemie.

## Flags

actions-flag-number = Flaga { $number }
actions-flag-red = Czerwona
actions-flag-orange = Pomarańczowa
actions-flag-green = Zielona
actions-flag-blue = Niebieska
actions-flag-pink = Różowa
actions-flag-turquoise = Turkusowa
actions-flag-purple = Fioletowa
actions-set-flag = Ustaw flagę
