adding-add-shortcut-ctrlandenter = Dodaj (skrót: ctrl+enter)
adding-added = Dodano
adding-close-and-lose-current-input = Zamknąć i porzucić aktualne dane?
adding-edit = Edytuj "{ $val }"
adding-history = Historia
adding-note-deleted = (Notatka usunięta)
adding-shortcut = Skrót: { $val }
adding-the-first-field-is-empty = Pierwsze pole jest puste.
adding-you-have-a-cloze-deletion-note = Wybrano typ Luka, ale nie ma żadnych luk do wypełnienia. Kontynuować?
adding-cloze-outside-cloze-notetype = Luki mogą być użyte tylko w typie notatki Luka.
adding-cloze-outside-cloze-field = Luki mogą być użyte tylko w polach, które używają filtru "cloze:". Zazwyczaj jest to pierwsze pole.
