editing-actual-size = Przełącz rzeczywisty rozmiar
editing-add-media = Dodaj pliki
editing-align-left = Wyrównaj do lewej
editing-align-right = Wyrównaj do prawej
editing-an-error-occurred-while-opening = Wystąpił błąd przy otwieraniu { $val }
editing-attach-picturesaudiovideo = Dołącz obraz/audio/wideo
editing-bold-text = Pogrubienie
editing-cards = Karty
editing-center = Wycentrowanie
editing-change-color = Zmień kolor
editing-cloze-deletion = Luka (nowa karta)
editing-cloze-deletion-repeat = Luka (ta sama karta)
editing-couldnt-record-audio-have-you-installed = Nie można nagrać dźwięku. Czy masz zainstalowany program "lame"?
editing-customize-card-templates = Dostosuj szablony kart
editing-customize-fields = Dostosuj pola
editing-cut = Wytnij
editing-double-click-image = podwójne kliknięcie grafiki
editing-double-click-to-expand = podwójne kliknięcie rozwija
editing-double-click-to-collapse = podwójne kliknięcie zwija
editing-edit-current = Edytuj aktualną
editing-edit-html = Edytuj HTML
editing-fields = Pola
editing-float-left = Opływanie z lewej
editing-float-right = Opływanie z prawej
editing-float-none = Bez opływania
editing-indent = Zwiększ wcięcie
editing-italic-text = Pochylenie
editing-jump-to-tags-with-ctrlandshiftandt = Przeskocz do etykiet z Ctrl+Shift+T
editing-justify = Wyjustowanie
editing-latex = LaTeX
editing-latex-equation = Równanie LaTeX
editing-latex-math-env = Środowisko matematyczne LaTeX
editing-mathjax-block = Blok MathJax
editing-mathjax-chemistry = Chemia MathJax
editing-mathjax-inline = Liniowy MathJax
editing-media = Pliki
editing-ordered-list = Lista uporządkowana
editing-outdent = Zmniejsz wcięcie
editing-paste = Wklej
editing-record-audio = Nagraj dźwięk
editing-remove-formatting = Usuń formatowanie
editing-restore-original-size = Przywróć oryginalny rozmiar
editing-select-remove-formatting = Wybierz formatowanie do usunięcia
editing-show-duplicates = Pokaż duplikaty
editing-subscript = Indeks dolny
editing-superscript = indeks górny
editing-tags = Etykiety
editing-tags-add = Dodaj etykietę
editing-tags-copy = Kopiuj etykiety
editing-tags-remove = Usuń etykiety
editing-tags-select-all = Zaznacz wszystkie etykiety
editing-text-color = Kolor tekstu
editing-text-highlight-color = Kolor zaznaczenia tekstu
editing-to-make-a-cloze-deletion-on = Aby wprowadzić wypełnianie luk do istniejącej notatki, musisz zmienić jej typ na lukę poprzez Notatki>Zmień typ notatki
editing-toggle-html-editor = Przełącz edytor HTML
editing-toggle-visual-editor = Przełącz edytor wizualny
editing-toggle-sticky = Przełącz przyklejenie
editing-expand-field = Rozwiń pole
editing-collapse-field = Zwiń pole
editing-underline-text = Podkreślenie
editing-unordered-list = Lista nieuporządkowana
editing-warning-cloze-deletions-will-not-work = Uwaga: wypełnianie luk nie będzie działać, jeśli nie ustawisz typu na górze na Luka.
editing-mathjax-preview = Podgląd kodu MathJax
editing-shrink-images = Zmniejsz obrazy
editing-close-html-tags = Automatycznie domykaj znaczniki HTML

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Edytor HTML
