actions-add = Dodaj
actions-cancel = Otkaži
actions-choose = Odaberi
actions-close = Zatvori
actions-copy = Kopiraj
actions-decks = Špilovi
actions-delete = Obriši
actions-export = Izvezi
actions-help = Pomoć
actions-import = Uvezi
actions-name = Naziv:
actions-new = Novo
actions-new-name = Novi naziv:
actions-options = Postavke
actions-options-for = Postavke za { $val }
actions-rebuild = Ponovno izgradi
actions-rename = Preimenuj
actions-rename-deck = Preimenuj špil
actions-replay-audio = Ponovno reproduciraj zvuk
actions-reposition = Premjesti
actions-search = Pretraživanje
actions-shortcut-key = Kratica: { $val }
actions-suspend-card = Suspendiraj karticu
