importing-failed = Uvoz neuspješan.
importing-failed-debug-info = Uvoz nije uspio. Informacije za ispravljanje grešaka:
importing-allow-html-in-fields = Dozvoli HTML u poljima
importing-by-default-anki-will-detect-the = Anki će standardno otkriti znak između polja, kao što su tabulator, zarez itd. Ako Anki pogrešno prepozna znak, možete ga unijeti ovdje. Upotrijebite \t za tabulator.
importing-change = Promijeni
importing-colon = Dvotočka
importing-comma = Zarez
importing-field-mapping = Preslikavanje polja
importing-field-of-file-is = Polje <b>{ $val }</b> datoteke je:
importing-fields-separated-by = Polja su odvojena sa: { $val }
importing-ignore-lines-where-first-field-matches = Ignoriraj linije gdje se prvo polje podudara sa postojećom bilješkom
importing-ignored = <ignorirano>
importing-import-even-if-existing-note-has = Uvezi iako postojeća bilješka ima isto prvo polje
importing-import-options = Opcije uvoza
importing-importing-complete = Uvoz završen.
importing-map-to = Preslikaj u { $val }
importing-map-to-tags = Preslikaj u oznake
importing-mapped-to = preslikano u <b>{ $val }</b>
importing-mapped-to-tags = Preslikano u <b>Tags</b>
importing-semicolon = Točka-zarez
importing-this-will-delete-your-existing-collection = Ovo će obrisati vaš postojeći komplet i zamijeniti ga sa podacima u datoteci koju uvozite. Jeste li sigurni?
importing-unknown-file-format = Nepoznat format datoteke.
importing-update-existing-notes-when-first-field = Ažuriraj postojeće bilješke kada se prvo polje podudara
