notetypes-front-field = Prednja strana
notetypes-back-field = Poleđina
notetypes-add = Dodaj: { $val }
notetypes-add-note-type = Dodaj vrstu bilješke
notetypes-cards = Kartice...
notetypes-clone = Kloniraj: { $val }
notetypes-delete-this-note-type-and-all = Obrisati ovaj tip bilješke i sve pripadajuće karte?
notetypes-delete-this-unused-note-type = Obrisati ovaj nekorišteni tip bilješke?
notetypes-fields = Polja...
notetypes-footer = Podnožje
notetypes-header = Zaglavlje
notetypes-note-types = Vrste bilješki
notetypes-options = Postavke...
notetypes-please-add-another-note-type-first = Najprije dodajte novu vrstu bilješke.
notetypes-type = Vrsta
