sync-wrong-pass = AnkiWeb ID ili lozinka su bili pogrešni; pokušajte ponovno.
sync-download-from-ankiweb = Preuzmi sa AnkiWeb-a
sync-upload-to-ankiweb = Pošalji na AnkiWeb
sync-cancel-button = Otkaži
sync-downloading-from-ankiweb = Preuzimanje s AnkiWeb-a...
sync-uploading-to-ankiweb = Šaljem na AnkiWeb...
sync-syncing = Sinkronizacija...
sync-checking = Provjera u tijeku...
sync-password-label = Lozinka:
sync-account-required =
    <h1>Potreban je račun</h1>
    Za sinkronizaciju vaše kolekcije treba vam besplatan račun.  <a href="{ $link }">Registrirajte</a> račun, a zatim dolje unesite svoje podatke.
sync-connecting = Povezivanje…
