qt-misc-addons = Tillägg
qt-misc-all-cards-notes-and-media-for = Alla kort, noter och media för denna profil kommer att tas bort. Är du säker?
qt-misc-anki-updatedanki-has-been-released = <h1>Ny version av Anki</h1>Anki { $val } har släppts.<br><br>
qt-misc-automatic-syncing-and-backups-have-been = Automatisk synkning och säkerhetskopiering har inaktiverats under återställning. För att aktivera dem igen, stäng profilen eller starta om Anki.
qt-misc-backing-up = Säkerhetskopierar...
qt-misc-browse = Bläddra
qt-misc-change-note-type-ctrlandn = Ändra Nottyp (Ctrl+N)
qt-misc-check-the-files-in-the-media = Kontrollera filerna i mediebiblioteket
qt-misc-choose-deck = Välj Kortlek
qt-misc-choose-note-type = Välj Nottyp
qt-misc-closing = Stänger...
qt-misc-configure-interface-language-and-options = Anpassa gränssnittets språk och andra alternativ
qt-misc-copy-to-clipboard = Kopiera till Urklipp
qt-misc-create-filtered-deck = Skapa en filtrerad kortlek
qt-misc-debug-console = Felsökningskonsoll
qt-misc-deck-will-be-imported-when-a = Kortleken kommer importeras när en profil öppnas.
qt-misc-default = Standard
qt-misc-empty-cards = Tomma kort...
qt-misc-error-during-startup = Fel under uppstart: { $val }
qt-misc-filtered-deck = Filtrerad kortlek { $val }
qt-misc-ignore-this-update = Hoppa över denna uppdatering
qt-misc-in-order-to-ensure-your-collection = För att Anki ska kunna säkerställa att din samling fungerar korrekt när den flyttas mellan enheter, måste din dators interna klocka vara korrekt inställd. Den interna klockan kan gå fel även om ditt system visar rätt lokal tid.  Vänligen öppna tidsinställningar på din dator och kontrollera följande:  - fm/em (AM/PM) - Klockförskjutning - Dag, månad och år - Tidszon - Sommar- eller vintertid  Skillnad till korrekt tid: { $val }
qt-misc-loading = Laddar...
qt-misc-manage = Hantera
qt-misc-manage-note-types = Hantera nottyper
qt-misc-name-exists = Namnet existerar redan.
qt-misc-non-unicode-text = <icke-unicode-text>
qt-misc-optimizing = Optimerar...
qt-misc-please-connect-a-microphone-and-ensure = Vänligen koppla in en mikrofon och säkerställ att inga andra program använder ljudenheten.
qt-misc-please-ensure-a-profile-is-open = Säkerställ att en profil är öppen och att Anki inte är upptaget, och försök sedan igen.
qt-misc-please-select-1-card = (välj ett kort)
qt-misc-please-select-a-deck = Välj en kortlek.
qt-misc-please-use-fileimport-to-import-this = Använd Fil>Importera för att importera denna fil.
qt-misc-processing = Behandlar...
qt-misc-replace-your-collection-with-an-earlier = Ersätt din samling med en tidigare säkerhetskopia?
qt-misc-resume-now = Återuppta nu
qt-misc-revert-to-backup = Återställ till säkerhetskopia
qt-misc-reverted-to-state-prior-to = Återställde till status innan '{ $val }'.
qt-misc-shift-key-was-held-down-skipping = Shift-knappen hölls ned. Hoppar över automatisk synkronisering och laddning av tillägg.
qt-misc-shortcut-key-left-arrow = Kortkommando: Vänsterpil
qt-misc-shortcut-key-right-arrow-or-enter = Kortkommando: Högerpil eller Enter
qt-misc-stats = Statistik
qt-misc-study-deck = Studera kortlek...
qt-misc-sync = Synkronisera
qt-misc-target-deck-ctrlandd = Målkortlek (Ctrl+D)
qt-misc-the-following-character-can-not-be = Det följande tecknet kan inte användas: { $val }
qt-misc-the-requested-change-will-require-a = De ändringar du försöker göra kommer att kräva en fullständig uppladdning av databasen när du synkroniserar din samling nästa gång. Om du har gjort repetitioner eller har andra ändringar som väntar på andra enheter som inte har synkroniserats hit ännu, kommer de att gå förlorade. Vill du fortsätta?
qt-misc-there-must-be-at-least-one = Det måste finnas minst en profil.
qt-misc-this-file-exists-are-you-sure = Denna fil finns redan. Är du säker på att du vill skriva över den?
qt-misc-unable-to-move-existing-file-to = Kan inte flytta existerande fil till papperskorgen - prova att starta om din dator
qt-misc-undo = Ångra
qt-misc-undo2 = Ångra { $val }
qt-misc-waiting-for-editing-to-finish = Väntar på att redigeringen ska avslutas.
qt-misc-would-you-like-to-download-it = Vill du hämta hem den nu?
qt-misc-your-collection-file-appears-to-be = Filen med din samling verkar vara korrupt. Detta kan inträffa när filen kopieras eller flyttas medan Anki är öppet, eller när samlingen lagras på en nätverks- eller molnenhet. Om problemet kvarstår efter att ha startat om din dator, öppna en automatisk säkerhetskopia från profilskärmen.
qt-misc-your-firewall-or-antivirus-program-is = Din brandvägg eller ditt antivirusprogram förhindrar Anki från att ansluta till sig självt. Lägg till ett undantag för Anki.
qt-misc-second = { $count ->
    [one] { $count } sekund
   *[other] { $count } sekunder
  }
