actions-add = Engadir
actions-cancel = Cancelar
actions-choose = Escoller
actions-close = Pechar
actions-copy = Copiar
actions-custom-study = Estudo personalizado
actions-decks = Feixes
actions-delete = Eliminar
actions-export = Exportar
actions-filter = Filtrar
actions-help = Axuda
actions-import = Importar
actions-name = Nome:
actions-new = Novas
actions-new-name = Novo nome:
actions-options = Opcións
actions-options-for = Opcións para { $val }
actions-preview = Vista previa
actions-rebuild = Reconstruír
actions-rename = Cambiar o nome
actions-rename-deck = Cambiar o nome ao feixe
actions-replay-audio = Reproducir son
actions-reposition = Reposiciónar
actions-search = Busca
actions-shortcut-key = Tecla de atallo: { $val }
actions-suspend-card = Suspender tarxeta
