editing-add-media = Engadir ficheiros multimedia
editing-an-error-occurred-while-opening = produciuse un erro ao abrir { $val }
editing-cards = Tarxetas
editing-cut = Cortar
editing-edit-current = Editar a actual
editing-edit-html = Editar HTML
editing-fields = Campos
editing-html-editor = Editor de HTML
editing-jump-to-tags-with-ctrlandshiftandt = Ir ás etiquetas con Ctrl+Maiús+T
editing-latex-equation = Ecuación LaTeX
editing-latex-math-env = Entorno matemático LaTeX
editing-media = Recursos multimedia
editing-paste = Pegar
editing-show-duplicates = Amosar os duplicados
editing-tags = Etiquetas
editing-to-make-a-cloze-deletion-on = Para crear ocos nunha nota existente, primeiro debe cambiala a un tipo de nota de ocos, mediante Editar > Cambiar o tipo de nota.
editing-warning-cloze-deletions-will-not-work = Aviso: os ocos non funcionarán a non ser que cambie o tipo de nota a Ocos.
