notetypes-front-field = Anverso
notetypes-back-field = Reverso
notetypes-add-reverse-field = Engadir reverso
notetypes-text-field = Texto
notetypes-basic-name = Básica
notetypes-basic-reversed-name = Básica (e tarxeta invertida)
notetypes-basic-optional-reversed-name = Básica (tarxeta invertida opcional)
notetypes-cloze-name = Oco
notetypes-card-2-name = Tarxeta 2
notetypes-card-1-name = Tarxeta 1
notetypes-add = Engadir: { $val }
notetypes-add-note-type = Engadir un tipo de nota
notetypes-cards = Tarxetas...
notetypes-clone = Clonar: { $val }
notetypes-copy = copiar { $val }
notetypes-delete-this-note-type-and-all = Eliminar este tipo de nota e todas as súas tarxetas?
notetypes-delete-this-unused-note-type = Eliminar ese tipo de nota non usado?
notetypes-fields = Campos...
notetypes-footer = Rodapé
notetypes-header = Cabeceira
notetypes-note-types = Tipos de nota
notetypes-options = Opcións…
notetypes-please-add-another-note-type-first = Engada primeiro outro tipo de nota.
notetypes-type = Tipo
