preferences-automatically-sync-on-profile-openclose = Sincronizar automaticamente no perfil de apertura/peche
preferences-backups = Copias de seguranza
preferences-backups2 = copias de seguranza
preferences-backupsanki-will-create-a-backup-of = <b>Copias de seguranza</b><br>Anki creará unha copia de seguranza da súa colección cada vez que sexa pechado ou sincronizado.
preferences-basic = Básica
preferences-change-deck-depending-on-note-type = Cambiar o feixe en función do tipo de nota
preferences-hours-past-midnight = horas pasada a medianoite
preferences-interface-language = Idioma da interface:
preferences-keep = Conservar
preferences-learn-ahead-limit = Tempo límite para adiantar o estudo
preferences-mins = mins.
preferences-network = Rede
preferences-next-day-starts-at = O seguinte día comeza ás
preferences-note-media-is-not-backed-up = Nota: Non se fai copia de seguranza dos ficheiros multimedia. Cree periodicamente unha copia de seguranza do seu cartafol Anki para estar seguro.
preferences-on-next-sync-force-changes-in = Forzar cambios nunha dirección na próxima sincronización
preferences-paste-clipboard-images-as-png = Pegar imaxes do portapapeis como PNG
preferences-preferences = Preferencias
preferences-scheduling = Reprogramar
preferences-show-next-review-time-above-answer = Amosar o intervalo do próximo repaso enriba dos botóns de resposta
preferences-show-remaining-card-count-during-review = Amosar o número de tarxetas restantes durante o repaso
preferences-some-settings-will-take-effect-after = Algúns axustes terán efecto despois de reiniciar Anki.
preferences-synchronisation = <b>Sincronización</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sincronización</b><br> Actualmente non está activada; prema no botón de sincronización na pantalla principal para activala.
preferences-synchronize-audio-and-images-too = Sincronizar tamén o son e as imaxes
preferences-timebox-time-limit = Intervalos temporais de estudo
preferences-when-adding-default-to-current-deck = Ao engadir, facelo no feixe predeterminado
