actions-add = Дадаць
actions-all-selected = Усё выбранае
actions-any-selected = Любое з выбранага
actions-cancel = Скасаваць
actions-choose = Выбраць
actions-close = Закрыць
actions-copy = Скапіяваць
actions-create-copy = Стварыць копію
actions-custom-study = Дапасаванае навучанне
actions-decks = Калоды
actions-decrement-value = Паменшыць значэнне
actions-delete = Выдаліць
actions-export = Экспартаваць
actions-filter = Фільтраваць
actions-help = Даведка
actions-increment-value = Павялічыць значэнне
actions-import = Імпартаваць
actions-manage = Кіраваць...
actions-name = Назва:
actions-new = Новыя
actions-new-name = Новая назва:
actions-options = Параметры
actions-options-for = Параметры для { $val }
actions-preview = Перадпрагляд
actions-rebuild = Перасабраць
actions-rename = Перайменаваць
actions-rename-deck = Перайменаваць калоду
actions-rename-tag = Перайменаваць цэтлік
actions-rename-with-parents = Перайменаваць разам з бацькоўскімі
actions-remove-tag = Выдаліць цэтлік
actions-replay-audio = Паўтарыць аудыя
actions-reposition = Перамясціць
actions-save = Захаваць
actions-search = Пошук
actions-select = Выбраць
actions-shortcut-key = Клавіятурны скарот: { $val }
actions-suspend-card = Прыпыніць картку
actions-set-due-date = Задаць тэрмін
actions-answer-card = Адказ да карткі
actions-unbury-unsuspend = Вярнуць/Узнавіць
actions-add-deck = Дадаць калоду
actions-add-note = Дадаць нататку
actions-update-tag = Абнавіць цэтлік
actions-update-note = Абнавіць нататку
actions-update-card = Абнавіць картку
actions-update-deck = Абнавіць калоду
actions-forget-card = Забыць картку
actions-build-filtered-deck = Сабраць калоду
actions-add-notetype = Дадаць тып нататкі
actions-remove-notetype = Выдаліць тып нататкі
actions-update-notetype = Абнавіць тып нататкі
actions-update-config = Абнавіць канфігурацыю
actions-card-info = Звесткі аб картцы
actions-previous-card-info = Звесткі аб папярэдняй картцы
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = Гэта дзеянне зараз не падтрымліваецца на вашай сістэме.

## Flags

actions-flag-number = Сцяжок { $number }
actions-flag-red = Чырвоны
actions-flag-orange = Аранжавы
actions-flag-green = Зялёны
actions-flag-blue = Сіні
actions-flag-pink = Ружовы
actions-flag-turquoise = Бірузовы
actions-flag-purple = Фіялетавы
actions-set-flag = Задаць сцяжок
