decks-add-new-deck-ctrlandn = Дадаць новую калоду (Ctrl+N)
decks-build = Сабраць
decks-cards-selected-by = карткі выбраны паводле
decks-create-deck = Стварыць калоду
decks-custom-steps-in-minutes = Наладжвальныя крокі (у хвілінах)
decks-deck = Калода
decks-decreasing-intervals = Інтэрвалы з памяншэннем
decks-delete-deck = Выдаліць калоду
decks-enable-second-filter = Уключыць другі фільтр
decks-filter = Фільтр:
decks-filter-2 = Фільтр 2
decks-get-shared = Атрымаць абагуленыя
decks-import-file = Імпартаваць файл
decks-increasing-intervals = Інтэрвалы з павелічэннем
decks-latest-added-first = Спачатку апошнія дададзеныя
decks-limit-to = Абмежаваць да
decks-minutes = хвілін
decks-most-lapses = Найбольш недаглядаў
decks-new-deck-name = Новая назва калоды:
decks-no-deck = [няма калоды]
decks-oldest-seen-first = Спачатку найстарэйшыя
decks-order-added = У парадку дадавання
decks-order-due = Парадак паводле тэрміну
decks-please-select-something = Выберыце нешта.
decks-random = Выпадковы
decks-relative-overdueness = Адносная пратэрмінаванасць
decks-repeat-failed-cards-after = Паўтарыць няўдалыя каркі потым
decks-reschedule-cards-based-on-my-answers = Пераназначыць час картак на аснове маіх адказаў у гэтай калодзе.
decks-study = Вучыць
decks-study-deck = Вучыць калоду
decks-filtered-deck-search-empty = Няма картак, якія бы адпавядалі дадзенаму пошуку. Некаторыя карткі маглі быць выключаны, бо яны ў іншай фільтраванай калодзе або прыпынены.
decks-unmovable-cards = Паказваць усе выключаныя карткі
