editing-actual-size = Уключыць/выключыць фактычны памер
editing-add-media = Дадаць медыя
editing-align-left = Выраўнаваць па левым краі
editing-align-right = Выраўнаваць па правым краі
editing-an-error-occurred-while-opening = Пры адкрыцці { $val } узнікла памылка
editing-attach-picturesaudiovideo = Далучыць відарысы/аўдыя/відэа
editing-bold-text = Тоўсты тэкст
editing-cards = Карткі
editing-center = Па цэнтры
editing-change-color = Змяніць колер
editing-cloze-deletion = Запаўненне прабела
editing-couldnt-record-audio-have-you-installed = Не атрымалася запісаць аўдыя. Вы ўсталявалі «lame»?
editing-customize-card-templates = Дапасаваць шаблоны картак
editing-customize-fields = Дапасаваць палі
editing-cut = Выразаць
editing-edit-current = Рэдагаваць бягучую
editing-edit-html = Рэдагаваць HTML
editing-fields = Палі
editing-float-left = Абцяканне злева
editing-float-right = Абцяканне справа
editing-float-none = Без абцякання
editing-indent = Павялічыць водступ
editing-italic-text = Курсіўны тэкст
editing-jump-to-tags-with-ctrlandshiftandt = Перайсці да цэтлікаў праз Ctrl+Shift+T
editing-justify = Выраўнаваць па баках
editing-latex = LaTeX
editing-latex-equation = Ураўненне LaTeX
editing-latex-math-env = Мат. асяроддзе LaTeX
editing-mathjax-block = Блок MathJax
editing-mathjax-chemistry = MathJax хімія
editing-mathjax-inline = Убудаваны MathJax
editing-mathjax-placeholder = Націсніце { $accept } для прыняцця, { $newline } для новага радка.
editing-media = Медыя
editing-ordered-list = Упарадкаваны спіс
editing-outdent = Паменшыць водступ
editing-paste = Уставіць
editing-record-audio = Запісаць аўдыя
editing-remove-formatting = Выдаліць фармаціраванне
editing-restore-original-size = Аднавіць арыгінальны памер
editing-show-duplicates = Паказаць дублікаты
editing-subscript = Ніжні індэкс
editing-superscript = Верхні індэкс
editing-tags = Цэтлікі
editing-tags-add = Дадаць цэтлік
editing-tags-copy = Скапіяваць цэтлікі
editing-tags-remove = Выдаліць цэтлікі
editing-tags-select-all = Выбраць усе цэтлікі
editing-text-color = Колер тэксту
editing-text-highlight-color = Колер вылучэння тэксту
editing-to-make-a-cloze-deletion-on = Каб дадаць запаўненне прабела да існуючай нататкі, неабходна спачатку змяніць яе тып на «З прабеламі», праз «Нататкі > Змяніць тып нататкі»
editing-toggle-html-editor = Пераключыць рэдактар HTML
editing-toggle-visual-editor = Пераключыць візуальны рэдактар
editing-toggle-sticky = Пераключыць заліпанне
editing-expand-field = Разгарнуць поле
editing-collapse-field = Згарнуць поле
editing-underline-text = Падкрэслены тэкст
editing-unordered-list = Неўпарадкаваны спіс
editing-warning-cloze-deletions-will-not-work = Увага, запаўненні прабелаў не будуць працаваць,пакуль вы не пераключыце тып на «З прабеламі» уверсе.
editing-mathjax-preview = Перадпрагляд MathJax
editing-shrink-images = Паменшыць відарысы
editing-close-html-tags = Аўтаматычна закрываць тэгі HTML

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Рэдактак HTML
