actions-add = 추가
actions-all-selected = 선택된 전체
actions-any-selected = 선택된 아무거나
actions-cancel = 취소
actions-choose = 선택
actions-close = 닫기
actions-copy = 복사하기
actions-create-copy = 사본 만들기
actions-custom-study = 맞춤 스터디
actions-decks = 덱
actions-decrement-value = 값 감소
actions-delete = 삭제
actions-export = 내보내기
actions-filter = 필터
actions-help = 도움말
actions-increment-value = 값 증가
actions-import = 가져오기
actions-manage = 관리...
actions-name = 이름:
actions-new = 새 카드
actions-new-name = 새 이름:
actions-options = 옵션
actions-options-for = { $val }의 옵션
actions-preview = 미리 보기
actions-rebuild = 다시 모으기
actions-rename = 이름 변경
actions-rename-deck = 덱 이름 변경
actions-rename-tag = 태그 이름 변경
actions-rename-with-parents = 상위 항목과 함께 이름 변경하기
actions-remove-tag = 태그 삭제
actions-replay-audio = 오디오 재생
actions-reposition = 위치 변경
actions-save = 저장하기
actions-search = 찾기
actions-select = 선택
actions-shortcut-key = 단축키: { $val }
actions-suspend-card = 카드 일시중단
actions-set-due-date = 만기 날짜 설정
actions-answer-card = 카드 학습
actions-unbury-unsuspend = 미루기/일시중단 해제
actions-add-deck = 덱 추가
actions-add-note = 노트 추가
actions-update-tag = 태그 업데이트
actions-update-note = 노트 업데이트
actions-update-card = 카드 업데이트
actions-update-deck = 덱 업데이트
actions-forget-card = 초기화
actions-build-filtered-deck = 덱 만들기
actions-add-notetype = 노트 유형 추가
actions-remove-notetype = 노트 유형 삭제
actions-update-notetype = 노트 유형 업데이트
actions-update-config = 설정 업데이트
actions-card-info = 카드 정보
actions-previous-card-info = 이전 카드 정보
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = 귀하의 시스템에서 아직 지원하지 않는 동작입니다.

## Flags

actions-flag-number = 플래그 { $number }
actions-flag-red = 빨강
actions-flag-orange = 주황
actions-flag-green = 초록
actions-flag-blue = 파랑
actions-flag-pink = 분홍
actions-flag-turquoise = 청록
actions-flag-purple = 보라
actions-set-flag = 플래그 설정
