decks-add-new-deck-ctrlandn = 새로운 덱 추가 (Ctrl+N)
decks-build = 모으기
decks-cards-selected-by = 카드, 선택 기준
decks-create-deck = 덱 만들기
decks-custom-steps-in-minutes = 맞춤 단계(분)
decks-deck = 덱
decks-decreasing-intervals = 복습간격이 긴 것부터
decks-delete-deck = 덱 제거
decks-enable-second-filter = 두번째 필터 활성화
decks-filter = 필터:
decks-filter-2 = 필터 2
decks-get-shared = 공유 덱 다운로드
decks-import-file = 파일 가져오기
decks-increasing-intervals = 복습간격이 짧은 것부터
decks-latest-added-first = 나중에 추가한 것부터
decks-limit-to = 개수 제한
decks-minutes = 분
decks-most-lapses = 많이 틀린 순서대로
decks-new-deck-name = 새로운 덱 이름:
decks-no-deck = [덱 없음]
decks-oldest-seen-first = 공부한 지 오래된 것부터
decks-order-added = 추가한 순서대로
decks-order-due = 만기 순서대로
decks-please-select-something = 무엇이든 선택하세요.
decks-random = 랜덤
decks-relative-overdueness = 늦은 정도의 상대값
decks-repeat-failed-cards-after = 학습 실패한 카드를 다음에 반복하기
decks-reschedule-cards-based-on-my-answers = 덱에서의 답변을 기준으로 카드 일정 조정하기
decks-study = 공부
decks-study-deck = 공부할 덱
decks-filtered-deck-search-empty = 검색어와 일치하는 카드가 없습니다. 일부 카드는 필터링된 다른 덱에 있거나 일시중단되었기 때문에 제외되었을 수 있습니다.
decks-unmovable-cards = 제외된 카드 보기
