qt-accel-about = &കുറിച്ച് ...
qt-accel-browse-and-install = &ബ്രൗസ് ചെയ്ത് ഇൻസ്റ്റാൾ ചെയ്യുക ...
qt-accel-cards = &കാർഡുകൾ
qt-accel-check-database = &ഡാറ്റാബേസ് പരിശോധിക്കുക
qt-accel-check-media = &മീഡിയ പരിശോധിക്കുക
qt-accel-edit = &തിരുത്തുക
qt-accel-exit = പു&റത്ത്
qt-accel-export = &കയറ്റുമതി ചെയ്യുക ...
qt-accel-export-notes = &കുറിപ്പുകൾ എക്‌സ്‌പോർട്ടുചെയ്യുക...
qt-accel-file = &ഫയൽ
qt-accel-filter = ഫിൽ&റ്റർ
qt-accel-find = &കണ്ടെത്തുക
qt-accel-find-and-replace = കണ്ടെത്തി മാറ്റിസ്ഥാ&പിക്കുക
qt-accel-find-duplicates = &തനിപ്പകർപ്പുകൾ കണ്ടെത്തുക
qt-accel-go = &പോകൂ
qt-accel-guide = &വഴികാട്ടി ...
qt-accel-help = &സഹായം
qt-accel-import = &ഇറക്കുമതി ചെയ്യുക...
qt-accel-info = &വിവരം...
qt-accel-invert-selection = &തിരഞ്ഞെടുപ്പ് വിപരീതമാക്കുക
qt-accel-next-card = &അടുത്ത കാർഡ്
qt-accel-note = കു&റിപ്പ്
qt-accel-notes = &കുറിപ്പുകൾ
qt-accel-open-addons-folder = &ആഡ്-ഓണുകൾ ഫോൾഡർ തുറക്കുക ...
qt-accel-preferences = &മുൻഗണനകൾ
qt-accel-previous-card = &മുമ്പത്തെ കാർഡ്
qt-accel-select-all = &എല്ലാം തിരഞ്ഞെടുക്കുക
qt-accel-select-notes = &കുറിപ്പുകൾ തിരഞ്ഞെടുക്കുക
qt-accel-support-anki = Anki-യെ &പിന്തുണയ്ക്കുക ...
qt-accel-switch-profile = പ്രൊഫൈൽ &സ്വിച്ചുചെയ്യുക
qt-accel-tools = &ഉപകരണങ്ങൾ
qt-accel-undo = &പഴയപടിയാക്കുക
qt-accel-redo = &പുനര്‍നിര്‍വ്വഹിക്കുക
qt-accel-set-due-date = &നിശ്ചിത തീയതി സജ്ജമാക്കുക
qt-accel-forget = &മറക്കുക
