actions-add = Добавить
actions-all-selected = Все выбранные
actions-any-selected = Любое из выбранного
actions-cancel = Отменить
actions-choose = Выбрать
actions-close = Закрыть
actions-copy = Копировать
actions-create-copy = Сделать копию
actions-custom-study = Учить ещё
actions-decks = Колоды
actions-decrement-value = Вычитаемое
actions-delete = Удалить
actions-export = Экспортировать
actions-filter = Фильтр
actions-help = Справка
actions-increment-value = Прибавляемое
actions-import = Импортировать
actions-manage = Править...
actions-name = Имя:
actions-new = Новые
actions-new-name = Новое название:
actions-options = Параметры
actions-options-for = Параметры { $val }
actions-preview = Просмотреть
actions-rebuild = Пересобрать
actions-rename = Переименовать
actions-rename-deck = Переименовать колоду
actions-rename-tag = Переименовать метку
actions-rename-with-parents = Переименовать с материнскими
actions-remove-tag = Удалить метку
actions-replay-audio = Воспроизвести снова
actions-reposition = Переместить
actions-save = Сохранить
actions-search = Поиск
actions-select = Выбрать
actions-shortcut-key = Горячая клавиша: { $val }
actions-suspend-card = Исключить карточку
actions-set-due-date = Задать срок
actions-answer-card = Ответ
actions-unbury-unsuspend = Вернуть/Включить
actions-add-deck = Добавить колоду
actions-add-note = Добавить запись
actions-update-tag = Обновить метку
actions-update-note = Обновить запись
actions-update-card = Обновить карточку
actions-update-deck = Обновить колоду
actions-forget-card = Сбросить карточку
actions-build-filtered-deck = Создать колоду
actions-add-notetype = Добавить тип записи
actions-remove-notetype = Удалить тип записи
actions-update-notetype = Обновить тип записи
actions-update-config = Обновить конфигурацию
actions-card-info = Сведения о карточке
actions-previous-card-info = Сведения о предыдущей
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }
actions-currently-unsupported = Данное действие не поддерживается вашей системой на текущий момент.

## Flags

actions-flag-number = Флажок { $number }
actions-flag-red = Красный
actions-flag-orange = Оранжевый
actions-flag-green = Зеленый
actions-flag-blue = Синий
actions-flag-pink = Розовый
actions-flag-turquoise = Бирюзовый
actions-flag-purple = Фиолетовый
actions-set-flag = Установить флажок
