decks-add-new-deck-ctrlandn = Добавить новую колоду (Ctrl+N)
decks-build = Создать
decks-cards-selected-by = карт, выбранных
decks-create-deck = Создать колоду
decks-custom-steps-in-minutes = Заданные шаги (мин.)
decks-deck = Колода
decks-decreasing-intervals = Сокращающиеся интервалы
decks-delete-deck = Удалить колоду
decks-enable-second-filter = Активировать второй фильтр
decks-filter = Фильтр:
decks-filter-2 = Фильтр 2
decks-get-shared = Скачать колоду
decks-import-file = Импортировать
decks-increasing-intervals = Увеличивающиеся интервалы
decks-latest-added-first = Сначала последнее добавление
decks-limit-to = Ограничить до
decks-minutes = мин.
decks-most-lapses = Самые забываемые
decks-new-deck-name = Имя новой колоды:
decks-no-deck = [нет колоды]
decks-oldest-seen-first = Сначала просмотренные давно
decks-order-added = В порядке добавления
decks-order-due = По расписанию повторения
decks-please-select-something = Выберите вариант.
decks-random = В случайном порядке
decks-relative-overdueness = Относительная просроченность
decks-repeat-failed-cards-after = Повторить забытые карточки после
decks-reschedule-cards-based-on-my-answers = Перепланировать карточки на основе моих ответов в этой колоде
decks-study = Учить
decks-study-deck = Учить колоду
decks-filtered-deck-search-empty = Совпадений не найдено. Карточки могли быть исключены или находиться в другой отфильтрованной колоде.
decks-unmovable-cards = Показать все исключённые карточки
