editing-actual-size = Переключить размер
editing-add-media = Добавить медиафайл
editing-align-left = Выровнять по левому краю
editing-align-right = Выровнять по правому краю
editing-an-error-occurred-while-opening = При открытии { $val } возникла ошибка
editing-attach-picturesaudiovideo = Прикрепить изображение/аудиофайл/видеофайл
editing-bold-text = Жирный шрифт
editing-cards = Карточки
editing-center = Центр
editing-change-color = Изменить цвет
editing-cloze-deletion = Заполнить пропуск
editing-cloze-deletion-repeat = Задание с пропуском (та же карточка)
editing-couldnt-record-audio-have-you-installed = Не получается записать звук. У вас установлен "lame"?
editing-customize-card-templates = Настроить шаблоны карточек
editing-customize-fields = Настроить поля
editing-cut = Вырезать
editing-double-click-image = щёлкните дважды
editing-double-click-to-expand = (щёлкните дважды, чтобы увеличить)
editing-double-click-to-collapse = Дважды щелкните чтобы свернуть
editing-edit-current = Редактировать
editing-edit-html = Править HTML
editing-fields = Поля
editing-float-left = Слева
editing-float-right = Справа
editing-float-none = Выключить обтекание
editing-indent = Увеличить отступ
editing-italic-text = Курсив
editing-jump-to-tags-with-ctrlandshiftandt = Перейти к меткам (Ctrl+Shift+T)
editing-justify = Выровнять
editing-latex = LaTeX
editing-latex-equation = Формула LaTeX
editing-latex-math-env = Окружение LaTeX
editing-mathjax-block = MathJax с выключкой
editing-mathjax-chemistry = MathJax для химии
editing-mathjax-inline = MathJax в строке
editing-mathjax-placeholder = Нажмите { $accept } для подтверждения или { $newline } для новой строки
editing-media = Медиафайлы
editing-ordered-list = Упорядоченный список
editing-outdent = Сократить отступ
editing-paste = Вставить
editing-record-audio = Записать аудиофайл
editing-remove-formatting = Удалить форматирование
editing-restore-original-size = Восстановить размер
editing-select-remove-formatting = Выбрать форматирование для удаления
editing-show-duplicates = Показать повторы
editing-subscript = Подстрочный знак
editing-superscript = Надстрочный знак
editing-tags = Метки
editing-tags-add = Добавить метку
editing-tags-copy = Копировать метку
editing-tags-remove = Удалить метки
editing-tags-select-all = Выбрать все метки
editing-text-color = Цвет текста
editing-text-highlight-color = Цвет выделения текста
editing-to-make-a-cloze-deletion-on = Чтобы добавить заполнение пропусков к существующей записи, необходимо сначала изменить её тип на «Задание с пропусками», выбрав «Записи» — «Сменить тип записи».
editing-toggle-html-editor = HTML-редактор
editing-toggle-visual-editor = Визуальный редактор
editing-toggle-sticky = Сохранять значение
editing-expand-field = Развернуть поле
editing-collapse-field = Свернуть поле
editing-underline-text = Подчеркивание
editing-unordered-list = Неупорядоченный список
editing-warning-cloze-deletions-will-not-work = Внимание! Заполнение пропусков не будет работать, пока вы не измените тип карточки на «Пропуски».
editing-mathjax-preview = Предпросмотр MathJax
editing-shrink-images = Уменьшить изображения
editing-close-html-tags = Закрывать теги HTML

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Редактор HTML
