fields-add-field = Добавить поле
fields-delete-field-from = Удалить поле из { $val }?
fields-editing-font = Шрифт в редакторе
fields-field = Поле:
fields-field-name = Имя поля:
fields-description = Описание
fields-description-placeholder = Будет показано рядом с названием при редактировании
fields-fields-for = Поля для { $val }
fields-font = Шрифт:
fields-new-position-1 = Новая позиция (1…{ $val }):
fields-notes-require-at-least-one-field = В записи должно быть хотя бы одно поле.
fields-reverse-text-direction-rtl = Направление письма справа налево
fields-collapse-by-default = Сворачивать по умолчанию
fields-html-by-default = Использовать HTML по умолчанию
fields-size = Размер:
fields-sort-by-this-field-in-the = Сортировать список по этому полю
fields-that-field-name-is-already-used = Заданное имя уже используется
fields-name-first-letter-not-valid = Имя поля не должно начинаться с #, ^ или /.
fields-name-invalid-letter = Имя поля не должно содержать :, ",  { "{" } или { "}" }.
