preferences-automatically-sync-on-profile-openclose = Автоматически синхронизировать при смене профиля
preferences-backups = Резервные копии
preferences-change-deck-depending-on-note-type = Выбрать колоду по типу записи
preferences-changes-will-take-effect-when-you = Изменения вступят в силу при перезапуске Anki.
preferences-hours-past-midnight = ч. после полуночи
preferences-language = Язык
preferences-interrupt-current-audio-when-answering = Прерывать аудио при ответе
preferences-learn-ahead-limit = Лимит опережения
preferences-mins = мин.
preferences-network = Сеть
preferences-next-day-starts-at = Начало следующего дня
preferences-media-is-not-backed-up = Резервная копия медиафайлов не делается. Периодические делайте копию своих файлов.
preferences-on-next-sync-force-changes-in = При следующей синхронизации перезаписать в одном направлении
preferences-paste-clipboard-images-as-png = Вставлять изображения из буфера как PNG
preferences-paste-without-shift-key-strips-formatting = Вставка без клавиши Shift убирает форматирование
preferences-periodically-sync-media = Периодически синхронизировать медиаданные
preferences-please-restart-anki-to-complete-language = Перезагрузите Anki, чтобы переключить язык.
preferences-preferences = Настройки
preferences-scheduling = Расписание
preferences-show-learning-cards-with-larger-steps = Показывать изучаемые карточки с большими шагами до повторяемых
preferences-show-next-review-time-above-answer = Показывать время повторения над кнопками ответа
preferences-show-play-buttons-on-cards-with = Показывать кнопки управления на карточках с аудио
preferences-show-remaining-card-count = Показывать количество оставшихся
preferences-some-settings-will-take-effect-after = Некоторые параметры вступят в силу только после перезапуска Anki.
preferences-tab-synchronisation = Синхронизация
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Синхронизация</b><br> Выключена. Чтобы включить её, щёлкните кнопку в главном окне.
preferences-synchronize-audio-and-images-too = Синхронизировать аудио и изображения
preferences-timebox-time-limit = Лимит ограничения времени
preferences-user-interface-size = Размер интерфейса
preferences-when-adding-default-to-current-deck = Добавлять в текущую колоду
preferences-you-can-restore-backups-via-fileswitch = Вы можете восстановить резервную копию через «Файл» — «Сменить профиль».
preferences-legacy-timezone-handling = Устаревшая обработка часовых поясов (с ошибками, но требуется для AnkiDroid <= 2.14)
preferences-default-search-text = Текст поиска по умолчанию
preferences-default-search-text-example = например, 'deck:current ' для выбора текущей колоды
preferences-theme = Тема
preferences-theme-follow-system = Как в системе
preferences-theme-light = Светлая
preferences-theme-dark = Тёмная
preferences-v3-scheduler = Планировщик V3
preferences-ignore-accents-in-search = Игнорировать диакритические знаки при поиске (медленнее)
preferences-backup-explanation =
    Anki периодически создает резервную копию ваших коллекций при выходе. После двух дней,
    Anki начнет удалять некоторые из них для освобождения дискового пространства.
preferences-daily-backups = Оставлять резервных копий ежедневно:
preferences-weekly-backups = Оставлять резервных копий еженедельно:
preferences-monthly-backups = Оставлять резервных копий ежемесячно:
preferences-minutes-between-backups = Интервал между автоматическими копиями:
preferences-reduce-motion = Меньше анимации
preferences-reduce-motion-tooltip = Отключить анимацию и переходы в интерфейсе
preferences-custom-sync-url = Собственный сервер синхронизации
preferences-custom-sync-url-disclaimer = Для опытных пользователей — см. руководство
preferences-hide-top-bar-during-review = Скрывать верхнюю панель во время учёбы
preferences-hide-bottom-bar-during-review = Скрывать нижнюю панель во время учёбы
preferences-always = Всегда
preferences-full-screen-only = При полном экране
preferences-appearance = Внешний вид
preferences-general = Общие
preferences-style = Стиль
preferences-review = Учёба
preferences-distractions = Помехи
preferences-minimalist-mode = Минималистичный
preferences-editing = Редактирование
preferences-browsing = Список
preferences-default-deck = Колода по умолчанию
preferences-account = Учётная запись AnkiWeb
preferences-note = Записи
preferences-scheduler = Расписание
preferences-user-interface = Интерфейс
preferences-import-export = Импорт и экспорт
preferences-network-timeout = Ожидание сети

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = Основные
preferences-media = Медиа
