actions-add = Aggiungi
actions-all-selected = Tutte selezionate
actions-any-selected = Qualsiasi selezionata
actions-cancel = Annulla
actions-choose = Scegli
actions-close = Chiudi
actions-copy = Copia
actions-create-copy = Crea Copia
actions-custom-study = Studio personalizzato
actions-decks = Mazzi
actions-decrement-value = Diminuisci valore
actions-delete = Elimina
actions-export = Esporta
actions-filter = Filtro
actions-help = Aiuto
actions-increment-value = Incrementa valore
actions-import = Importa
actions-manage = Gestisci...
actions-name = Nome:
actions-new = Nuove
actions-new-name = Nuovo nome:
actions-options = Opzioni
actions-options-for = Opzioni per { $val }
actions-preview = Anteprima
actions-rebuild = Ricrea
actions-rename = Rinomina
actions-rename-deck = Rinomina il mazzo
actions-rename-tag = Rinomina etichetta
actions-rename-with-parents = Rinomina coi genitori
actions-remove-tag = Rimuovi etichetta
actions-replay-audio = Riproduci di nuovo l'audio
actions-reposition = Riposiziona
actions-save = Salva
actions-search = Cerca
actions-select = Seleziona
actions-shortcut-key = Tasto di scorciatoia: { $val }
actions-suspend-card = Sospendi la carta
actions-set-due-date = Imposta data di scadenza
actions-answer-card = Rispondi carta
actions-unbury-unsuspend = Disseppellisci/Annulla sospensione
actions-add-deck = Aggiungi mazzo
actions-add-note = Aggiungi nota
actions-update-tag = Aggiorna etichetta
actions-update-note = Aggiorna nota
actions-update-card = Aggiorna carta
actions-update-deck = Aggiorna mazzo
actions-forget-card = Dimentica carta
actions-build-filtered-deck = Crea mazzo
actions-add-notetype = Aggiungi tipo di nota
actions-remove-notetype = Rimuovi tipo di nota
actions-update-notetype = Aggiorna tipo di nota
actions-update-config = Aggiorna configurazione
actions-card-info = Info carta
actions-previous-card-info = Info Carta Precedente
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = Questa azione al momento non è supportata sul tuo sistema.

## Flags

actions-flag-number = Bandiera { $number }
actions-flag-red = Rossa
actions-flag-orange = Arancione
actions-flag-green = Verde
actions-flag-blue = Blu
actions-flag-pink = Rosa
actions-flag-turquoise = Turchese
actions-flag-purple = Viola
actions-set-flag = Imposta bandiera
