editing-actual-size = Attiva/disattiva dimensione effettiva
editing-add-media = Aggiungi media
editing-align-left = Allinea a sinistra
editing-align-right = Allinea a destra
editing-an-error-occurred-while-opening = Si è verificato un errore durante l'apertura di { $val }
editing-attach-picturesaudiovideo = Allega immagini/audio/video
editing-bold-text = Grassetto
editing-cards = Carte
editing-center = Centro
editing-change-color = Cambia colore
editing-cloze-deletion = Cancellazione cloze (Nuova carta)
editing-cloze-deletion-repeat = Cancellazione cloze (Stessa carta)
editing-couldnt-record-audio-have-you-installed = La registrazione audio non è stata possibile. Hai installato 'lame'?
editing-customize-card-templates = Personalizza i modelli delle carte
editing-customize-fields = Personalizza i campi
editing-cut = Taglia
editing-double-click-image = doppio click sull'immagine
editing-double-click-to-expand = doppio click per espandere
editing-double-click-to-collapse = doppio click per comprimere
editing-edit-current = Modifica corrente
editing-edit-html = Modifica HTML
editing-fields = Campi
editing-float-left = Fluttua a sinistra
editing-float-right = Fluttua a destra
editing-float-none = Non fluttuare
editing-indent = Aumenta l'indentazione
editing-italic-text = Corsivo
editing-jump-to-tags-with-ctrlandshiftandt = Salta a etichette con Ctrl+Shift+T
editing-justify = Giustificato
editing-latex = LaTeX
editing-latex-equation = Equazione LaTeX
editing-latex-math-env = Ambiente LaTeX math
editing-mathjax-block = Blocco MathJax
editing-mathjax-chemistry = MathJax chimica
editing-mathjax-inline = MathJax in linea
editing-mathjax-placeholder = Premi { $accept } per accettare, { $newline } per una nuova riga.
editing-media = File multimediale
editing-ordered-list = Lista ordinata
editing-outdent = Riduci indentazione
editing-paste = Incolla
editing-record-audio = Registra audio
editing-remove-formatting = Rimuovi formattazione
editing-restore-original-size = Ripristina dimensione originale
editing-select-remove-formatting = Seleziona formattazione da rimuovere
editing-show-duplicates = Mostra i duplicati
editing-subscript = Pedice
editing-superscript = Apice
editing-tags = Etichette
editing-tags-add = Aggiungi etichetta
editing-tags-copy = Copia etichette
editing-tags-remove = Rimuovi etichette
editing-tags-select-all = Seleziona tutte le etichette
editing-text-color = Colore del testo
editing-text-highlight-color = Colore di evidenziazione del testo
editing-to-make-a-cloze-deletion-on = Per inserire una cancellazione cloze in una nota esistente, devi prima cambiarla in una nota di tipo cloze, attraverso Modifica>Cambia tipo di nota
editing-toggle-html-editor = Attiva/disattiva l'editor HTML
editing-toggle-visual-editor = Attiva/disattiva editor visuale
editing-toggle-sticky = Attiva/disattiva adesività
editing-expand = Espandi
editing-collapse = Comprimi
editing-expand-field = Espandi campo
editing-collapse-field = Comprimi campo
editing-underline-text = Sottolinea testo
editing-unordered-list = Lista non ordinata
editing-warning-cloze-deletions-will-not-work = Attenzione, le cancellazioni cloze non funzioneranno fino a quando non cambierai in "Cloze" il tipo in alto.
editing-mathjax-preview = Anteprima MathJax
editing-shrink-images = Ridimensiona Immagini
editing-close-html-tags = Chiudi automaticamente i tag HTML

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Editor HTML
