profiles-anki-could-not-read-your-profile = Anki non ha potuto leggere i dati del tuo profilo. Le impostazioni non sono state riprese.
profiles-anki-could-not-rename-your-profile = Anki non ha potuto rinominare il profilo perché non è riuscito a rinominare la cartella del profilo sul disco. Assicurati di avere il permesso di scrittura in Documenti/Anki e che nessun altro programma stia accedendo alle cartelle del profilo, quindi riprova.
profiles-folder-already-exists = La cartella esiste già.
profiles-open = Apri
profiles-open-backup = Apri backup...
profiles-please-remove-the-folder-and = Rimuovi la cartella { $val } e riprova.
profiles-profile-corrupt = Profilo corrotto
profiles-profiles = Profili
profiles-quit = Esci
profiles-user-1 = Utente 1
profiles-confirm-lang-choice = Sei sicuro di voler mostrare l'interfaccia di Anki in { $lang }?
profiles-could-not-create-data-folder = Anki non ha potuto creare la sua cartella di dati. Per favore consulta la sezione "Posizione dei File" del manuale, e assicurati che la posizione non sia in sola lettura.
profiles-prefs-corrupt-title = Preferenze corrotte
profiles-prefs-file-is-corrupt = Il file prefs21.db di Anki era corrotto ed è stato ricreato. Se stavi usando profili multipli, per favore aggiungili di nuovo usando gli stessi nomi di prima per poter recuperare le tue carte.
profiles-profile-does-not-exist = Il profilo richiesto non esiste.
profiles-creating-backup = Creazione backup in corso...
profiles-backup-created = Creato backup.
profiles-backup-creation-failed = Creazione backup non riuscita: { $reason }
profiles-backup-unchanged = Nessuna modifica dall'ultimo backup.
