actions-add = जोडा
actions-cancel = रद्द करा
actions-choose = निवडा
actions-close = बंद करा
actions-copy = नक्कल
actions-decks = पत्त्यांचे गठ्ठे
actions-delete = काढून टाका
actions-export = निर्यात करा
actions-filter = गाळणी
actions-help = मदत
actions-import = आयात करा
actions-options = पर्याय
