actions-add = Aldoni
actions-blue-flag = Blua flago
actions-cancel = Nuligi
actions-choose = Elekti
actions-close = Fermi
actions-copy = Kopii
actions-custom-study = Propra lernado
actions-decks = Kartaroj
actions-delete = Forigi
actions-export = Elporti
actions-filter = Filtrilo
actions-green-flag = Verda flago
actions-help = Helpo
actions-import = Enporti
actions-manage = Administri...
actions-name = Nomo:
actions-new = Nova
actions-new-name = Nova nomo:
actions-options = Opcioj
actions-options-for = Opcioj por { $val }
actions-orange-flag = Oranĝkolora flago
actions-preview = Antaŭmontro
actions-rebuild = Rekunmeti
actions-red-flag = Ruĝa flago
actions-rename = Alinomi
actions-rename-deck = Alinomi kartaron
actions-replay-audio = Reludi sonon
actions-reposition = Repozicii
actions-save = Konservi
actions-search = Serĉi
actions-shortcut-key = Fulmoklavo: { $val }
actions-suspend-card = Daŭre kaŝi karton
