adding-add-shortcut-ctrlandenter = Aldoni (fulmoklavo: Ctrl+Enter)
adding-added = Aldonita
adding-close-and-lose-current-input = Ĉu fermi kaj perdi nunan enmetitaĵon?
adding-edit = Redakti "{ $val }"
adding-history = Antaŭaĵo
adding-note-deleted = (Noto estas forigita)
adding-shortcut = Fulmoklavo: { $val }
adding-the-first-field-is-empty = La unua kampo estas malplena.
adding-you-have-a-cloze-deletion-note = Vi elektis la nototipon truteksto, sed ne faris trutekstajn malplenojn. Daŭrigi?
