card-stats-added = Aldonita
card-stats-first-review = Unua ripeto
card-stats-latest-review = Plej lasta ripeto
card-stats-interval = Intertempo
card-stats-ease = Facileco
card-stats-review-count = Ripetoj
card-stats-lapse-count = Misrespondoj
card-stats-average-time = Mezuma tempo
card-stats-total-time = Suma tempo
card-stats-new-card-position = Pozicio
card-stats-card-template = Kartotipo
card-stats-note-type = Nototipo
card-stats-deck-name = Kartaro
card-stats-note-id = Noto-identigilo
card-stats-card-id = Karto-identigilo
card-stats-review-log-rating = Pritakso
card-stats-review-log-type = Tipo
card-stats-review-log-date = Dato
card-stats-review-log-time-taken = Tempo
card-stats-review-log-type-learn = Lerni
card-stats-review-log-type-review = ripeto
card-stats-review-log-type-relearn = Relerni
card-stats-review-log-type-filtered = Filtrita
card-stats-review-log-type-rescheduled = Replani
