custom-study-all-cards-in-random-order-dont = Ĉiuj kartoj en hazarda ordo (ne replani)
custom-study-all-review-cards-in-random-order = Ĉiuj ripetokartoj en hazarda ordo
custom-study-cards = kartoj
custom-study-cards-from-the-deck = kartoj de la kartaro
custom-study-choose-tags = Elekti etikedojn
custom-study-custom-study-session = Krei lernadan seancon
custom-study-due-cards-only = Nur lernendaj kartoj
custom-study-increase-todays-new-card-limit = Kreskigi hodiaŭan limigon de novaj kartoj
custom-study-increase-todays-new-card-limit-by = Kreskigi hodiaŭan limigon de novaj kartoj per
custom-study-increase-todays-review-card-limit = Kreskigi hodiaŭan limigon de ripetokartoj
custom-study-increase-todays-review-limit-by = Kreskigi hodiaŭan limigon de ripetokartoj per
custom-study-new-cards-in-deck-over-today = Novaj kartoj en la kartaro super la hodiaŭa limigo: { $val }
custom-study-new-cards-only = Nur novaj kartoj
custom-study-no-cards-matched-the-criteria-you = Neniuj kartoj kongruis kun la kriterioj, kiujn vi enigis.
custom-study-ok = Bone
custom-study-preview-new-cards = Antaŭmontri novajn kartojn
custom-study-preview-new-cards-added-in-the = Antaŭmontri novajn kartojn, kiuj estas aldonitaj en la lasta
custom-study-require-one-or-more-of-these = Nepri unu aŭ pli el ĉi tiuj etikedoj:
custom-study-review-ahead = Ripeti antaŭe
custom-study-review-ahead-by = Ripeti antaŭe al
custom-study-review-cards-forgotten-in-last = Ripeti kartojn, kiujn vi forgesis en la lasta(j)
custom-study-review-forgotten-cards = Ripeti forgesitajn kartojn
custom-study-reviews-due-in-deck-over-today = Lernendaj ripetoj en la kartaro super la hodiaŭa limigo: { $val }
custom-study-select = Elekti
custom-study-select-tags-to-exclude = Elektu etikedojn por ekskluzivi:
custom-study-selective-study = Selektiva lernado
custom-study-study-by-card-state-or-tag = Lerni laŭ kartostato aŭ etikedo
