editing-add-media = Aldoni aŭdovidaĵon
editing-an-error-occurred-while-opening = Okazis eraro dum malfermo de { $val }
editing-attach-picturesaudiovideo-f3 = Aldoni bildojn/sonojn/videojn (F3)
editing-bold-text-ctrlandb = Grasa teksto (Ctrl+B)
editing-cards = Kartoj
editing-change-colour-f8 = Ŝanĝi koloron (F8)
editing-cloze-deletion-ctrlandshiftandc = Truteksta malpleno (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = La registro de sono ne estas ebla. Ĉu vi instalis 'lame'?
editing-customize-card-templates-ctrlandl = Akomodi la kartoŝablonon (Ctrl+L)
editing-customize-fields = Akomodi kampojn
editing-cut = Eltondi
editing-edit-current = Redakti aktualan
editing-edit-html = Redakti HTML
editing-fields = Kampoj
editing-html-editor = HTML-redaktilo
editing-italic-text-ctrlandi = Kursiva teksto (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = Salti al etikedoj per Ctrl+Shift+T
editing-latex-equation = LaTeX-formulo
editing-latex-math-env = LaTeX matematika ĉirkaŭaĵo
editing-mathjax-block = MathJax bloko
editing-mathjax-chemistry = MathJax ĥemio
editing-mathjax-inline = Enlinia MathJax-Elemento
editing-media = Aŭdovidaĵo
editing-paste = Alglui
editing-record-audio-f5 = Registri sonon (F5)
editing-remove-formatting-ctrlandr = Forigi aranĝon (Ctrl+R)
editing-set-foreground-colour-f7 = Difini la koloron de la malfono (F7)
editing-show-duplicates = Montri duoblaĵojn
editing-subscript-ctrland = Suba indico (Ctrl+=)
editing-superscript-ctrlandand = Supra indico (Ctrl++)
editing-tags = Etikedoj
editing-to-make-a-cloze-deletion-on = Por krei trutekston ĉe ekzistanta noto, unuafoje vi devas ŝanĝi ĝin al truteksto-tipo, ĉe Redakti > Ŝanĝi nototipon.
editing-underline-text-ctrlandu = Substreki (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = Averto! Trutekstaj malplenoj ne funkcios, ĝis vi supre elektos la nototipon Truteksto.
