notetypes-front-field = Antaŭo
notetypes-back-field = Reen
notetypes-add-reverse-field = Aldoni malan direkton
notetypes-text-field = Teksto
notetypes-basic-name = Baza
notetypes-basic-reversed-name = Baza (en ambaŭ direktoj)
notetypes-basic-optional-reversed-name = Baza (en unu aŭ ambaŭ direktoj)
notetypes-cloze-name = Truteksto
notetypes-basic-type-answer-name = Baza (entajpi la respondon)
notetypes-card-2-name = 2-a karto
notetypes-card-1-name = 1-a karto
notetypes-add = Aldoni: { $val }
notetypes-add-note-type = Aldoni nototipon
notetypes-cards = Kartoj...
notetypes-clone = Kloni: { $val }
notetypes-copy = { $val } kopio
notetypes-create-scalable-images-with-dvisvgm = Krei skaleblan bildon per dvisvgm
notetypes-delete-this-note-type-and-all = Ĉu forigi ĉi tiun nototipon kaj ĉiujn ĝiajn kartojn?
notetypes-delete-this-unused-note-type = Ĉu forigi ĉi tiun neuzatan nototipon?
notetypes-fields = Kampoj...
notetypes-footer = Paĝopiedo
notetypes-header = Ĉapo
notetypes-note-types = Nototipoj
notetypes-options = Opcioj...
notetypes-please-add-another-note-type-first = Bonvolu aldoni alian nototipon antaŭe.
notetypes-type = Tipo
