actions-add = Ekle
actions-cancel = İptal
actions-choose = Seç
actions-close = Kapat
actions-copy = Kopyala
actions-create-copy = Kopyasını Oluştur
actions-custom-study = Özel Çalışma
actions-decks = Desteler
actions-delete = Sil
actions-export = Dışarıya Aktar
actions-filter = Filtre
actions-help = Yardım
actions-import = İçeri Aktar
actions-name = Ad:
actions-new = Yeni
actions-new-name = Yeni ad:
actions-options = Seçenekler
actions-options-for = { $val } için seçenekler
actions-preview = Önizleme
actions-rebuild = Yeniden oluştur
actions-rename = Yeniden Adlandır
actions-rename-deck = Desteyi Yeniden Adlandır
actions-rename-tag = Etiketi Yeniden Adlandır
actions-rename-with-parents = Üstlerle Yeniden Adlandır
actions-remove-tag = Etiketi Kaldır
actions-replay-audio = Sesi Tekrarla
actions-reposition = Yeniden Konumlandır
actions-save = Kaydet
actions-search = Ara
actions-select = Seç
actions-shortcut-key = Kısayol tuşu: { $val }
actions-suspend-card = Kartı Askıya Al
actions-set-due-date = Son Tarihi Ayarla
actions-unbury-unsuspend = Gizlemeyi/Askıya Almayı Geri Al
actions-add-deck = Deste Ekle
actions-add-note = Not Ekle
actions-update-tag = Etiketi Güncelle
actions-update-note = Notu Güncelle
actions-update-card = Kartı Güncelle
actions-update-deck = Desteyi Güncelle
actions-forget-card = Kartı Unut
actions-card-info = Kart Bilgisi

## Flags

actions-flag-number = { $number } Bayrak
actions-flag-red = Kırmızı
actions-flag-orange = Turuncu
actions-flag-green = Yeşil
actions-flag-blue = Mavi
actions-flag-pink = Pembe
actions-flag-turquoise = Turkuaz
actions-flag-purple = Mor
actions-set-flag = Bayrakla İşaretle
