decks-add-new-deck-ctrlandn = Yeni Deste Ekle (Ctrl+N)
decks-build = Yapılandır
decks-cards-selected-by = tarafından seçilen kartlar
decks-create-deck = Deste Oluştur
decks-custom-steps-in-minutes = Özel adımlar (dakikada)
decks-deck = Deste
decks-decreasing-intervals = Aralığı azaltma
decks-delete-deck = Desteyi kaldır
decks-enable-second-filter = İkinci filtreyi etkinleştir
decks-filter = Filtre:
decks-filter-2 = Filtre 2
decks-get-shared = Deste Bul
decks-import-file = Dosyayı İçeri Aktar
decks-increasing-intervals = Süreyi artırma
decks-latest-added-first = Son eklenen ilk
decks-limit-to = Sınırla
decks-minutes = dakîka
decks-most-lapses = En yüksek sapmalar
decks-new-deck-name = Yeni deste adı:
decks-no-deck = [deste yok]
decks-oldest-seen-first = En eski görülen ilk
decks-order-added = Sıralama eklendi
decks-order-due = Sıralama sonu
decks-please-select-something = Lütfen bir şey seçin.
decks-random = Rastgele
decks-relative-overdueness = Görece vadesi geçmişlik
decks-reschedule-cards-based-on-my-answers = Bu destedeki cevaplarıma göre kartları yeniden planlama
decks-study = Çalış
decks-study-deck = Desteyi Çalış
decks-unmovable-cards = Hariç tutulan kartları göster
