preferences-automatically-sync-on-profile-openclose = Açma/kapama anında profili otomatik olarak senkronize et
preferences-backups = Yedekler
preferences-basic = Temel
preferences-change-deck-depending-on-note-type = Not tipine göre desteyi değiştir
preferences-changes-will-take-effect-when-you = Değişiklikler, Anki'yi yeniden başlattığınızda etkili olacaktır.
preferences-learn-ahead-limit = Önceden öğrenme sınırı
preferences-mins = dk
preferences-network = Ağ
preferences-next-day-starts-at = Bir sonraki gün başlar
preferences-on-next-sync-force-changes-in = Bir sonraki senkronizasyonda değişiklikleri tek yönlü yap
preferences-paste-clipboard-images-as-png = Pano resmini PNG olarak yapıştır
preferences-please-restart-anki-to-complete-language = Dil değişimin tamamlamak için lütfen Anki'yi yeniden başlat.
preferences-preferences = Tercihler
preferences-scheduling = Yeniden Planlama
preferences-show-next-review-time-above-answer = Yanıt düğmelerinin üstünde sonraki inceleme süresini göster
preferences-some-settings-will-take-effect-after = Bazı ayarlar Anki'yi yeniden başlattığınızdan sonra etkili olacaktır.
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Eşitleme</b><br> Henüz etkin değil. Ana pencerede eşitleme düğmesine tıklayarak etkinleştirin.
preferences-synchronize-audio-and-images-too = Ses ve resimleri de senkronize edin
preferences-timebox-time-limit = Zaman sınırı
preferences-v3-scheduler = V3 planlayıcı
preferences-scheduler = Planlayıcı
