profiles-anki-could-not-rename-your-profile = Anki, disk üzerindeki profil klasörünü yeniden adlandıramadığı için profilinizi yeniden adlandıramadı. Lütfen Documents / Anki'ye yazma izninizin olduğundan ve diğer hiçbir programın profil klasörünüze erişemediğinden emin olduktan sonra tekrar deneyin.
profiles-folder-already-exists = Klasör zaten mevcut.
profiles-open = Aç
profiles-open-backup = Yedek Aç...
profiles-please-remove-the-folder-and = Lütfen { $val } klasörünü kaldır ve tekrar dene.
profiles-profiles = Profiller
profiles-quit = Çık
profiles-user-1 = Kullanıcı 1
profiles-creating-backup = Yedek Oluşturuluyor...
