actions-add = Додати
actions-all-selected = Усі вибрані
actions-cancel = Скасувати
actions-choose = Вибрати
actions-close = Закрити
actions-copy = Копіювати
actions-create-copy = Створити копію
actions-custom-study = Додаткове навчання
actions-decks = Колоди
actions-decrement-value = Зменшити значення
actions-delete = Видалити
actions-export = Експорт колоди в інший формат
actions-filter = Фільтр
actions-help = Допомога
actions-increment-value = Збільшити значення
actions-import = Імпорт
actions-manage = Керування…
actions-name = Назва:
actions-new = Нові
actions-new-name = Нова назва:
actions-options = Опції
actions-options-for = Налаштування для { $val }
actions-preview = Попередній  вигляд
actions-rebuild = Перебудувати
actions-rename = Перейменувати
actions-rename-deck = Перейменувати колоду
actions-rename-tag = Перейменувати мітку
actions-remove-tag = Прибрати мітку
actions-replay-audio = Прослухати ще раз
actions-reposition = Змінити розташування
actions-save = Зберегти
actions-search = Пошук
actions-select = Вибрати
actions-shortcut-key = Гаряча клавіша: { $val }
actions-suspend-card = Призупинити картку
actions-add-deck = Додати колоду
actions-add-notetype = Додати тип нотатки
actions-remove-notetype = Видалити тип нотатки
actions-update-notetype = Оновити тип нотатки

## Flags

actions-flag-number = { $number } прапорець
actions-flag-red = Червоний
actions-flag-orange = Помаранчевий
actions-flag-green = Зелений
actions-flag-blue = Синій
actions-flag-pink = Рожевий
actions-flag-turquoise = Бірюзовий
actions-flag-purple = Фіолетовий
actions-set-flag = Встановити прапорець
