fields-add-field = Додати поле
fields-delete-field-from = Видалити поле з { $val }?
fields-editing-font = Шрифт режиму редагування
fields-field = Поле:
fields-field-name = Назва поля:
fields-fields-for = Поля для { $val }
fields-font = Шрифт:
fields-new-position-1 = Нова позиція (1...{ $val }):
fields-notes-require-at-least-one-field = У нотатках необхідно мінімум одне поле.
fields-remember-last-input-when-adding = Запам'ятовувати останні внесені дані
fields-reverse-text-direction-rtl = Зворотній напрямок тексту (RTL)
fields-size = Розмір:
fields-sort-by-this-field-in-the = Сортувати по цьому полю у навігаторі
fields-that-field-name-is-already-used = Назва поля вже використовується.
fields-name-first-letter-not-valid = Назва поля не може починатися на #, ^ чи /.
fields-name-invalid-letter = Назва поля не може містити :, ", { "{" } чи { "}" }.
