preferences-automatically-sync-on-profile-openclose = Автоматична синхронізація при відкритті/закритті профілю
preferences-backups = Резервні копії
preferences-basic = Базова
preferences-change-deck-depending-on-note-type = Змінити колоду в залежності від типу нотатки
preferences-changes-will-take-effect-when-you = Зміни застосуються коли Ви перезавантажинти Anki.
preferences-hours-past-midnight = год
preferences-language = Мова
preferences-interrupt-current-audio-when-answering = Зупиняти відтворення звуку після відповіді
preferences-learn-ahead-limit = Обмеження для вивчення наперед на
preferences-mins = хв
preferences-network = Синхронізація
preferences-next-day-starts-at = Початок доби о
preferences-media-is-not-backed-up = Медіа-файли не включено до резервної копії. Для певності періодично робіть резервну копію вашої теки з файлами Anki самостійно.
preferences-on-next-sync-force-changes-in = Повна примусова одностороння синхронізація при наступному запуску
preferences-paste-clipboard-images-as-png = Вставити зображення із буфера обміну у форматі PNG
preferences-paste-without-shift-key-strips-formatting = Вставлення без shift прибирає форматування
preferences-periodically-sync-media = Періодично синхронізувати медіа
preferences-please-restart-anki-to-complete-language = Перезапустіть Anki для завершення зміни мови.
preferences-preferences = Налаштування
preferences-scheduling = Змінити розклад
preferences-show-learning-cards-with-larger-steps = Показувати вивчанні картки з більшим кроком раніше за повторюванні
preferences-show-next-review-time-above-answer = Показувати час наступного повторення над кнопками відповіді
preferences-show-play-buttons-on-cards-with = Показати кнопку «Програти» на картках із звуком
preferences-some-settings-will-take-effect-after = Деякі налаштування вступлять в силу лише після перезапуску Anki.
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Синхронізацію</b><br> Зараз вимкнено; щоб її увімкнути, натисніть кнопку синхронізації в головному вікні.
preferences-synchronize-audio-and-images-too = Синхронізувати також медіа-файли
preferences-timebox-time-limit = Період лічильника переглядів
preferences-user-interface-size = Розмір інтерфейсу
preferences-when-adding-default-to-current-deck = Додавати у поточну колоду за замовчуванням
preferences-you-can-restore-backups-via-fileswitch = Ви можете відновити резервні копії: Файл > змінити профіль.
preferences-default-search-text = Текст пошуку за замовченням
preferences-default-search-text-example = Наприклад: 'deck:current '
preferences-theme = Тема
preferences-theme-light = Світла
preferences-theme-dark = Темна
preferences-v3-scheduler = V3 планувальник
preferences-ignore-accents-in-search = Не зважати на діакрітичні знаки (повільніше)
preferences-backup-explanation =
    Anki періодично робить резервні копії колекції. Після 2 днів, 
    Anki почне видаляти деякі з них для вивільненя простору.
preferences-daily-backups = Залишати резервні копіїї щодня:
preferences-weekly-backups = Залишати резервні копіїї щотижня:
preferences-monthly-backups = Залишати резервні копіїї щомісяця:
preferences-minutes-between-backups = Хвилин між автоматичним резервним копіюванням:
preferences-always = Завжди
preferences-account = Обліковий запис AnkiWeb
preferences-media = Медіа-файли
preferences-note = Нотатка
preferences-scheduler = Планувальник
preferences-user-interface = Інтерфейс користувача
preferences-import-export = Імпорт/Експорт
