actions-add = Adicionar
actions-all-selected = Todos selecionados
actions-any-selected = Qualquer selecionado
actions-cancel = Cancelar
actions-choose = Escolher
actions-close = Fechar
actions-copy = Copiar
actions-create-copy = Criar Cópia
actions-custom-study = Estudo Personalizado
actions-decks = Baralhos
actions-decrement-value = Diminua valor
actions-delete = Excluir
actions-export = Exportar
actions-filter = Filtro
actions-help = Ajuda
actions-increment-value = Aumente valor
actions-import = Importar
actions-manage = Gerenciar...
actions-name = Nome:
actions-new = Novos
actions-new-name = Novo nome:
actions-options = Opções
actions-options-for = Opções para { $val }
actions-preview = Pré-visualização
actions-rebuild = Recriar
actions-rename = Renomear
actions-rename-deck = Renomear Baralho
actions-rename-tag = Renomear Etiqueta
actions-rename-with-parents = Renomear com Parentes
actions-remove-tag = Remover Etiqueta
actions-replay-audio = Repetir Áudio
actions-reposition = Reposicionar
actions-save = Salvar
actions-search = Procurar
actions-select = Selecionar
actions-shortcut-key = Tecla de Atalho: { $val }
actions-suspend-card = Suspender Cartão
actions-set-due-date = Definir Data de Revisão
actions-answer-card = Responder Cartão
actions-unbury-unsuspend = Remover Ocultação/Suspensão
actions-add-deck = Adicionar Baralho
actions-add-note = Adicionar Nota
actions-update-tag = Atualizar Etiqueta
actions-update-note = Atualizar Nota
actions-update-card = Atualizar Cartão
actions-update-deck = Atualizar baralho
actions-forget-card = Esquecer Cartão
actions-build-filtered-deck = Criar Baralho
actions-add-notetype = Adicionar Tipo de Notaﾠ
actions-remove-notetype = Remover Tipo de Nota
actions-update-notetype = Atualizar Tipo de Notaﾠ
actions-update-config = Atualizar Configurações
actions-card-info = Informação do Cartão
actions-previous-card-info = Informação do Cartão Anterior
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = Esta ação atualmente não é suportada em seu sistema.

## Flags

actions-flag-number = Emblema { $number }
actions-flag-red = Vermelho
actions-flag-orange = Laranja
actions-flag-green = Verde
actions-flag-blue = Azul
actions-flag-pink = Rosa
actions-flag-turquoise = Turquesa
actions-flag-purple = Roxo
actions-set-flag = Definir Emblema
