preferences-automatically-sync-on-profile-openclose = Sincronizar automaticamente ao abrir/fechar perfil de usuário
preferences-backups = Cópias de segurança
preferences-change-deck-depending-on-note-type = Mudar baralho dependendo do tipo de nota
preferences-changes-will-take-effect-when-you = As alterações serão aplicadas depois que você reiniciar o Anki.
preferences-hours-past-midnight = horas além da meia-noite
preferences-language = Idioma
preferences-interrupt-current-audio-when-answering = Interromper o áudio atual ao responder
preferences-learn-ahead-limit = Aprender além do limite
preferences-mins = minutos
preferences-network = Rede
preferences-next-day-starts-at = Novo dia começa às
preferences-media-is-not-backed-up = Imagens ou mídias não são copiadas. Por favor, faça uma cópia periódica da sua pasta do Anki para sua segurança.
preferences-on-next-sync-force-changes-in = Na próxima sincronização, obrigar mudanças em uma direção.
preferences-paste-clipboard-images-as-png = Colar imagens da área de transferência como PNG
preferences-paste-without-shift-key-strips-formatting = Colar sem o botão shift desfaz a formatação
preferences-periodically-sync-media = Sincronizar mídia periodicamente
preferences-please-restart-anki-to-complete-language = Por favor, reinicie o Anki para completar a mudação de idioma.
preferences-preferences = Preferências
preferences-scheduling = Agendamento
preferences-show-learning-cards-with-larger-steps = Exibir os cartões de aprendizagem com intervalos maiores antes de efetuar novas revisões
preferences-show-next-review-time-above-answer = Mostrar tempo da próxima revisão acima dos botões de resposta
preferences-show-play-buttons-on-cards-with = Mostrar botões de reprodução nos cartões com áudio
preferences-show-remaining-card-count = Mostrar a contagem de cartas restantes
preferences-some-settings-will-take-effect-after = Algumas configurações só surtirão efeito quando você reiniciar o Anki
preferences-tab-synchronisation = Sincronização
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sincronização</b><br> Desabilitado; clique no botão de sincronização na janela principal para ativá-la.
preferences-synchronize-audio-and-images-too = Sincronizar áudios e imagens também
preferences-timebox-time-limit = Tempo limite
preferences-user-interface-size = Tamanho da interface do usuário
preferences-when-adding-default-to-current-deck = Ao criar, o padrão é o baralho atual
preferences-you-can-restore-backups-via-fileswitch = Você pode restaurar as cópias de seguranças em Arquivo>Mudar perfil.
preferences-legacy-timezone-handling = Gerenciamento de fuso horário antigo (com erros, mas necessário para o AnkiDroid <= 2.14)
preferences-default-search-text = Termo de pesquisa padrão
preferences-default-search-text-example = ex. 'deck: current'
preferences-theme = Tema
preferences-theme-follow-system = Conforme o Sistema
preferences-theme-light = Claro
preferences-theme-dark = Escuro
preferences-v3-scheduler = Agendador V3
preferences-ignore-accents-in-search = Ignorar acentos na pesquisa (mais lento)
preferences-backup-explanation =
    Anki periodicamente faz backup de sua coleção. Depois que os backups tiverem mais de 2 dias,
    O Anki começará a remover alguns deles para liberar espaço em disco.
preferences-daily-backups = Backups diários para manter:
preferences-weekly-backups = Backups semanais para manter:
preferences-monthly-backups = Backups mensais para manter:
preferences-minutes-between-backups = Minutos antes dos backups automáticos:
preferences-reduce-motion = Reduzir animações
preferences-reduce-motion-tooltip = Desative várias animações e transições da interface do usuário
preferences-custom-sync-url-disclaimer = Para usuários avançados - por favor veja o manual
preferences-hide-top-bar-during-review = Ocultar a barra acima durante o review
preferences-hide-bottom-bar-during-review = Ocultar a barra abaixo durante o review
preferences-always = Sempre
preferences-full-screen-only = Apenas tela cheia
preferences-appearance = Aparência
preferences-general = Geral
preferences-style = Estilo
preferences-review = Review
preferences-distractions = Distrações
preferences-minimalist-mode = Modo minimalista
preferences-editing = Editando
preferences-browsing = Procurando
preferences-default-deck = Deck padrão
preferences-account = Conta AnkiWeb
preferences-note = Nota
preferences-scheduler = Agendamento
preferences-user-interface = Interface do usuário
preferences-import-export = Importar/Exportar

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = Básico
preferences-media = Midias
