editing-actual-size = Scoránaigh méid
editing-add-media = Cuir Meáin Leis
editing-align-left = Ailínigh ar chlé
editing-align-right = Ailínigh ar dheis
editing-an-error-occurred-while-opening = Bhain earráid agus { $val } á oscailt
editing-attach-picturesaudiovideo = Cuir pictiúir/fuaim/fís leis
editing-bold-text = Téacs trom
editing-cards = Cártaí
editing-center = Láraigh
editing-change-color = Malartaigh dath
editing-cloze-deletion = Sliocht iomlánaithe (cárta nua)
editing-cloze-deletion-repeat = Sliocht iomlánaithe (cárta céanna)
editing-couldnt-record-audio-have-you-installed = Níorbh fhéidir taifead fuaime a dhéanamh. An bhfuil 'lame' suite?
editing-customize-card-templates = Saincheap Teimpléid Chártaí
editing-customize-fields = Saincheap Réimsí
editing-cut = Gearr
editing-double-click-image = déchliceáil íomhá
editing-double-click-to-expand = (déchliceáil chun leathnú)
editing-edit-current = Cuir ábhar reatha in Eagar
editing-edit-html = Cuir HTML in eagar
editing-fields = Réimsí
editing-float-left = Íomhá ar chlé
editing-float-right = Íomhá ar dheis
editing-float-none = Íomhá mar a bhfuil
editing-indent = Méadaigh an eang
editing-italic-text = Cló iodálach
editing-jump-to-tags-with-ctrlandshiftandt = Léim go Clibeanna le Ctrl+Shift+T
editing-justify = Comhfhadaigh
editing-latex = LaTeX
editing-latex-equation = Cothromóid LaTeX
editing-latex-math-env = Timpeallacht mata LaTeX.
editing-mathjax-block = MathJax bloc
editing-mathjax-chemistry = MathJax Ceimic
editing-mathjax-inline = MathJax inlíne
editing-mathjax-placeholder = Roghnaigh { $accept } chun glacadh leis agus { $newline } chun dul chuig líne nua.
editing-media = Meáin
editing-ordered-list = Liosta in ord
editing-outdent = Laghdaigh an eang
editing-paste = Greamaigh
editing-record-audio = Déan taifead ar fhuaim
editing-remove-formatting = Bain formáidiú
editing-restore-original-size = Fill ar an tseanmhéid
editing-select-remove-formatting = Roghnaigh an formáidiú a bhainfear
editing-show-duplicates = Taispeáin Dúblaigh
editing-subscript = Foscript
editing-superscript = Forscript
editing-tags = Clibeanna
editing-tags-add = Cuir clib leis
editing-tags-copy = Cóipeáil clibeanna
editing-tags-remove = Scrios clibeanna
editing-tags-select-all = Roghnaigh clibeanna go léir
editing-text-color = Dath an téacs
editing-text-highlight-color = Dath aibhsithe an téacs
editing-to-make-a-cloze-deletion-on = Chun sliocht iomlánú a dhéanamh ar nóta, caithfear cineál an nóta a athrú i dtosach, trí 'Nótaí>Athraigh Cineál Nóta'
editing-toggle-html-editor = Scoránaigh Eagarthóir HTML
editing-toggle-visual-editor = Scoránaigh Eagarthóir Amhairc
editing-toggle-sticky = Greamaitheach (scorán)
editing-expand-field = Leathnaigh réimse
editing-collapse-field = Díleathnaigh réimse
editing-underline-text = Folínigh
editing-unordered-list = Liosta gan ord
editing-warning-cloze-deletions-will-not-work = Rabhadh, ní bheidh aon mhaith sna sleachta iomlánaithe go dtí go mbeidh an cineál 'Iomlánú' roghnaithe thuas.
editing-toggle-mathjax-rendering = Scoránaigh Rindreáil MathJax

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Eagarthóir HTML
