actions-add = Legg til
actions-blue-flag = Blått flagg
actions-cancel = Avbryt
actions-choose = Velg
actions-close = Lukk
actions-copy = Kopier
actions-custom-study = Egen Studie:
actions-decks = Kortstokker
actions-delete = Slett
actions-export = Eksporter
actions-green-flag = Grønt Flagg
actions-help = Hjelp
actions-import = Importere
actions-name = Navn:
actions-new = Ny
actions-new-name = Nytt navn:
actions-preview = Forhåndsvisning
actions-rename = Endre navn
actions-rename-deck = Gi nytt navn til kortstokk
actions-save = Lagre
actions-search = Søk
