card-stats-added = Lagt til
card-stats-first-review = Første repetisjon
card-stats-interval = Intervall
card-stats-ease = Innlæringsgrad
card-stats-review-count = Gjennomganger
card-stats-lapse-count = Feil
card-stats-average-time = Gjennomsnittstid
card-stats-total-time = Total tid
card-stats-new-card-position = Posisjon
card-stats-card-template = Korttype
card-stats-note-type = Notattype
card-stats-deck-name = Kortstokk
card-stats-note-id = Notat ID
card-stats-card-id = Kort ID
card-stats-review-log-date = Dato
card-stats-review-log-time-taken = Tid
card-stats-review-log-type-learn = Lært
card-stats-review-log-type-review = Repeter
card-stats-review-log-type-filtered = Filtrert
