actions-add = Lägg till
actions-blue-flag = Blå märkning
actions-cancel = Avbryt
actions-choose = Välj
actions-close = Stäng
actions-copy = Kopiera
actions-custom-study = Anpassade studier
actions-decks = Kortlekar
actions-delete = Ta bort
actions-export = Exportera
actions-green-flag = Grön märkning
actions-help = Hjälp
actions-import = Importera
actions-manage = Hantera...
actions-name = Namn:
actions-new = Nya
actions-new-name = Nytt namn:
actions-options = Alternativ
actions-options-for = Alternativ för { $val }
actions-preview = Förhandsvisa
actions-rebuild = Återskapa
actions-red-flag = Röd märkning
actions-rename = Byt namn
actions-rename-deck = Byt namn på kortlek
actions-replay-audio = Spela upp ljud igen
actions-reposition = Positionera om
actions-save = Spara
actions-search = Sök
actions-shortcut-key = Genväg: { $val }
actions-suspend-card = Uteslut kort
