card-stats-added = Tillagda
card-stats-first-review = Första repetitionen
card-stats-latest-review = Senaste repetition
card-stats-interval = Intervall
card-stats-ease = Inlärningsgrad
card-stats-review-count = Repetitioner
card-stats-lapse-count = Bortglömda
card-stats-average-time = Genomsnittlig Tid
card-stats-total-time = Sammanlagd Tid
card-stats-card-template = Korttyp
card-stats-note-type = Nottyp
card-stats-deck-name = Kortlek
card-stats-note-id = Noterings-ID
card-stats-card-id = Kort-ID
card-stats-review-log-rating = Betyg
card-stats-review-log-type = Typ
card-stats-review-log-date = Datum
card-stats-review-log-time-taken = Tid
card-stats-review-log-type-learn = Att lära
card-stats-review-log-type-review = Repetera
card-stats-review-log-type-relearn = Lär om
card-stats-review-log-type-filtered = Filtrerad
card-stats-review-log-type-rescheduled = Schemalägg på nytt
