custom-study-all-cards-in-random-order-dont = Alla kort i slumpmässig ordning ( ingen omschemaläggning)
custom-study-all-review-cards-in-random-order = Alla repetitionskort i slumpmässig ordning
custom-study-cards = kort
custom-study-cards-from-the-deck = kort från kortleken
custom-study-choose-tags = Välj taggar
custom-study-custom-study-session = Anpassat studiepass
custom-study-due-cards-only = Endast kort som ska repeteras
custom-study-increase-todays-new-card-limit = Öka gränsen för nya kort för idag
custom-study-increase-todays-new-card-limit-by = Öka gränsen för nya kort för idag med
custom-study-increase-todays-review-card-limit = Öka gränsen för antalet repetitioner för idag
custom-study-increase-todays-review-limit-by = Öka gränsen för antalet repetitioner för idag med
custom-study-new-cards-in-deck-over-today = Nya kort i leken över dagens gräns: { $val }
custom-study-new-cards-only = Endast nya kort
custom-study-no-cards-matched-the-criteria-you = Inga kort matchade de kriterier du uppgav.
custom-study-ok = ОК
custom-study-preview-new-cards = Förhandsgranska nya kort
custom-study-preview-new-cards-added-in-the = Förhandsgranska nya kort tillagda de senaste
custom-study-require-one-or-more-of-these = Kräv en eller fler av dessa etiketter:
custom-study-review-ahead = Repetera i förväg
custom-study-review-ahead-by = Repetera i förväg för
custom-study-review-cards-forgotten-in-last = Repetera glömda kort från de senaste
custom-study-review-forgotten-cards = Repetera glömda kort
custom-study-select = Välj
custom-study-select-tags-to-exclude = Välj etiketter att exkludera:
custom-study-selective-study = Selektiva studier
custom-study-study-by-card-state-or-tag = Studera efter korttillstånd eller etikett
