editing-add-media = Lägg till media
editing-an-error-occurred-while-opening = Ett fel uppstod vid öppning av { $val }
editing-attach-picturesaudiovideo-f3 = Bifoga bilder/ljud/video (F3)
editing-bold-text-ctrlandb = Fet text (Ctrl+B)
editing-cards = Kort
editing-change-colour-f8 = Byt färg (F8)
editing-cloze-deletion-ctrlandshiftandc = Lucktest (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = Kunde inte spela in. Har du installerat 'lame'?
editing-cut = Klipp
editing-edit-current = Redigera Nuvarande
editing-edit-html = Redigera HTML
editing-fields = Fält
editing-html-editor = HTML-redigerare
editing-italic-text-ctrlandi = Kursiv text (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = Hoppa till taggar med Ctrl+Shift+T
editing-latex = LaTeX
editing-latex-equation = LaTeX-ekvation
editing-paste = Klistra in
editing-record-audio-f5 = Spela in ljud (F5)
editing-remove-formatting-ctrlandr = Ta bort formatering (Ctrl+R)
editing-set-foreground-colour-f7 = Sätt förgrundsfärg (F7)
editing-show-duplicates = Visa dubletter
editing-subscript-ctrland = Nedsänkt (Ctrl+=)
editing-superscript-ctrlandand = Upphöjd (Ctrl++)
editing-tags = Etiketter
editing-to-make-a-cloze-deletion-on = För att göra en existerande not till en lucktext måste du ändra korttypen till 'Lucktext' först, via Redigera>Ändra nottyp.
editing-underline-text-ctrlandu = Stryk under text (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = Varning, luckorna visas bara som en lucktext om korttypen är inställd på 'Lucktext'
