notetypes-front-field = Framsida
notetypes-back-field = Baksida
notetypes-add-reverse-field = Lägg till Omvänt
notetypes-text-field = Text
notetypes-basic-name = Grundläggande
notetypes-basic-reversed-name = Bas (och omvänt kort)
notetypes-basic-optional-reversed-name = Bas (valbart omvänt kort)
notetypes-cloze-name = Lucktext
notetypes-basic-type-answer-name = Bas (skriv in svaret)
notetypes-card-2-name = Kort 2
notetypes-card-1-name = Kort 1
notetypes-add = Lägg till: { $val }
notetypes-add-note-type = Lägg till nottyp
notetypes-cards = Kort...
notetypes-clone = Klona: { $val }
notetypes-copy = { $val }-kopia
notetypes-create-scalable-images-with-dvisvgm = Skapa skalbara bilder med dvisvgm
notetypes-delete-this-note-type-and-all = Ta bort den här nottypen och alla dess kort?
notetypes-delete-this-unused-note-type = Ta bort den här oanvända nottypen?
notetypes-fields = Fält...
notetypes-footer = Sidfot
notetypes-header = Sidhuvud
notetypes-note-types = Nottyper
notetypes-options = Alternativ...
notetypes-please-add-another-note-type-first = Lägg till en annan nottyp först.
notetypes-type = Typ
