preferences-automatically-sync-on-profile-openclose = Synka automatiskt när profil öppnas/stängs
preferences-backups = Säkerhetskopior
preferences-backups2 = säkerhetskopior
preferences-backupsanki-will-create-a-backup-of = <b>Säkerhetskopior</b><br>Anki kommer att skapa en säkerhetskopia av din samling varje gång programmet avslutas eller synkroniseras.
preferences-basic = Grundläggande
preferences-change-deck-depending-on-note-type = Ändra kortlek beroende på nottyp
preferences-hardware-acceleration-faster-may-cause-display = Hårdvaruacceleration (snabbare, kan orsaka grafiska problem)
preferences-hours-past-midnight = timmar efter midnatt
preferences-interface-language = Språk för gränssnitt:
preferences-keep = Lagra
preferences-learn-ahead-limit = Gräns för inlärning i förväg
preferences-mins = min
preferences-network = Nätverk
preferences-next-day-starts-at = Nästa dag börjar
preferences-note-media-is-not-backed-up = Observera: Media har inte säkerhetskopierats. Vänligen skapa återkommande säkerhetskopior av din Anki-mapp för säkerhets skull.
preferences-on-next-sync-force-changes-in = Vid nästa synkning, tvinga ändringar i en riktning
preferences-paste-clipboard-images-as-png = Klistra in bilder som PNG
preferences-please-restart-anki-to-complete-language = Starta om Anki för att slutföra ändringen av språk.
preferences-preferences = Inställningar
preferences-scheduling = Schemalägg igen
preferences-show-next-review-time-above-answer = Visa ny repetitionstid ovanför svarsknapparna
preferences-show-remaining-card-count-during-review = Visa återstående antal kort under repetition
preferences-some-settings-will-take-effect-after = Vissa inställningar blir aktiva först efter att du startat om Anki.
preferences-synchronisation = <b>Synkronisering</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Synkronisering</b><br> Inte aktiverat; klicka på knappen Synka i huvudfönstret för att aktivera.
preferences-synchronize-audio-and-images-too = Synkronisera även ljud och bilder
preferences-this-will-reset-any-cards-in = Detta kommer att återställa alla kort i nyinlärda-kön, rensa bort alla filtrerade kortlekar och ändra schemaläggarens version. Vill du fortsätta?
preferences-timebox-time-limit = Tidsgräns för tidsfönster
preferences-when-adding-default-to-current-deck = När du lägger till, använd nuvarande kortlek som förval
