actions-add = افزودن
actions-all-selected = همه انتخاب شده‌ها
actions-any-selected = هر انتخاب شده
actions-cancel = لغو
actions-choose = انتخاب
actions-close = بستن
actions-copy = کپی
actions-custom-study = مطالعۀ سفارشی
actions-decks = دسته‌ها
actions-delete = حذف کردن
actions-export = صادر کردن
actions-filter = فیلتر
actions-help = راهنما
actions-import = وارد کردن
actions-manage = مدیریت…
actions-name = نام:
actions-new = جدید
actions-new-name = نام جدید:
actions-options = تنظیمات
actions-options-for = تنظیمات { $val }
actions-preview = پیش‌نمایش
actions-rebuild = بازسازی
actions-rename = نام‌گذاری مجدد
actions-rename-deck = نامگذاری مجدد دسته
actions-rename-tag = تغییر نام برچسب
actions-rename-with-parents = نامگذاری مجدد همراه والدین
actions-remove-tag = حذف برچسب
actions-replay-audio = پخش مجدد صوت
actions-reposition = تغییر موقعیت
actions-save = ذخیره
actions-search = جست‌و‌جو
actions-select = انتخاب
actions-shortcut-key = کلید میانبر: { $val }
actions-suspend-card = معلق کردن کارت
actions-set-due-date = انتخاب موعد مرور
actions-forget = فراموش کردن
actions-answer-card = پاسخ دادن به کارت
actions-unbury-unsuspend = لغو دفن/تعلیق
actions-add-deck = افزودن دسته
actions-add-note = افزودن یادداشت
actions-update-tag = به‌روز رسانی برچسب
actions-update-note = به‌روز رسانی یادداشت
actions-update-card = به‌روز رسانی کارت
actions-update-deck = به‌روز رسانی دسته
actions-forget-card = فراموش کردن کارت
actions-build-filtered-deck = ایجاد دسته
actions-expand-collapse = گسترش دادن/فشرده سازی
actions-add-notetype = افزودن نوع یادداشت
actions-remove-notetype = حذف نوع یادداشت
actions-update-notetype = به‌روز رسانی نوع یادداشت
actions-update-config = به‌روز رسانی کانفیگ
actions-card-info = مشخصات کارت

## Flags

actions-flag-number = نشان { $number }
actions-flag-red = قرمز
actions-flag-orange = نارنجی
actions-flag-green = سبز
actions-flag-blue = آبی
actions-flag-pink = صورتی
actions-flag-turquoise = فیروزه‌ای
actions-flag-purple = ارغوانی
actions-set-flag = تنظیم نشان
