custom-study-must-rename-deck = لطفاً نام دستۀ مطالعۀ سفارشی فعلی را تغییر دهید.
custom-study-all-cards-in-random-order-dont = همۀ کارت‌ها به‌صورت تصادفی (عدم تغییر زمان‌بندی کارت)
custom-study-all-review-cards-in-random-order = همۀ کارت‌ها در مرحلۀ مرور به‌صورت تصادفی
custom-study-cards = کارت‌ها
custom-study-cards-from-the-deck = کارت‌های دسته
custom-study-choose-tags = انتخاب برچسب
custom-study-custom-study-session = دستۀ مطالعۀ سفارشی
custom-study-due-cards-only = فقط کارت‌های در مرحلۀ مرور
custom-study-increase-todays-new-card-limit = افزایش تعداد کارت‌های جدید امروز
custom-study-increase-todays-new-card-limit-by = افزایش تعداد کارت‌های جدید امروز به تعداد
custom-study-increase-todays-review-card-limit = افزایش تعداد کارت‌های مرور امروز
custom-study-increase-todays-review-limit-by = افزایش تعداد کارت‌های مرور امروز به تعداد
custom-study-new-cards-in-deck-over-today = تعداد کارت‌های جدید موجود در دسته بیشتر از حد مطالعه: { $val }
custom-study-new-cards-only = فقط کارت‌های جدید
custom-study-no-cards-matched-the-criteria-you = هیچ کارتی با معیارهای مشروط شما مطابقت نداشت.
custom-study-ok = تأیید
custom-study-preview-new-cards = پیش نمایش کارتهای جدید
custom-study-preview-new-cards-added-in-the = پیش‌نمایش کارت‌های جدید اضافه شده در آخر
custom-study-require-one-or-more-of-these = یک یا بیشتر از یکی از این برچسب ها لازم است :
custom-study-review-ahead = مرور پیش از موعد
custom-study-review-ahead-by = مرور پیش از موعد به اندازۀ
custom-study-review-cards-forgotten-in-last = مرور کارت‌های فراموش شده در
custom-study-review-forgotten-cards = مرور کارتهای فراموش شده
custom-study-reviews-due-in-deck-over-today = تعداد مرورهای موجود در دسته بیشتر از حد مطالعه: { $val }
custom-study-select = انتخاب
custom-study-select-tags-to-exclude = ‌انتخاب برچسب‌ها برای مستثنی کردن:
custom-study-selective-study = مطالعه گزینشی
custom-study-study-by-card-state-or-tag = مطالعه بر اساس وضعیت کارت یا برچسب
