editing-add-media = افزودن رسانه
editing-align-left = چینش چپ
editing-align-right = چینش راست
editing-an-error-occurred-while-opening = یک خطا هنگام باز کردن رخ داده است { $val }
editing-attach-picturesaudiovideo = پیوست کردن عکس/صدا/فیلم
editing-bold-text = متن پررنگ (بولد)
editing-cards = کارت‌ها
editing-center = مرکز
editing-change-color = تغییر رنگ
editing-cloze-deletion = جاخالی
editing-couldnt-record-audio-have-you-installed = ضبط صدا ممکن نیست. آیا ‘lame’ را نصب کرده‌اید؟
editing-customize-card-templates = شخصی‌سازی قالب کارت
editing-customize-fields = شخصی‌سازی فیلدها
editing-cut = برش
editing-edit-current = ویرایش فعلی
editing-edit-html = ویرایش HTML
editing-fields = فیلدها
editing-html-editor = ویرایشگر HTML
editing-indent = افزایش فاصله
editing-italic-text = متن کج (ایتالیک)
editing-jump-to-tags-with-ctrlandshiftandt = رفتن به برچسب‌ها ‫با کنترل+شیفت+T
editing-justify = هم‌تراز کردن
editing-latex = LaTeX
editing-latex-equation = معادله LaTeX
editing-latex-math-env = محیط ریاضی LaTeX.
editing-mathjax-block = بلوک MathJax
editing-mathjax-chemistry = فرمول شیمی MathJax
editing-mathjax-inline = ‫MathJax درون خطی
editing-media = رسانه
editing-ordered-list = لیست مرتب
editing-outdent = کاهش فاصله
editing-paste = جاگذاری
editing-record-audio = ضبط صدا
editing-remove-formatting = حذف تزئین
editing-set-text-color = تنظیم رنگ متن
editing-set-text-highlight-color = تنظیم رنگ هایلایت متن
editing-show-duplicates = نمایش تکراریها
editing-subscript = ‏‏پایین نویس
editing-superscript = پایین نویس
editing-tags = برچسب‌ها
editing-to-make-a-cloze-deletion-on = برای ایجاد جاخالی روی یادداشت موجود، اول باید نوع یادداشت را از مسیر 'یادداشت‌ها>تغییر نوع یادداشت' تغییر دهید
editing-toggle-sticky = تغییر وضعیت چسبان
editing-underline-text = خط کشیدن زیر متن
editing-unordered-list = لیست بدون ترتیب
editing-warning-cloze-deletions-will-not-work = اخطار، جای خالی تا وقتی که شما نوع را از بالا به جای خالی تغییر ندهید بطور صحیح کار نخواهد کرد.

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-bold-text-ctrlandb = متن بولد (Ctrl+B)
editing-italic-text-ctrlandi = متن کج (Ctrl+I)
editing-underline-text-ctrlandu = خط کشیدن زیر متن (Ctrl+U)
editing-subscript-ctrland = زیرنویس (=+Ctrl)
editing-superscript-ctrlandand = بالانویس (++Ctrl)
editing-remove-formatting-ctrlandr = پارک کردن تزئین (Ctrl+R)
editing-record-audio-f5 = ضبط صدا (F5)
editing-attach-picturesaudiovideo-f3 = پیوست کردن عکس/صدا/فیلم (F3)
editing-cloze-deletion-ctrlandshiftandc = ایجاد جاخالی (Ctrl+Shift+C)
editing-change-colour-f8 = تغییر رنگ (F8)
editing-set-foreground-colour-f7 = تنظیم رنگ پیش‌زمینه (F7)
editing-customize-card-templates-ctrlandl = ویرایش قالب‌های کارت (Ctrl+L)
editing-set-foreground-color = تنظیم رنگ پیش‌زمینه
