fields-add-field = افزودن فیلد
fields-delete-field-from = حذف فیلد از { $val }؟
fields-editing-font = ویرایش فونت
fields-field = فیلد:
fields-field-name = نام فیلد:
fields-fields-for = فیلدهای { $val }
fields-font = فونت
fields-new-position-1 = موقعیت جدید (1...{ $val }):
fields-notes-require-at-least-one-field = یادداشت‌ها حداقل یک فیلد لازم دارند.
fields-remember-last-input-when-adding = بخاطر سپردن آخرین ورودی هنگام اضافه کردن
fields-reverse-text-direction-rtl = جهت متن معکوس (راست به چپ)
fields-size = اندازه:
fields-sort-by-this-field-in-the = بر اساس این فیلد در مرورگر مرتب کن
fields-that-field-name-is-already-used = نام فیلد قبلا استفاده شده است.
fields-name-first-letter-not-valid = نام فیلد نباید با #، ^ یا / شروع شود.
fields-name-invalid-letter = نام فیلد نباید حاوی :، { "{" } یا { "}" } باشد.
