preferences-automatically-sync-on-profile-openclose = همگام‌سازی خودکار با بازکردن/بستن پروفایل.
preferences-backups = پشتیبان‌ها
preferences-backups2 = پشتیبان‌ها
preferences-backupsanki-will-create-a-backup-of = <b>پشتیبان‌گیری</b><br>آنکی هر بار که بسته می‌شود یا همگام‌سازی می‌شود،یک پشتیبان از مجموعه‌ی شما ایجاد خواهد کرد.
preferences-basic = پایه
preferences-change-deck-depending-on-note-type = تغییر دسته براساس نوع یادداشت
preferences-changes-will-take-effect-when-you = تغییرات بعد از اینکه شمال آنکی را ری‌استارت کردید اعمال خواهند شد.
preferences-hours-past-midnight = ساعت از نیمه شب گذشته
preferences-interface-language = زبان رابط کاربری:
preferences-interrupt-current-audio-when-answering = توقف پخش صدا هنگام نمایش پاسخ
preferences-keep = نگه داشتن
preferences-learn-ahead-limit = حد مطالعه پیش از موعد
preferences-mins = دقیقه
preferences-network = شبکه
preferences-next-day-starts-at = شروع روز جدید در
preferences-night-mode = حالت شب
preferences-note-media-is-not-backed-up = توجه : از رسانه پشتیبان گرفته نشده است. لطفا متناوباً از پوشه آنکی خود پشتیان تهیه نمایید تا آن ایمن بماند.
preferences-on-next-sync-force-changes-in = در همگام‌سازی بعدی، اجباراً در یک دستور تغییر بده
preferences-paste-clipboard-images-as-png = تصویر حافظه موقت به عنوان PNG جاگذاری شود
preferences-paste-without-shift-key-strips-formatting = جاگذاری بدون نگه داشتن کلید شیفت تزئینات فایل را از بین می‌برد
preferences-periodically-sync-media = همگام‌سازی رسانه به‌صورت دوره‌ای
preferences-please-restart-anki-to-complete-language = لطفاً برای نهایی‌سازی تغییر زبان آنکی را ری‌استارت کنید.
preferences-preferences = تنظیمات
preferences-scheduling = زمانبندی
preferences-show-learning-cards-with-larger-steps = کارت‌های در مرحلۀ یادگیری با قدم‌های بزرگتر را قبل از مرورها نشان بده
preferences-show-next-review-time-above-answer = زمان مرور بعدی را در بالای دکمه پاسخ نشان بده
preferences-show-play-buttons-on-cards-with = دکمۀ پخش را روی کارت‌های دارای صدا نشان بده
preferences-show-remaining-card-count-during-review = تعداد کارت باقیمانده در طول مرور را نشان بده
preferences-some-settings-will-take-effect-after = برخی از تغییرات پس از اینکه انکی دوباره شروع شد اعمال خواهند شد.
preferences-synchronisation = همگام‌سازی
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>همگام‌سازی</b><br> غیرفعال است؛ برای فعال کردن آن در پنجرۀ اصلی روی دکمۀ همگام‌سازی کلیک کنید.
preferences-synchronize-audio-and-images-too = تصاویر و صوت نیز یکپارچه شوند
preferences-this-will-reset-any-cards-in = این عمل همۀ کارت‌های موجود در مرحلۀ یادگیری را به کارت تازه تبدیل و همۀ دسته‌های فیلتر شده را پاک کرده و نوع زمانبندی کارت‌ها را تغییر خواهد داد. ادامه؟
preferences-timebox-time-limit = بازۀ زمانی هشدار مطالعه
preferences-user-interface-size = اندازۀ رابط کاربری
preferences-when-adding-default-to-current-deck = هنگام افزدون کارت جدید، دسته فعلی به عنوان پیش فرض باشد
preferences-you-can-restore-backups-via-fileswitch = شما می‌توانید فایل‌های پشتیبان را از مسیر فایل>تغییر پروفایل بازگردانی کنید.
preferences-legacy-timezone-handling = مدیریت بازه زمانی قدیمی (دارای باگ، ولی برای AnkiDroid قدیمی‌تر از 2.14 ضروری است)
preferences-theme = طرح
preferences-editing = در حال ویرایش
