[package]
name = "tugger-code-signing"
version = "0.10.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Cross-platform code signing functionality"
keywords = ["tugger"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[dependencies]
anyhow = "1.0"
apple-bundles = "0.14"
apple-codesign = "0.20"
bcder = "0.7"
cryptographic-message-syntax = "0.18"
goblin = "0.5"
log = "0.4"
p12 = "0.6"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls"] }
simple-file-manifest = "0.11"
tempfile = "3.2"
thiserror = "1.0"
x509-certificate = "0.15"
yasna = "0.5"

[dependencies.tugger-windows-codesign]
version = "0.10.0-pre"
path = "../tugger-windows-codesign"
