actions-add = إضافة
actions-all-selected = كل المحدد
actions-any-selected = أي من المحدد
actions-cancel = إلغاء
actions-choose = اختيار
actions-close = إغلاق
actions-copy = نسخ
actions-create-copy = إنشاء نسخة
actions-custom-study = دراسة مخصصة
actions-decks = رزم
actions-decrement-value = إنقاص القيمة
actions-delete = حذف
actions-export = تصدير
actions-filter = فلتر
actions-help = مساعدة
actions-increment-value = رفع القيمة
actions-import = استيراد
actions-manage = إدارة...
actions-name = اسم:
actions-new = جديدة
actions-new-name = الاسم الجديد:
actions-options = خيارات
actions-options-for = خيارات { $val }
actions-preview = معاينة
actions-rebuild = إعادة إنشاء
actions-rename = إعادة تسمية
actions-rename-deck = تغيير اسم الرزمة
actions-rename-tag = إعادة تسمية الوسم
actions-rename-with-parents = تغيير الاسم الكامل
actions-remove-tag = حذف الوسم
actions-replay-audio = إعادة تشغيل الصوت
actions-reposition = تغيير الموضع
actions-save = حفظ
actions-search = بحث
actions-select = تحديد
actions-shortcut-key = اختصار: { $val }
actions-suspend-card = تعليق البطاقة
actions-set-due-date = ضبط تاريخ الاستحقاق
actions-answer-card = الإجابة عن بطاقة
actions-unbury-unsuspend = نكش/تفعيل
actions-add-deck = إضافة رزمة
actions-add-note = إضافة ملحوظة
actions-update-tag = تحديث وسم
actions-update-note = تحديث ملحوظة
actions-update-card = تحديث بطاقة
actions-update-deck = تحديث رزمة
actions-forget-card = نسيان بطاقة
actions-build-filtered-deck = بناء رزمة
actions-add-notetype = إضافة نوع ملحوظة
actions-remove-notetype = حذف نوع ملحوظة
actions-update-notetype = تحديث نوع ملحوظة
actions-update-config = تحديث إعداد
actions-card-info = معلومات البطاقة
actions-previous-card-info = معلومات البطاقة السابقة
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = لا يتوفر هذا الخيار حاليًا في نظامك.

## Flags

actions-flag-number = مؤشر { $number }
actions-flag-red = أحمر
actions-flag-orange = برتقالي
actions-flag-green = أخضر
actions-flag-blue = أزرق
actions-flag-pink = زهري
actions-flag-turquoise = فيرزوي
actions-flag-purple = بنفسجي
actions-set-flag = وضع مؤشر
