preferences-automatically-sync-on-profile-openclose = مزامنة تلقائية عند فتح الملف الشخصي وإغلاقه
preferences-backups = نُسخ احتياطية
preferences-change-deck-depending-on-note-type = تغيير الرزمة اعتمادًا على نوع الملحوظة
preferences-changes-will-take-effect-when-you = ستجري التغييرات عند إعادة تشغيل أنكي.
preferences-hours-past-midnight = ساعة بعد منتصف الليل
preferences-language = اللغة
preferences-interrupt-current-audio-when-answering = إيقاف التسجيل الصوتي الحالي عند الإجابة
preferences-learn-ahead-limit = حد التعلم المبكر
preferences-mins = دقيقة
preferences-network = الشبكة
preferences-next-day-starts-at = يبدأ اليوم التالي في
preferences-media-is-not-backed-up = الوسائط غير منسوخة احتياطيًا. الرجاء نسخ مجلد أنكي الخاص بك احتياطيًا من وقت لآخر.
preferences-on-next-sync-force-changes-in = فرض التغييرات في جانب واحد عند المزامنة التالية
preferences-paste-clipboard-images-as-png = لصق الصور من الحافظة بصيغة PNG
preferences-paste-without-shift-key-strips-formatting = اللصق بدون الضغط على زر shift يزيل التنسيق
preferences-periodically-sync-media = مزامنة الوسائط من وقت لآخر
preferences-please-restart-anki-to-complete-language = أعد تشغيل أنكي لإكمال تغيير اللغة.
preferences-preferences = تفضيلات
preferences-scheduling = جدولة
preferences-show-learning-cards-with-larger-steps = عرض بطاقات التعلم ذات الخطوات الأكبر قبل المراجعات
preferences-show-next-review-time-above-answer = إظهار وقت المراجعة التالية فوق أزرار الإجابة
preferences-show-play-buttons-on-cards-with = إظهار أزرار التشغيل في البطاقات التي فيها تسجيلات صوتية
preferences-show-remaining-card-count = أظهر عدد البطاقات المتبقية
preferences-some-settings-will-take-effect-after = ستُفعَّل بعض الإعدادات بعد إعادة تشغيل أنكي.
preferences-tab-synchronisation = المزامنة
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>مزامنة</b><br> ليست مفعلة حاليًا؛ اضغط زر المزامنة في النافذة الرئيسية للتفعيل.
preferences-synchronize-audio-and-images-too = مزامنة التسجيلات الصوتية والصور أيضًا
preferences-timebox-time-limit = مهلة تقسيم المهام
preferences-user-interface-size = حجم واجهة المستخدم
preferences-when-adding-default-to-current-deck = معاملة الرزمة الحالية كرزمة افتراضية عند إضافة بطاقات
preferences-you-can-restore-backups-via-fileswitch = تستطيع استعادة النسخ الاحتياطية من خلال ملف>تبديل الملف الشخصي.
preferences-legacy-timezone-handling = طريقة المعالجة القديمة للمناطق الزمنية (فيها أخطاء، لكنها متطلبة لإصدارات أنكيدرويد من 2.14 وأقدم)
preferences-default-search-text = نص البحث الافتراضي
preferences-default-search-text-example = مثال: 'deck:current '
preferences-theme = السمة
preferences-theme-follow-system = حسب النظام
preferences-theme-light = ساطع
preferences-theme-dark = داكن
preferences-v3-scheduler = مجدول V3
preferences-ignore-accents-in-search = تجاهل حركات الأحرف في البحث (أبطأ)
preferences-backup-explanation =
    يأخذ أنكي نسخ احتياطية لمجموعتك بشكل دوري. سيبدأ أنكي بحذف بعض النسخ
    لتوفير مساحة القرص بعد مضي أكثر من يومين على أخدها.
preferences-daily-backups = عدد النسخ اليومية المحفوظة:
preferences-weekly-backups = عدد النسخ الأسبوعية المحفوظة:
preferences-monthly-backups = عدد النسخ الشهرية المحفوظة:
preferences-minutes-between-backups = الدقائق بين النسخ التلقائية:
preferences-reduce-motion = تقليل الأنميشن
preferences-reduce-motion-tooltip = إيقاف تفعيل تأثيرات متحركة عديدة في واجهة المستخدم
preferences-custom-sync-url = خادم مزامنة مستضاف ذاتيًا
preferences-custom-sync-url-disclaimer = للمستخدمين المتقدمين - اطلع على دليل الاستخدام
preferences-hide-top-bar-during-review = إخفاء الشريط العلوي أثناء المراجعة
preferences-hide-bottom-bar-during-review = إخفاء الشريط السفلي أثناء المراجعة
preferences-always = دائمًا
preferences-full-screen-only = في وضع ملء الشاشة فقط
preferences-appearance = المظهر
preferences-general = عام
preferences-style = النمط
preferences-review = المراجعة
preferences-distractions = المشتتات
preferences-minimalist-mode = الوضع المبسط
preferences-editing = تحرير
preferences-browsing = التصفح
preferences-default-deck = الرزمة الافتراضية
preferences-account = حساب AnkiWeb
preferences-note = ملاحظة
preferences-scheduler = المجدول
preferences-user-interface = واجهة المستخدم
preferences-import-export = الاستيراد/التصدير
preferences-network-timeout = مهلة الشبكة
preferences-reset-window-sizes = تصفير أحجام النوافذ
preferences-reset-window-sizes-complete = تم تصفير أحجام النوافذ ومواقعها.

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = أساسي
preferences-reviewer = شاشة المراجعة
preferences-media = الوسائط
