[package]
name = "tugger-rpm"
version = "0.6.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "RPM packaging primitives"
keywords = ["package", "rpm", "tugger"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[dependencies]
anyhow = "1.0"
rpm-rs = "0.8"

[dependencies.tugger-file-manifest]
version = "0.5.0"
