addons-addon-has-no-configuration = Complemento não tem configuração.
addons-addon-was-not-downloaded-from-ankiweb = O add-on não foi descarregado do AnkiWeb.
addons-changes-will-take-effect-when-anki = As alterações terão efeito quando o Anki for reiniciado.
addons-check-for-updates = Verificar atualizações
addons-checking = Verificando...
addons-code = Código:
addons-config = Definições
addons-configuration = Definições
addons-disabled = (desativado)
addons-downloaded-fnames = { $fname } foi descarregado
addons-get-addons = Obter add-ons...
addons-install-addon = Instalar Complemento
addons-invalid-code = Código inválido.
addons-invalid-configuration = Configuração inválida:
addons-no-updates-available = Não há atualizações disponíveis.
addons-toggle-enabled = Alternância habilitado
addons-view-addon-page = Visitar página do add-on
addons-view-files = Ver os ficheiros
