actions-add = 追加
actions-all-selected = 選択条件すべてを含む
actions-any-selected = 選択条件を含む
actions-cancel = キャンセル
actions-choose = 選択
actions-close = 閉じる
actions-copy = コピー
actions-create-copy = コピーを作成
actions-custom-study = カスタム学習
actions-decks = デッキ
actions-delete = 削除
actions-export = エクスポート
actions-filter = フィルター
actions-help = ヘルプ
actions-import = インポート
actions-manage = 管理...
actions-name = 名前:
actions-new = 新規
actions-new-name = 新しい名前:
actions-options = オプション
actions-options-for = { $val } のオプション
actions-preview = プレビュー
actions-rebuild = 再構築
actions-rename = 名前を変更
actions-rename-deck = デッキ名を変更
actions-rename-tag = タグ名を変更
actions-rename-with-parents = 親デッキも併せて名前を変更
actions-remove-tag = タグを削除
actions-replay-audio = オーディオを再生
actions-reposition = 並び替える
actions-save = 保存
actions-search = 検索
actions-select = 選択
actions-shortcut-key = ショートカットキーは「{ $val }」
actions-suspend-card = カードを保留
actions-set-due-date = 期日設定
actions-answer-card = カードの回答
actions-unbury-unsuspend = 延期解除/保留解除
actions-add-deck = デッキを追加
actions-add-note = ノートを追加
actions-update-tag = タグの更新
actions-update-note = ノートの更新
actions-update-card = カードを更新
actions-update-deck = デッキを更新
actions-forget-card = カードをリセットする
actions-build-filtered-deck = デッキを構築
actions-add-notetype = ノートタイプを追加
actions-remove-notetype = ノートタイプを削除
actions-update-notetype = ノートタイプを更新
actions-update-config = 設定を更新
actions-card-info = カード情報
actions-previous-card-info = 直前カード情報
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = このアクションは現在お使いのシステムでサポートされていません。

## Flags

actions-flag-number = フラグ{ $number }
actions-flag-red = 赤
actions-flag-orange = 橙
actions-flag-green = 緑
actions-flag-blue = 青
actions-flag-pink = ピンク
actions-flag-turquoise = ターコイズ
actions-flag-purple = 紫
actions-set-flag = フラグの変更
