adding-add-shortcut-ctrlandenter = 追加（ショートカット: ctrl+enter）
adding-added = 追加しました
adding-close-and-lose-current-input = 閉じて現在の入力を破棄しますか？
adding-edit = 「{ $val }」を編集
adding-history = 履歴
adding-note-deleted = (ノートを削除しました)
adding-shortcut = ショートカット: { $val }
adding-the-first-field-is-empty = 最初のフィールドが空欄です。
adding-you-have-a-cloze-deletion-note = 穴埋め問題のノートタイプがありますが、穴埋め問題を作っていません。続行しますか。
adding-cloze-outside-cloze-notetype = 穴埋め問題機能は穴埋め問題のノートタイプでのみ使用できます。
adding-cloze-outside-cloze-field = 穴埋め問題機能は「cloze:」（穴埋め）フィルターを使用しているフィールドでのみ使用できます。多くの場合、最初のフィールドがそれに該当します。
