editing-actual-size = 実寸表示（エディターの幅が上限）/ コンパクト表示
editing-add-media = メディアを追加
editing-align-left = 左寄り
editing-align-right = 右寄り
editing-an-error-occurred-while-opening = { $val } を開いた時にエラーが発生しました。
editing-attach-picturesaudiovideo = メディア(画像/音声/動画)を追加
editing-bold-text = 太字
editing-cards = カード
editing-center = 中央
editing-change-color = 色を変更
editing-cloze-deletion = 穴埋め問題
editing-cloze-deletion-repeat = 穴埋め問題 (同じカード )
editing-couldnt-record-audio-have-you-installed = 音声を録音できませんでした。LAMEを
editing-customize-card-templates = カードテンプレートをカスタマイズ
editing-customize-fields = フィールドをカスタマイズ
editing-cut = カット
editing-double-click-image = 画像をダブルクリック
editing-double-click-to-expand = （ダブルクリックで実寸表示）
editing-edit-current = 現在のノートを編集
editing-edit-html = HTML を編集
editing-fields = フィールド
editing-float-left = 左寄せ配置（後に続く内容は右側に回り込ませる）
editing-float-right = 右寄せ配置（後に続く内容は左側に回り込ませる）
editing-float-none = 左右への配置指定なし（後に続く内容の回り込みもなし）
editing-indent = インデントを増やす
editing-italic-text = イタリック
editing-jump-to-tags-with-ctrlandshiftandt = Ctrl+Shift+T でタグフィールドに移動します。
editing-justify = 両端揃え
editing-latex = LaTeX
editing-latex-equation = LaTeX インライン数式
editing-latex-math-env = LaTeX ディスプレイ数式
editing-mathjax-block = MathJaxブロック
editing-mathjax-chemistry = MathJax 化学
editing-mathjax-inline = MathJax インライン
editing-mathjax-placeholder = 受け入れる場合は { $accept } を、改行する場合は { $newline } を押してください。
editing-media = メディア
editing-ordered-list = リスト（順序あり）
editing-outdent = インデントを減らす
editing-paste = 貼り付け
editing-record-audio = 音声を録音
editing-remove-formatting = 書式を取り除く
editing-restore-original-size = 元のサイズにリセット
editing-select-remove-formatting = 削除する書式を選択
editing-show-duplicates = 重複を表示する
editing-subscript = 下付き文字
editing-superscript = 上付き文字
editing-tags = タグ
editing-tags-add = タグを追加
editing-tags-copy = タグをコピー
editing-tags-remove = タグを削除
editing-tags-select-all = すべてのタグを選択
editing-text-color = 文字色
editing-text-highlight-color = 文字の背景色
editing-to-make-a-cloze-deletion-on = このノートに穴埋め問題を作るには、まず今のノートタイプを穴埋め問題に対応したノートタイプに変更する必要があります。[編集] > [ノートタイプを変更]から、穴埋め問題に対応したノートタイプを選択してください。（Ankiインストール時から付属しているノートタイプのうちでは、「Cloze」が穴埋め問題に対応しています。）
editing-toggle-html-editor = HTMLエディターを表示
editing-toggle-visual-editor = ビジュアルエディターを表示/非表示
editing-toggle-sticky = この内容を固定
editing-underline-text = 下線を追加
editing-unordered-list = リスト（順序なし）
editing-warning-cloze-deletions-will-not-work = 注意: 穴埋め問題は上部にある「ノートタイプ」の設定を「Cloze」（穴埋め）タイプに変更するまで機能しません。

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML エディタ
