fields-add-field = フィールドを追加
fields-delete-field-from = { $val } からフィールドを削除しますか？
fields-editing-font = フォントを編集
fields-field = フィールド:
fields-field-name = フィールド名:
fields-description = 詳細
fields-description-placeholder = エディター画面内の このフィールド名の右に、この内容のツールチップを表示します
fields-fields-for = { $val } のフィールド
fields-font = フォント:
fields-new-position-1 = 新しい位置 (1...{ $val }):
fields-notes-require-at-least-one-field = ノートには最低一つのフィールドが必要です。
fields-reverse-text-direction-rtl = 右から左入力 (RTL)
fields-size = サイズ:
fields-sort-by-this-field-in-the = このフィールドでソート(並び替え)する
fields-that-field-name-is-already-used = そのフィールド名は既に使用しています。
fields-name-first-letter-not-valid = フィールド名の始めに「#」「^」「/」を使用することはできません。
fields-name-invalid-letter = フィールド名にはこれらを含めることはできません：:, ", { "{" }, { "}" }
