actions-add = Toevoegen
actions-blue-flag = Blauwe vlag
actions-cancel = Annuleren
actions-choose = Kiezen
actions-close = Sluiten
actions-copy = Kopiëren
actions-custom-study = Aangepaste studie
actions-decks = Sets
actions-delete = Verwijderen
actions-export = Exporteren
actions-green-flag = Groene vlag
actions-import = Importeren
actions-manage = Beheren...
actions-name = Naam:
actions-new = Nieuw
actions-new-name = Nieuwe naam:
actions-options = Instellingen
actions-options-for = Instellingen voor { $val }
actions-orange-flag = Oranje vlag
actions-preview = Voorvertoning
actions-rebuild = Opnieuw opbouwen
actions-red-flag = Rode vlag
actions-rename = Hernoemen
actions-rename-deck = Set hernoemen
actions-replay-audio = Geluid opnieuw afspelen...
actions-reposition = Volgorde veranderen
actions-save = Opslaan
actions-search = Zoeken
actions-shortcut-key = Sneltoets: { $val }
actions-suspend-card = Kaart opschorten
