qt-misc-addon-will-be-installed-when-a = افزونه بعد از باز کردن پروفایل نصب خواهد شد.
qt-misc-addons = افزونه‌ها
qt-misc-all-cards-notes-and-media-for = تمام کارت‌ها، یادداشت‌ها و فایل‌های رسانه برای این پروفایل حذف خواهد شد. آیا از انجام این عمل اطمینان دارید؟
qt-misc-anki-updatedanki-has-been-released = <h1>آنکی به‌روزرسانی شد</h1>آنکی { $val } منتشر شده است.<br><br>
qt-misc-automatic-syncing-and-backups-have-been = همگام‌سازی مجدد در هنگام بازنشانی غیرفعال شدند. برای فعالسازی مجدد، پروفایل را ببندید یا آنکی را ری‌استارت کنید.
qt-misc-back-side-only = فقط پشت کارت
qt-misc-backing-up = در حال پشتیبان‌گیری...
qt-misc-browse = جستجو
qt-misc-change-note-type-ctrlandn = تغییر نوع یادداشت (Ctrl+N)
qt-misc-check-the-files-in-the-media = بررسی فایل‌ها در شاخۀ رسانه
qt-misc-choose-deck = انتخاب دسته
qt-misc-choose-note-type = انتخاب نوع یادداشت
qt-misc-closing = در حال بستن…
qt-misc-configure-interface-language-and-options = پیکربندی رابط زبان و تنظیمات
qt-misc-copy-to-clipboard = ‫کپی به حافظه
qt-misc-create-filtered-deck = ایجاد دستۀ فیلتر شده...
qt-misc-debug-console = کنسول اشکال‌یابی
qt-misc-deck-will-be-imported-when-a = وقتی یک پروفایل باز شده باشد، دسته وارد خواهد شد.
qt-misc-default = پیش‌فرض
qt-misc-empty-cards = کارت‌های خالی...
qt-misc-error-during-startup = خطا هنگام شروع: { $val }
qt-misc-filtered-deck = دسته فیلتر شده { $val }
qt-misc-ignore-this-update = این به‌روزرسانی را نادیده بگیر
qt-misc-in-order-to-ensure-your-collection = برای اطمینان از درست کار کردن مجموعۀ شما هنگام استفاده از دستگاه‌های مختلف، ساعت کامپیوتر شما باید به درستی تنظیم شده باشد. ساعت ممکن است اشتباه باشد حتی اگر کامپیوتر زمان محلی را به‌درستی نشان می‌دهد.  لطفاً به تنظیمات زمان کامپیوتر خود مراجعه کرده و موارد زیر را بررسی کنید:  -ق.ظ/ب.ظ -درست نبودن ساعت -روز، ماه، سال -ناحیۀ زمانی -جلو/عقب شدن ساعت (ساعت بهاری/پاییزی)  تفاوت با زمان فعلی: { $val }.
qt-misc-invalid-property-found-on-card-please = ویژگی نامعتبر در کارت یافت شد. لطفا از مسیر ابزارها>بررسی دیتابیس استفاده کنید، اگر مشکل همچنان ادامه داشت، لطفاً در وبسایت پشتیبانی درخواست کمک کنید.
qt-misc-loading = درحال بارگذاری...
qt-misc-manage = مدیریت
qt-misc-manage-note-types = مدیریت انواع یادداشت‌ها
qt-misc-name-exists = نام موجود است.
qt-misc-non-unicode-text = <متن غیر یونیکد>
qt-misc-optimizing = درحال بهینه‌سازی ...
qt-misc-please-connect-a-microphone-and-ensure = لطفا میکروفون را متصل کنید و مطمئن شوید که سایر برنامه ها از سیستم صوتی استفاده نمی کنند.
qt-misc-please-ensure-a-profile-is-open = لطفا مطمئن شوید که یک پروفایل باز است و آنکی مشغول نیست، سپس مجدداً سعی نمایید.
qt-misc-please-select-1-card = (لطفا یک کارت انتخاب کنید)
qt-misc-please-select-a-deck = لطفا یک دسته انتخاب کنید.
qt-misc-please-use-fileimport-to-import-this = لطفاً از مسیر فایل>وارد کردن فایل برای وارد کردن این فایل استفاده کنید.
qt-misc-processing = درحال پردازش...
qt-misc-replace-your-collection-with-an-earlier = جایگزین کردن مجموعه با یک فایل پشتیبان قبلی؟
qt-misc-resume-now = الان ادامه بده
qt-misc-revert-to-backup = بازگردانی به پشتیبان
qt-misc-reverted-to-state-prior-to = برگشت به حالت قبلی به '{ $val }'.
qt-misc-segoe-ui = "Segoe UI"
qt-misc-shift-key-was-held-down-skipping = کلید شیفت پایین نگه داشته شده بود. همگام‌سازی خودکار و بارگذاری افزونه‌ها انجام نشد.
qt-misc-shortcut-key-left-arrow = کلید میانبر: فلش چپ
qt-misc-shortcut-key-right-arrow-or-enter = کلید میانبر: فلش راست یا اینتر
qt-misc-stats = آمار
qt-misc-study-deck = مطالعۀ دسته...
qt-misc-sync = همگام سازی
qt-misc-target-deck-ctrlandd = دسته هدف (Ctrl+D)
qt-misc-the-following-character-can-not-be = کاراکتر زیر قابل استفاده نیست: { $val }
qt-misc-the-requested-change-will-require-a = هنگام همگام‌سازی بعدی مجموعۀ خود، به یک بارگذاری کامل دیستابیس نیاز خواهید داشت. اگر مرور یا تغییرات دیگری روی دستگاه‌های دیگر دارید و هنوز آنها را همگام‌سازی نکرده‌اید، آنها از بین خواهد رفت. آیا ادامه می‌دهید؟
qt-misc-there-must-be-at-least-one = حداقل یک پروفایل باید وجود داشته باشد.
qt-misc-this-file-exists-are-you-sure = این فایل موجود است. آیا مطمئن هسیتد که می خواهید آن را بازنویسی کنید؟
qt-misc-unable-to-access-anki-media-folder = عدم دسترسی به پوشۀ فایل‌های رسانۀ آنکی. اختیارات پوشۀ موقت سیستم شما ممکن است نادرست باشند.
qt-misc-unable-to-move-existing-file-to = امکان انتقال فایل به سطل زباله وجود ندارد - لطفاً سیستم خود را ری‌استارت کنید.
qt-misc-undo = برگرداندن
qt-misc-undo2 = برگرداندن { $val }
qt-misc-unexpected-response-code = کد پاسخ نامعتبر: { $val }
qt-misc-waiting-for-editing-to-finish = برای ویرایش تا پایان منتظر بمانید
qt-misc-would-you-like-to-download-it = آیا میخواهید اکنون این را بارگیری نمایید؟
qt-misc-your-collection-file-appears-to-be = مجموعۀ شما خراب است. این اتفاق ممکن است در اثر کپی یا تغییر محل فایل در حالی که آنکی باز بوده است، یا در اثر بازگردانی مجموعه از یک فایل موجود بر فضای ذخیره‌سازی ابری یا سرور محلی رخ داده باشد. اگر بعد از ری‌استارت کردن سیستم شما مشکل همچنان ادامه داشت، لطفاً از یک پشتیبان خودکار در صفحۀ انتخاب پروفایل برای بازگردانی مجموعۀ خود استفاده کنید.
qt-misc-your-computers-storage-may-be-full = فضای ذخیره‌سازی سیستم شما ممکن است پر باشد. لطفاً تعدادی از فایل‌های غیرضروری را حذف کرده، و سپس دوباره امتحان کنید.
qt-misc-your-firewall-or-antivirus-program-is = فایروال یا آنتی ویروس شما از برقراری ارتباط توسط آنکی جلوگیری می‌کند. لطفاً در فایروال یا آنتی ویروس خود یک استثنا برای آنکی اضافه کنید.
qt-misc-error = خطا
qt-misc-no-temp-folder = پوشه موقت قابل استفاده پیدا نشد. از اینکه C:\\temp وجود دارد یا TEMP در دستگاه شما به یک پوشه قابل ویرایش و صحیح اشاره دارد.
qt-misc-incompatible-video-driver = درایور ویدیو شما ناسازگار است. لطفاً آنکی را ری‌استارت کنید، تا آنکی از یک حالت آهسته و سازگار استفاده کند.
qt-misc-error-loading-graphics-driver = خطا در باز کردن درایور گرافیک '{ $mode }'. لطفاً آنکی را ری‌استارت کنید تا از درایور بعدی استفاده کند. { $context }
qt-misc-anki-is-running = آنکی از قبل اجرا شده است
qt-misc-if-instance-is-not-responding = اگر آنکی که از قبل باز شده است اجرا نمی‌شود، لطفاً آن را با استفاده از تسک منیجر خود ببندید یا دستگاه خود را ری‌استارت کنید.
qt-misc-second =
    { $count ->
       *[other] { $count } ثانیه
    }
