actions-add = Tambah
actions-all-selected = Pilih Semua
actions-any-selected = Pilih tiap-tiap
actions-cancel = Batal
actions-choose = Memilih
actions-close = Tutup
actions-copy = Salin
actions-create-copy = Buat Salinan
actions-custom-study = Belajar Kustom
actions-decks = Dek
actions-delete = Hapus
actions-export = Ekspor
actions-filter = Filter
actions-help = Bantuan
actions-import = Impor
actions-manage = Kelola...
actions-name = Nama:
actions-new = Baru
actions-new-name = Nama Baru:
actions-options = Pengaturan
actions-options-for = Pengaturan Untuk { $val }
actions-preview = Tampilan
actions-rebuild = Rebuild
actions-rename = Rename
actions-rename-deck = Rename Dek
actions-rename-tag = Rename Label
actions-rename-with-parents = Rename dengan Induk
actions-remove-tag = Hapus Label
actions-replay-audio = Replay Audio
actions-reposition = Reposisi
actions-save = Simpan
actions-search = Cari
actions-select = Pilih
actions-shortcut-key = Tombol Shortcut: { $val }
actions-suspend-card = Cabut Kartu
actions-set-due-date = Atur Batas Waktu
actions-answer-card = Kartu Jawaban
actions-unbury-unsuspend = Batal Pendam/Batal Cabut
actions-add-deck = Tambah Dek
actions-add-note = Tambah Catatan
actions-update-tag = Perbarui Label
actions-update-note = Perbarui Catatan
actions-update-card = Perbarui Kartu
actions-update-deck = Perbarui Dek
actions-forget-card = Lupakan Kartu
actions-build-filtered-deck = Bangun Dek
actions-add-notetype = Tambahkan Jeniscatatan
actions-remove-notetype = Hapus Jeniscatatan
actions-update-notetype = Perbarui Jeniscatatan
actions-update-config = Perbarui Konfig
actions-card-info = Info Kartu
actions-previous-card-info = Info Kartu Sebelumnya
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = tindakan ini belum didukung di sistem kamu

## Flags

actions-flag-number = Flag { $number }
actions-flag-red = Merah
actions-flag-orange = Oranye
actions-flag-green = Hijau
actions-flag-blue = Biru
actions-flag-pink = Pink
actions-flag-turquoise = Pirus (Turquoise)
actions-flag-purple = Ungu
actions-set-flag = Atur Flag
