actions-add = जोडें
actions-all-selected = सभी चुने गए
actions-any-selected = कोई भी चयनित
actions-cancel = रद्द करें
actions-choose = चुनें
actions-close = बंद करें
actions-copy = प्रतिलिपि
actions-create-copy = नक़ल बनाएँ
actions-custom-study = मनपसंद अध्ययन
actions-decks = डेक
actions-delete = मिटाएं
actions-export = निर्यात करना
actions-filter = फ़िल्टर करें
actions-help = मदद
actions-import = आयात
actions-manage = प्रबंधन...
actions-name = नाम:
actions-new = नई
actions-new-name = नया नाम:
actions-options = विकल्प
actions-options-for = { $val } के लिए विकल्प
actions-preview = पूर्वावलोकन
actions-rebuild = पुनर्निमाण
actions-rename = नाम बदलें
actions-rename-deck = डेक का नाम बदलें
actions-rename-tag = टैग का नाम बदलें
actions-rename-with-parents = श्रेणी के साथ नाम बदलें
actions-remove-tag = टैग हटाएँ
actions-replay-audio = ऑडियो फिर से खेलना
actions-reposition = पुनर्स्थापन
actions-save = सहेजें
actions-search = खोजें
actions-select = चुनें
actions-shortcut-key = शॉर्टकट कुंजी: { $val }
actions-suspend-card = कार्ड निलंबित करें
actions-set-due-date = नियत दिनांक सेट
actions-answer-card = उत्तर कार्ड
actions-unbury-unsuspend = अनबरी/अनसस्पेंड
actions-add-deck = डेक जोड़ें
actions-add-note = नोट जोड़ें
actions-update-tag = टैग अपडेट करें
actions-update-note = नोट अपडेट करें
actions-update-card = कार्ड अपडेट करें
actions-update-deck = डेक अपडेट करें
actions-forget-card = कार्ड भूल जाओ
actions-build-filtered-deck = डेक का निर्माण
actions-add-notetype = नोटटाइप जोड़ें
actions-remove-notetype = नोटटाइप मिटाएँ
actions-update-notetype = नोटटाइप अपडेट करें
actions-update-config = कॉन्फिग अद्यतन करें
actions-card-info = कार्ड की जानकारी
actions-previous-card-info = पिछले कार्ड की जानकारी
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = यह कार्रवाई फ़िलहाल आपके सिस्टम पर समर्थित नहीं है।

## Flags

actions-flag-number = { $number } झंडा
actions-flag-red = लाल
actions-flag-orange = नारंगी
actions-flag-green = हरा
actions-flag-blue = नीला
actions-flag-pink = गुलाबी
actions-flag-turquoise = फ़िरोज़ा
actions-flag-purple = बैंगनी
actions-set-flag = झंडा सेट करें
