actions-add = Adicionar
actions-blue-flag = Marca azul
actions-cancel = Cancelar
actions-choose = Escolher
actions-close = Fechar
actions-copy = Copiar
actions-custom-study = Estudo Personalizado
actions-decks = Baralhos
actions-delete = Eliminar
actions-export = Exportar
actions-filter = Filtro
actions-green-flag = Marca verde
actions-help = Ajuda
actions-import = Importar
actions-manage = Gerir...
actions-name = Nome:
actions-new = Novos
actions-new-name = Novo nome:
actions-options = Opções
actions-options-for = Opções para { $val }
actions-preview = Pré-visualização
actions-rebuild = Recriar
actions-red-flag = Marca vermelha
actions-rename = Renomear
actions-rename-deck = Renomear Baralho
actions-replay-audio = Repetir Áudio
actions-reposition = Reposicionar
actions-save = Guardar
actions-search = Procurar
actions-shortcut-key = Tecla de Atalho: { $val }
actions-suspend-card = Suspender ficha
