card-stats-added = Adicionado
card-stats-first-review = Primeira Revisão
card-stats-latest-review = Revisão mais recente
card-stats-interval = Intervalo
card-stats-ease = Dificuldade
card-stats-review-count = Revisões
card-stats-lapse-count = Erros
card-stats-average-time = Tempo médio
card-stats-total-time = Tempo Total
card-stats-new-card-position = Posição
card-stats-card-template = Tipo de ficha
card-stats-note-type = Tipo de Nota
card-stats-deck-name = Baralho
card-stats-note-id = ID nota
card-stats-card-id = ID da ficha
card-stats-review-log-rating = Classificação
card-stats-review-log-type = Tipo
card-stats-review-log-date = Data
card-stats-review-log-time-taken = Tempo
card-stats-review-log-type-learn = Aprender
card-stats-review-log-type-review = Revisão
card-stats-review-log-type-relearn = Reaprender
card-stats-review-log-type-filtered = Filtrado
card-stats-review-log-type-rescheduled = Reagendado
