custom-study-cards = fichas
custom-study-cards-from-the-deck = fichas do baralho
custom-study-choose-tags = Escolha etiquetas.
custom-study-custom-study-session = Sessão de Estudo Personalizado
custom-study-due-cards-only = Apenas fichas pendentes
custom-study-increase-todays-new-card-limit = Aumentar o limite de fichas novas para hoje
custom-study-increase-todays-new-card-limit-by = Aumentar o limite de fichas novas para hoje em
custom-study-increase-todays-review-card-limit = Aumentar o limite de fichas a rever hoje
custom-study-increase-todays-review-limit-by = Aumentar o limite de fichas a rever hoje em
custom-study-new-cards-only = Somente fichas novas
custom-study-no-cards-matched-the-criteria-you = Nenhuma ficha corresponde aos seus critérios.
custom-study-ok = Aceptar
custom-study-preview-new-cards = Pré-visualizar fichas novas
custom-study-preview-new-cards-added-in-the = Pré-visualizar fichas novas criadas no/a(s) último/a(s)
custom-study-require-one-or-more-of-these = Deve ter pelo menos uma dessas etiquetas:
custom-study-review-ahead = Antecipar a revisão
custom-study-review-ahead-by = Antecipar a revisão dos próximos
custom-study-review-cards-forgotten-in-last = Rever as fichas esquecidas no/a(s) último/a(s)
custom-study-review-forgotten-cards = Rever as fichas esquecidas
custom-study-select = Selecionar
custom-study-select-tags-to-exclude = Seleccione etiquetas para excluir:
custom-study-selective-study = Estudo Seletivo
custom-study-study-by-card-state-or-tag = Estudar pelo estado da ficha ou etiqueta
