editing-add-media = Adicionar Média
editing-an-error-occurred-while-opening = Ocorreu um erro ao abrir { $val }
editing-attach-picturesaudiovideo-f3 = Anexar imagens/áudio/vídeo (F3)
editing-bold-text-ctrlandb = Texto em negrito (Ctrl+B)
editing-cards = Fichas
editing-change-colour-f8 = Mudar de cor (F8)
editing-cloze-deletion-ctrlandshiftandc = Fechar eliminação (Ctrl+Shift+C)
editing-cut = Recortar
editing-edit-current = Editar Atual
editing-edit-html = Editar HTML
editing-fields = Campos
editing-html-editor = Editor HTML
editing-italic-text-ctrlandi = Texto em itálico (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = Ir para etiquetas com Ctrl+Shift+T
editing-latex-equation = Equação LaTeX
editing-latex-math-env = Matemática LaTeX
editing-mathjax-block = bloco MathJax
editing-mathjax-inline = MathJax em linha
editing-media = Média
editing-paste = Colar
editing-record-audio-f5 = Gravar áudio (F5)
editing-remove-formatting-ctrlandr = Eliminar formatação (Ctrl+R)
editing-set-foreground-colour-f7 = Estabelecer cor do primeiro plano (F7)
editing-show-duplicates = Mostrar Duplicados
editing-subscript-ctrland = Subscrito (Ctrl+=)
editing-superscript-ctrlandand = Índice (Ctrl++)
editing-tags = Etiquetas
editing-to-make-a-cloze-deletion-on = Para omitir palavras numa nota existente, você precisa mudá-la para o tipo Omissão de Palavras, via Editar>Mudar Tipo de Nota.
editing-underline-text-ctrlandu = Sublinhar texto (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = Atenção, exclusões cloze não funcionarão até que você mude o tipo no topo de Cloze
