notetypes-front-field = Frente
notetypes-back-field = Verso
notetypes-add-reverse-field = Adicionar invertido
notetypes-text-field = Texto
notetypes-basic-name = Básico
notetypes-basic-reversed-name = Básico (e ficha invertida)
notetypes-basic-optional-reversed-name = Básico (ficha invertida opcional)
notetypes-cloze-name = Omissão de Palavras
notetypes-basic-type-answer-name = Básico (digite a resposta)
notetypes-card-2-name = Ficha 2
notetypes-card-1-name = Ficha 1
notetypes-add = Adicionar: { $val }
notetypes-add-note-type = Adicionar Tipo de Nota
notetypes-cards = Fichas...
notetypes-clone = Clonar: { $val }
notetypes-copy = { $val } cópia
notetypes-create-scalable-images-with-dvisvgm = Criar imagens escaláveis com dvisvgm
notetypes-delete-this-note-type-and-all = Eliminar este tipo de nota e todas as suas fichas?
notetypes-delete-this-unused-note-type = Eliminar este tipo de nota não utilizado?
notetypes-fields = Campos...
notetypes-footer = Rodapé
notetypes-header = Cabeçalho
notetypes-note-types = Tipos de Nota
notetypes-options = Opções...
notetypes-please-add-another-note-type-first = Por favor, crie outro tipo de nota primeiro.
notetypes-type = Tipo
