preferences-automatically-sync-on-profile-openclose = Sincronizar automaticamente ao abrir/fechar perfil de usuário
preferences-backups = Cópias de segurança
preferences-backups2 = cópias de segurança
preferences-backupsanki-will-create-a-backup-of = <b>Backups</b><br>Anki criará uma cópia de segurança da sua coleção a cada vez que ela for fechada ou sincronizada.
preferences-basic = Básico
preferences-change-deck-depending-on-note-type = Mudar baralho dependendo do tipo de nota
preferences-hours-past-midnight = horas depois da meia-noite
preferences-interface-language = Idioma da Interface:
preferences-keep = Manter
preferences-learn-ahead-limit = Aprender além do limite
preferences-mins = mins.
preferences-network = Rede
preferences-next-day-starts-at = Novo dia começa às
preferences-note-media-is-not-backed-up = Nota: A média não tem backup. Por favor, copie periodicamente a sua pasta Anki por segurança.
preferences-on-next-sync-force-changes-in = Na próxima sincronização, obrigar mudanças numa direção.
preferences-paste-clipboard-images-as-png = Colar imagens da área de transferência como PNG
preferences-please-restart-anki-to-complete-language = Por favor reinicie o Anki para completar a alteração de idioma.
preferences-preferences = Preferências
preferences-scheduling = Reagendar
preferences-show-next-review-time-above-answer = Mostrar tempo da próxima revisão acima dos botões de resposta
preferences-show-remaining-card-count-during-review = Mostrar contador de fichas restantes durante a revisão
preferences-some-settings-will-take-effect-after = Algumas configurações só surtirão efeito quando você reiniciar o Anki
preferences-synchronisation = <b>Sincronização</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sincronização</b><br> Não ativada agora; clique no botão de sincronização na janela principal para ativá-la.
preferences-synchronize-audio-and-images-too = Sincronizar áudios e imagens também
preferences-timebox-time-limit = Tempo limite
preferences-when-adding-default-to-current-deck = Ao criar, o baralho atual será o padrão
