actions-add = Afegeix
actions-all-selected = Tot seleccionat
actions-any-selected = Qualsevol seleccionat
actions-cancel = Anuŀla
actions-choose = Tria
actions-close = Tanca
actions-copy = Copia
actions-create-copy = Crea'n una còpia
actions-custom-study = Estudi personalitzat
actions-decks = Baralles
actions-decrement-value = Disminueix-ne el valor
actions-delete = Suprimeix
actions-export = Exporta
actions-filter = Filtra
actions-help = Ajuda
actions-increment-value = Augmenta'n el valor
actions-import = Importa
actions-manage = Gestiona…
actions-name = Nom:
actions-new = Noves
actions-new-name = Nom nou:
actions-options = Opcions
actions-options-for = Opcions per a { $val }
actions-preview = Previsualització
actions-rebuild = Reconstrueix
actions-rename = Reanomena
actions-rename-deck = Reanomena la baralla
actions-rename-tag = Reanomena l'etiqueta
actions-rename-with-parents = Reanomena amb els superiors
actions-remove-tag = Suprimeix l'etiqueta
actions-replay-audio = Reprodueix-ne el so
actions-reposition = Reposiciona
actions-save = Guarda
actions-search = Cerca
actions-select = Selecciona
actions-shortcut-key = Tecla de drecera: { $val }
actions-suspend-card = Suspèn la targeta
actions-set-due-date = Defineix una data de repàs
actions-answer-card = Respon la targeta
actions-unbury-unsuspend = Desenterra/anul·la la suspensió
actions-add-deck = Afegeix una baralla
actions-add-note = Afegeix una nota
actions-update-tag = Actualitza l'etiqueta
actions-update-note = Actualitza la nota
actions-update-card = Actualitza la targeta
actions-update-deck = Actualitza la baralla
actions-forget-card = Oblida la targeta
actions-build-filtered-deck = Crea una baralla
actions-add-notetype = Afegeix un tipus de nota
actions-remove-notetype = Suprimeix el tipus de nota
actions-update-notetype = Actualtza el tipus de nota
actions-update-config = Actualitza'n la configuració
actions-card-info = Informació de la targeta
actions-previous-card-info = Informació de la targeta anterior
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }…
actions-currently-unsupported = El vostre sistema no és compatible amb aquesta acció.

## Flags

actions-flag-number = Senyal { $number }
actions-flag-red = Roig
actions-flag-orange = Taronja
actions-flag-green = Verd
actions-flag-blue = Blau
actions-flag-pink = Rosa
actions-flag-turquoise = Turquesa
actions-flag-purple = Morat
actions-set-flag = Selecciona un senyal
