editing-actual-size = Activa la mida real
editing-add-media = Afegeix fitxers multimèdia
editing-align-left = Alinea a l'esquerra
editing-align-right = Alinea a la dreta
editing-an-error-occurred-while-opening = S'ha produït un error en obrir { $val }
editing-attach-picturesaudiovideo = Afegeix imatges, so o vídeo
editing-bold-text = Text en negreta
editing-cards = Targetes
editing-center = Centrar
editing-change-color = Canvia el color
editing-cloze-deletion = Text amb buits (nova targeta)
editing-cloze-deletion-repeat = Text amb buits (mateixa targeta)
editing-couldnt-record-audio-have-you-installed = No s'ha pogut enregistrar el so. Heu instal·lat «lame»?
editing-customize-card-templates = Personalitza les plantilles de targeta
editing-customize-fields = Personalitza els camps
editing-cut = Talla
editing-double-click-image = feu doble clic en la imatge
editing-double-click-to-expand = (feu doble clic per a expandir)
editing-double-click-to-collapse = feu doble clic per a reduir
editing-edit-current = Edita l'actual
editing-edit-html = Edita l'HTML
editing-fields = Camps
editing-float-left = Flotant a l'esquerra
editing-float-right = Flotant a la dreta
editing-float-none = No flotant
editing-indent = Augmenta el sagnat
editing-italic-text = Text en cursiva
editing-jump-to-tags-with-ctrlandshiftandt = Salta a les etiquetes amb Ctrl+Shift+T
editing-justify = Justifica
editing-latex = LaTeX
editing-latex-equation = Equació LaTeX
editing-latex-math-env = Entorn matemàtic LaTeX
editing-mathjax-block = Bloc de MathJacx
editing-mathjax-chemistry = Química MathJax
editing-mathjax-inline = MathJacx en línia
editing-mathjax-placeholder = Premeu { $accept } per a acceptar i { $newline } per a afegir una nova línia.
editing-media = Multimèdia
editing-ordered-list = Llista ordenada
editing-outdent = Redueix el sagnat
editing-paste = Enganxa
editing-record-audio = Enregistra un so
editing-remove-formatting = Suprimeix el format
editing-restore-original-size = Restaura la mida original
editing-select-remove-formatting = Seleccioneu el format que voleu suprimir
editing-show-duplicates = Mostra'n els duplicats
editing-subscript = Subíndex
editing-superscript = Superíndex
editing-tags = Etiquetes
editing-tags-add = Afegeix una etiqueta
editing-tags-copy = Copia les etiquetes
editing-tags-remove = Suprimeix les etiquetes
editing-tags-select-all = Selecciona totes les etiquetes
editing-text-color = Color del text
editing-text-highlight-color = Color de ressaltat del texto
editing-to-make-a-cloze-deletion-on = Si voleu crear buits en una nota existent, primer heu de canviar a un tipus de nota amb buits des del menú «Edita > Canvia el tipus de nota».
editing-toggle-html-editor = Activa l'editor HTML
editing-toggle-visual-editor = Mostra l'editor visual
editing-toggle-sticky = Activa l'ancoratge del text
editing-expand = Expandeix
editing-collapse = Redueix
editing-expand-field = Expandeix el camp
editing-collapse-field = Redueix el camp
editing-underline-text = Subratlla el text
editing-unordered-list = Llista desordenada
editing-warning-cloze-deletions-will-not-work = Aneu amb compte: els buits no funcionaran fins que canvieu el tipus de nota a «Text amb buits».
editing-mathjax-preview = Previsualització MathJax
editing-shrink-images = Redueix les imatges
editing-close-html-tags = Tanca les etiquetes HTML automàticament

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Editor HTML
