preferences-automatically-sync-on-profile-openclose = Sincronitza automàticament en obrir o tancar un perfil
preferences-backups = Còpies de seguretat
preferences-change-deck-depending-on-note-type = Canvia la baralla en funció del tipus de nota
preferences-changes-will-take-effect-when-you = Els canvis s'aplicaran quan reinicieu Anki.
preferences-hours-past-midnight = hora/hores passada la mitjanit
preferences-language = Llengua
preferences-interrupt-current-audio-when-answering = Interromp el so actual en respondre
preferences-learn-ahead-limit = Límit d'estudi per endavant
preferences-mins = minut(s)
preferences-network = Xarxa
preferences-next-day-starts-at = El dia següent comença a les
preferences-media-is-not-backed-up = No heu fet cap còpia de seguretat dels fitxers multimèdia. Per motius de seguretat, feu una còpia de la carpeta d'Anki de manera periòdica.
preferences-on-next-sync-force-changes-in = En la pròxima sincronització, força els canvis en una direcció
preferences-paste-clipboard-images-as-png = Enganxa les imatges del portapapers com a PNG
preferences-paste-without-shift-key-strips-formatting = Enganxa sense prémer la tecla de majúscules per a eliminar-ne el format
preferences-periodically-sync-media = Sincronitza els fitxers multimèdia periòdicament
preferences-please-restart-anki-to-complete-language = Reinicieu Anki per a completar el canvi d'idioma.
preferences-preferences = Preferències
preferences-scheduling = Planificació
preferences-show-learning-cards-with-larger-steps = Mostra les targetes que estic aprenent amb passos més grans abans dels repassos
preferences-show-next-review-time-above-answer = Mostra l'interval de repàs pròxim sobre dels botons de resposta
preferences-show-play-buttons-on-cards-with = Mostra els botons de reproducció en les targetes que tenen so
preferences-show-remaining-card-count = Mostra el nombre de targetes restants
preferences-some-settings-will-take-effect-after = Alguns canvis no s'aplicaran fins que reinicieu Anki.
preferences-tab-synchronisation = Sincronització
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sincronització</b><br> La sincronització està desactivada. Feu clic en el botó de sincronització de la pantalla principal per a activar-la.
preferences-synchronize-audio-and-images-too = Sincronitza també els sons i les imatges
preferences-timebox-time-limit = Límit de sessió d'estudi
preferences-user-interface-size = Mida de l'interfície d'usuari
preferences-when-adding-default-to-current-deck = Afegeix la baralla actual per defecte
preferences-you-can-restore-backups-via-fileswitch = Podeu restaurar còpies de seguretat des del menú Fitxer → Canviar de perfil.
preferences-legacy-timezone-handling = Gestió de zones horàries antiga (tot i que té errors, és necessària si feu servir AnkiDroid 2.14 o inferior)
preferences-default-search-text = Text de cerca per defecte
preferences-default-search-text-example = per exemple: 'deck:current'
preferences-theme = Tema
preferences-theme-follow-system = segons el sistema
preferences-theme-light = clar
preferences-theme-dark = fosc
preferences-v3-scheduler = V3 del planificador
preferences-ignore-accents-in-search = Ignora els accents quan cerquis (més lent)
preferences-backup-explanation =
    Anki fa una còpia de seguretat periòdica de la vostra col·lecció. Quan les còpies compleixin 2 dies,
    Anki començarà a eliminar-ne algunes per tal d'alliberar espai en el disc.
preferences-daily-backups = Còpies de seguretat diàries que cal mantenir:
preferences-weekly-backups = Còpies de seguretat setmanals que cal mantenir:
preferences-monthly-backups = Còpies de seguretat mensuals que cal mantenir:
preferences-minutes-between-backups = Minuts que ha d'haver-hi entre còpies de seguretat automàtiques:
preferences-reduce-motion = Redueix el moviment
preferences-reduce-motion-tooltip = Desactiva les animacions i les transicions de l'interfície d'usuari.
preferences-custom-sync-url = Servidor de sincronització propi
preferences-custom-sync-url-disclaimer = Si sou un usuari avançat, consulteu el manual.
preferences-hide-top-bar-during-review = Amaga la barra superior durant els repassos
preferences-hide-bottom-bar-during-review = Amaga la barra inferior durant els repassos
preferences-always = Sempre
preferences-full-screen-only = Només a pantalla completa
preferences-appearance = Aparença
preferences-general = General
preferences-style = Estil
preferences-review = Repassar
preferences-distractions = Distraccions
preferences-minimalist-mode = Mode minimalista
preferences-editing = Edició
preferences-browsing = Navegació
preferences-default-deck = Baralla per defecte
preferences-account = Compte d'AnkiWeb
preferences-note = Nota
preferences-scheduler = Planificador
preferences-user-interface = Interfície d'usuari
preferences-import-export = Importar/Exportar
preferences-network-timeout = Temps d’espera de la xarxa
preferences-reset-window-sizes = Reestableix la mida de les finestres
preferences-reset-window-sizes-complete = S’ha reestablert la mida i la posició de les finestres.

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = Bàsica
preferences-reviewer = Revisor
preferences-media = Multimèdia
