actions-add = 添加
actions-all-selected = 所有选中的
actions-any-selected = 任何选中的
actions-cancel = 取消
actions-choose = 选择
actions-close = 关闭
actions-copy = 复制
actions-create-copy = 创建副本
actions-custom-study = 自定义学习
actions-decks = 牌组
actions-decrement-value = 递减值
actions-delete = 删除
actions-export = 导出
actions-filter = 筛选
actions-help = 帮助
actions-increment-value = 递增值
actions-import = 导入
actions-manage = 管理...
actions-name = 名称：
actions-new = 未学习
actions-new-name = 新名称：
actions-options = 选项
actions-options-for = { $val } 学习计划
actions-preview = 预览
actions-rebuild = 重建
actions-rename = 重命名
actions-rename-deck = 重命名牌组
actions-rename-tag = 重命名标签
actions-rename-with-parents = 重命名（包括父级）
actions-remove-tag = 删除标签
actions-replay-audio = 重播音频
actions-reposition = 重排位置
actions-save = 保存
actions-search = 搜索
actions-select = 选择
actions-shortcut-key = 快捷键：{ $val }
actions-suspend-card = 暂停卡片
actions-set-due-date = 设置到期时间
actions-answer-card = 回答卡片
actions-unbury-unsuspend = 取消搁置/取消暂停
actions-add-deck = 添加牌组
actions-add-note = 添加笔记
actions-update-tag = 更新标签
actions-update-note = 更新笔记
actions-update-card = 更新卡片
actions-update-deck = 更新牌组
actions-forget-card = 忘记卡片
actions-build-filtered-deck = 建立牌组
actions-add-notetype = 添加笔记模板
actions-remove-notetype = 删除笔记模板
actions-update-notetype = 更新笔记模板
actions-update-config = 更新设置
actions-card-info = 卡片信息
actions-previous-card-info = 上一张卡片信息
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = 当前系统不支持此操作。

## Flags

actions-flag-number = 旗标{ $number }
actions-flag-red = 红色
actions-flag-orange = 橙色
actions-flag-green = 绿色
actions-flag-blue = 蓝色
actions-flag-pink = 粉色
actions-flag-turquoise = 青色
actions-flag-purple = 紫色
actions-set-flag = 设置旗标
