editing-actual-size = 打开/关闭以实际尺寸展示
editing-add-media = 添加媒体文件
editing-align-left = 左对齐
editing-align-right = 右对齐
editing-an-error-occurred-while-opening = 打开{ $val }时发生错误
editing-attach-picturesaudiovideo = 附加图片/音频/视频
editing-bold-text = 粗体
editing-cards = 卡片
editing-center = 居中对齐
editing-change-color = 更改颜色
editing-cloze-deletion = 设置空格（新卡片）
editing-cloze-deletion-repeat = 设置空格（同卡片）
editing-couldnt-record-audio-have-you-installed = 无法录制音频。请检查是否已安装“lame”？
editing-customize-card-templates = 自定义卡片内容模板
editing-customize-fields = 自定义字段
editing-cut = 剪切
editing-double-click-image = 双击图片
editing-double-click-to-expand = 双击展开
editing-double-click-to-collapse = 双击折叠
editing-edit-current = 编辑当前
editing-edit-html = 编辑HTML
editing-fields = 字段
editing-float-left = 向左浮动
editing-float-right = 向右浮动
editing-float-none = 不浮动
editing-indent = 增加缩进
editing-italic-text = 斜体
editing-jump-to-tags-with-ctrlandshiftandt = 使用Ctrl+Shift+T跳到标签
editing-justify = 两端对齐
editing-latex = LaTeX
editing-latex-equation = LaTeX公式
editing-latex-math-env = LaTeX数学环境
editing-mathjax-block = MathJax块
editing-mathjax-chemistry = MathJax化学式
editing-mathjax-inline = MathJax行内式
editing-mathjax-placeholder = 按{ $accept }接受，按{ $newline }换行。
editing-media = 媒体
editing-ordered-list = 有序列表
editing-outdent = 减少缩进
editing-paste = 粘贴
editing-record-audio = 录制音频
editing-remove-formatting = 清除格式
editing-restore-original-size = 恢复原始大小
editing-select-remove-formatting = 选择要清除的格式
editing-show-duplicates = 查看重复的卡片
editing-subscript = 下标
editing-superscript = 上标
editing-tags = 标签
editing-tags-add = 添加标签
editing-tags-copy = 复制标签
editing-tags-remove = 删除标签
editing-tags-select-all = 全选标签
editing-text-color = 文字颜色
editing-text-highlight-color = 高亮文本
editing-to-make-a-cloze-deletion-on = 若要在现有笔记上设置空格，请通过「笔记」>「更改笔记模板」将笔记模板修改为填空题模板。
editing-toggle-html-editor = 打开/关闭 HTML 编辑器
editing-toggle-visual-editor = 打开/关闭可视化编辑器
editing-toggle-sticky = 固定/取消固定
editing-expand-field = 拓展字段
editing-collapse-field = 折叠字段
editing-underline-text = 下划线
editing-unordered-list = 无序列表
editing-warning-cloze-deletions-will-not-work = 警告，在将笔记模板修改为填空题模板前，设置的空格将不会生效。
editing-mathjax-preview = MathJax 预览
editing-shrink-images = 缩小图像
editing-close-html-tags = 自闭合HTML标签

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML编辑器
