preferences-automatically-sync-on-profile-openclose = 账户启动和关闭时自动同步
preferences-backups = 备份
preferences-change-deck-depending-on-note-type = 添加卡片时，根据笔记模板自动选择牌组
preferences-changes-will-take-effect-when-you = 变更将在重启Anki后生效。
preferences-hours-past-midnight = 时
preferences-language = 语言
preferences-interrupt-current-audio-when-answering = 回答卡片时停止播放当前音频
preferences-learn-ahead-limit = 提前学习的上限
preferences-mins = 分钟
preferences-network = 网络
preferences-next-day-starts-at = 新的一天始于
preferences-media-is-not-backed-up = 媒体文件未被备份，为确保安全请定期备份Anki文件夹.
preferences-on-next-sync-force-changes-in = 下次同步时，强制单向覆盖
preferences-paste-clipboard-images-as-png = 粘贴图片为PNG格式
preferences-paste-without-shift-key-strips-formatting = 粘贴时未按住Shift键，则清除文本格式
preferences-periodically-sync-media = 定期同步媒体文件
preferences-please-restart-anki-to-complete-language = 请重启 Anki 以完成语言切换
preferences-preferences = 设置
preferences-scheduling = 计划
preferences-show-learning-cards-with-larger-steps = 在复习前展示步伐更长且处于学习中的卡牌
preferences-show-next-review-time-above-answer = 在回答按钮上显示下次复习时间
preferences-show-play-buttons-on-cards-with = 卡片上显示音频播放按钮
preferences-show-remaining-card-count = 显示剩余卡片数量
preferences-some-settings-will-take-effect-after = 部分设置将在重启Anki后生效
preferences-tab-synchronisation = 同步
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>同步</b><br> 尚未启用，点击主界面的同步按钮启用。
preferences-synchronize-audio-and-images-too = 同时同步音频和图像
preferences-timebox-time-limit = 提醒指定时间内的学习卡片数
preferences-user-interface-size = 界面缩放
preferences-when-adding-default-to-current-deck = 添加卡片时，默认加入当前牌组
preferences-you-can-restore-backups-via-fileswitch = 可通过「文件」>「切换账户」恢复备份。
preferences-legacy-timezone-handling = 旧版时区处理方式（有问题，但 AnkiDroid 2.14 及以下版本必须使用）
preferences-default-search-text = 默认搜索文本
preferences-default-search-text-example = 例如：'deck:current '
preferences-theme = 主题
preferences-theme-follow-system = 跟随系统
preferences-theme-light = 浅色
preferences-theme-dark = 深色
preferences-v3-scheduler = 启用 V3 排程算法
preferences-ignore-accents-in-search = 搜索时忽略重音（速度较慢）
preferences-backup-explanation = Anki将自动备份您的集合。但为节省磁盘空间，将自动删除超过2天的备份。
preferences-daily-backups = 要保留的每日备份数量：
preferences-weekly-backups = 要保留的每周备份数量：
preferences-monthly-backups = 要保留的每月备份数量：
preferences-minutes-between-backups = 自动备份的间隔时间(分钟)：
preferences-reduce-motion = 减少动效
preferences-reduce-motion-tooltip = 禁用用户界面的所有动画和过渡。
preferences-custom-sync-url = 私人同步服务器
preferences-custom-sync-url-disclaimer = 供进阶用户使用—详情请参阅使用手册
preferences-hide-top-bar-during-review = 复习时隐藏顶栏
preferences-hide-bottom-bar-during-review = 复习时隐藏底栏
preferences-always = 总是
preferences-full-screen-only = 仅全屏
preferences-appearance = 显示
preferences-general = 通用
preferences-style = 风格
preferences-review = 复习
preferences-distractions = 专心
preferences-minimalist-mode = 极简模式
preferences-editing = 编辑
preferences-browsing = 浏览
preferences-default-deck = 默认牌组
preferences-account = AnkiWeb账户
preferences-note = 注意
preferences-scheduler = 排程
preferences-user-interface = 用户界面
preferences-import-export = 导入/导出
preferences-network-timeout = 网络超时

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = 基本
preferences-media = 媒体
