actions-add = Tilføj
actions-all-selected = Alle markeret
actions-any-selected = Alle markeret
actions-cancel = Afbryd
actions-choose = Vælg
actions-close = Luk
actions-copy = Kopier
actions-create-copy = Skab kopi
actions-custom-study = Brugerdefineret studie
actions-decks = Alle kortsæt
actions-delete = Slet
actions-export = Eksportér
actions-filter = Filtrér
actions-help = Hjælp
actions-import = Importér
actions-manage = Håndter...
actions-name = Navn:
actions-new = Nye
actions-new-name = Nyt navn:
actions-options = Indstillinger
actions-options-for = Muligheder for { $val }
actions-preview = Forhåndsvisning
actions-rebuild = Genopbyg
actions-rename = Omdøb
actions-rename-deck = Omdøg kortsæt
actions-rename-tag = Omdøb tag
actions-rename-with-parents = Omdøb med forældre
actions-remove-tag = Fjern tag
actions-replay-audio = Genafspil lyd
actions-reposition = Repositioner
actions-save = Gem
actions-search = Søg
actions-select = Vælg
actions-shortcut-key = Genvej: { $val }
actions-suspend-card = Suspender kort
actions-set-due-date = Sæt en sidste dato
actions-answer-card = Svar kort
actions-unbury-unsuspend = Grav op/fjern suspendering
actions-add-deck = Tilføj kortbunke
actions-add-note = Tilføj note
actions-update-tag = Opdater Tag
actions-update-note = Opdater Note
actions-update-card = Opdater Kort
actions-update-deck = Opdater Kortbunke
actions-forget-card = Glem kort
actions-build-filtered-deck = Byg kortbunke
actions-add-notetype = Tilføj note-type
actions-remove-notetype = Fjern note-type
actions-update-notetype = Opdatér note-type
actions-update-config = Opdatér konfiguration
actions-card-info = Kortinformation
actions-previous-card-info = Forrige korts information
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $handling }...
actions-currently-unsupported = Den her handling er endnu ikke understøttet af dit system.

## Flags

actions-flag-number = Flag { $nummer }
actions-flag-red = Rød
actions-flag-orange = Orange
actions-flag-green = Grøn
actions-flag-blue = Blå
actions-flag-pink = Lyserød
actions-flag-turquoise = Turkis
actions-flag-purple = Lila
actions-set-flag = Sæt flag
