actions-add = ചേര്‍ക്കുക
actions-all-selected = മൊത്തം തിരഞ്ഞെടുത്തത്
actions-any-selected = തിരഞ്ഞെടുത്തവ
actions-cancel = റദ്ദാക്കുക
actions-choose = തിരഞ്ഞെടുക്കുക
actions-close = അവസാനിപ്പിക്കുക
actions-copy = പകര്‍ത്തുക
actions-custom-study = ഇഷ്‌ടാനുസൃത പഠനം
actions-decks = ഡെക്കുകൾ
actions-delete = ഇല്ലാതാക്കുക
actions-export = കയറ്റുമതി
actions-filter = ഫിൽറ്റർ ചെയ്യുക
actions-help = സഹായം
actions-import = ഇറക്കുമതി
actions-manage = നിയന്ത്രിക്കുക
actions-name = പേര്:
actions-new = പുതിയത്
actions-new-name = പുതിയ പേര്:
actions-options = ഐച്ഛികങ്ങൾ
actions-options-for = { $val }-നുള്ള ഓപ്ഷനുകൾ
actions-preview = തിരനോട്ടം
actions-rebuild = വീണ്ടും പണിയുക
actions-rename = പേരു മാറ്റുക
actions-rename-deck = ഡെക്കിന്റെ പേര് മാറ്റുക
actions-rename-tag = ടാഗ് പുനർനാമകരണം
actions-remove-tag = ഡെക്ക് പുനർനാമകരണം
actions-replay-audio = ഓഡിയോ വീണ്ടും പ്ലേ ചെയ്യുക
actions-reposition = സ്ഥാനം മാറ്റുക
actions-save = സംരക്ഷിക്കുക
actions-search = തിരയുക
actions-select = തിരഞ്ഞെടുക്കുക
actions-shortcut-key = കുറുക്കുവഴി കീ: { $val }
actions-suspend-card = കാർഡ് താൽക്കാലികമായി നിർത്തുക
actions-set-due-date = നിശ്ചിത തീയതി സജ്ജമാക്കുക
actions-forget = മറക്കുക
actions-answer-card = ഉത്തര കാർഡ്
actions-unbury-unsuspend = അൺബറി / അൺസെസ്പെൻഡ്
actions-add-deck = ഡെക്ക് ചേർക്കുക
actions-add-note = കുറിപ്പ് ചേർക്കുക
actions-update-tag = ടാഗ് പുതുക്കുക
actions-update-note = കുറിപ്പ് പുതുക്കുക
actions-update-card = കാർഡ് പുതുക്കുക
actions-update-deck = ഡെക്ക് പുതുക്കുക
actions-forget-card = കാർഡ് മറക്കുക
actions-build-filtered-deck = ഡെക്ക് നിർമ്മിക്കുക
actions-expand-collapse = വികസിപ്പിക്കുക/ചുരുക്കുക
actions-add-notetype = കുറിപ്പ് തരം ചേർക്കുക
actions-remove-notetype = കുറിപ്പ് തരം നീക്കം ചെയ്യുക
actions-update-notetype = കുറിപ്പ് തരം പുതുക്കുക
actions-update-config = കോൺഫിഗറേഷൻ പുതുക്കുക
actions-card-info = കാർഡ് വിവരം

## Flags

actions-flag-number = ഫ്ലാഗുചെയ്യുക { $number }
actions-flag-red = ചുവപ്പ്
actions-flag-orange = ഓറഞ്ച്
actions-flag-green = പച്ച
actions-flag-blue = നീല
actions-flag-pink = പിങ്ക്
actions-flag-turquoise = നീലരത്നം
actions-flag-purple = പര്‍പ്പിള്‍
actions-set-flag = ഫ്ലാഗ് സജ്ജമാക്കുക
