card-stats-added = ചേർത്തു
card-stats-first-review = ആദ്യ അവലോകനം
card-stats-latest-review = ഏറ്റവും പുതിയ അവലോകനം
card-stats-interval = ഇടവേള
card-stats-ease = അനായാസം
card-stats-review-count = അവലോകനങ്ങൾ
card-stats-lapse-count = വീഴ്ചകൾ
card-stats-average-time = ശരാശരി സമയം
card-stats-total-time = ആകെ സമയം
card-stats-new-card-position = സ്ഥാനം
card-stats-card-template = കാർഡ് തരം
card-stats-note-type = കുറിപ്പ് തരം
card-stats-deck-name = ഡെക്ക്
card-stats-note-id = കുറിപ്പ് ഐഡി
card-stats-card-id = കാർഡ് ഐഡി
card-stats-review-log-rating = റേറ്റിംഗ്
card-stats-review-log-type = തരം
card-stats-review-log-date = തീയതി
card-stats-review-log-time-taken = സമയം
card-stats-review-log-type-learn = പഠിക്കുക
card-stats-review-log-type-review = അവലോകനം
card-stats-review-log-type-relearn = വീണ്ടും പഠിക്കുക
card-stats-review-log-type-filtered = ഫിൽട്ടർ ചെയ്‌തത്
card-stats-review-log-type-manual = കരകൃതമായി
