preferences-automatically-sync-on-profile-openclose = പ്രൊഫൈൽ തുറക്കുമ്പോഴും അടയ്ക്കുമ്പോഴും യാന്ത്രികമായി സമന്വയിപ്പിക്കുക
preferences-backups = ബാക്കപ്പുകൾ
preferences-backups2 = ബാക്കപ്പുകൾ
preferences-backupsanki-will-create-a-backup-of = <html><head/><body><p><span style=" font-weight:600;">ബാക്കപ്പുകൾ</span><br/>നിങ്ങളുടെ ശേഖരം അടയ്‌ക്കുമ്പോഴെല്ലാം Anki ഒരു ബാക്കപ്പ് സൃഷ്‌ടിക്കും.</p></body></html>
preferences-basic = അടിസ്ഥാനം
preferences-change-deck-depending-on-note-type = കുറിപ്പ് തരം അനുസരിച്ച് ഡെക്ക് മാറ്റുക
preferences-changes-will-take-effect-when-you = നിങ്ങൾ Anki പുനരാരംഭിക്കുമ്പോൾ മാറ്റങ്ങൾ പ്രാബല്യത്തിൽ വരും.
preferences-hours-past-midnight = അർദ്ധരാത്രി കഴിഞ്ഞ മണിക്കൂറുകൾ
preferences-interface-language = ഇന്റർഫേസ് ഭാഷ:
preferences-interrupt-current-audio-when-answering = ഉത്തരം നൽകുമ്പോൾ നിലവിലെ ഓഡിയോ തടസ്സപ്പെടുത്തുക
preferences-keep = നിലനിർത്തുക
preferences-learn-ahead-limit = മുന്നോട്ടു പഠിക്കുന്നതിനുള്ള പരിധി
preferences-mins = മിനിറ്റുകള്‍
preferences-network = നെറ്റ്‌വർക്ക്
preferences-next-day-starts-at = അടുത്ത ദിവസം ആരംഭിക്കുന്നത്
preferences-night-mode = രാത്രി മോഡ്
preferences-note-media-is-not-backed-up = കുറിപ്പ്: മീഡിയ ബാക്കപ്പ് ചെയ്തിട്ടില്ല. സുരക്ഷിതമായിരിക്കാൻ നിങ്ങളുടെ Anki ഫോൾഡറിന്റെ ആനുകാലിക ബാക്കപ്പ് സൃഷ്ടിക്കുക.
preferences-on-next-sync-force-changes-in = അടുത്ത സമന്വയത്തിൽ, ഒരു ദിശയിൽ മാറ്റങ്ങൾ വരുത്തുക
preferences-paste-clipboard-images-as-png = ക്ലിപ്പ്ബോർഡ് ചിത്രങ്ങൾ PNG ആയി പതിക്കുക
preferences-paste-without-shift-key-strips-formatting = ഷിഫ്റ്റ് കീ സ്ട്രിപ്പുകളുടെ ഫോർമാറ്റിംഗ് ഇല്ലാതെ പതിക്കുക
preferences-periodically-sync-media = ആനുകാലികമായി മീഡിയ സമന്വയിപ്പിക്കുക
preferences-please-restart-anki-to-complete-language = ഭാഷാ മാറ്റം പൂർത്തിയാക്കാൻ ദയവായി Anki പുനരാരംഭിക്കുക.
preferences-preferences = മുൻഗണനകൾ
preferences-scheduling = ഷെഡ്യൂളിംഗ്
preferences-show-learning-cards-with-larger-steps = അവലോകനങ്ങൾക്ക് മുമ്പായി വലിയ ഘട്ടങ്ങളോടെ ഉള്ള പഠന കാർഡുകൾ കാണിക്കുക
preferences-show-next-review-time-above-answer = ഉത്തര ബട്ടണുകൾക്ക് മുകളിൽ അടുത്ത അവലോകന സമയം കാണിക്കുക
preferences-show-play-buttons-on-cards-with = ഓഡിയോ ഉള്ള കാർഡുകളിൽ പ്ലേ ബട്ടണുകൾ കാണിക്കുക
preferences-show-remaining-card-count-during-review = അവലോകന സമയത്ത് ശേഷിക്കുന്ന കാർഡുകളുടെ എണ്ണം കാണിക്കുക
preferences-some-settings-will-take-effect-after = നിങ്ങൾ Anki പുനരാരംഭിച്ചതിനുശേഷം ചില ക്രമീകരണങ്ങൾ പ്രാബല്യത്തിൽ വരും.
preferences-synchronisation = <b>സമന്വയം</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>സമന്വയം</b><br>നിലവിൽ പ്രവർത്തനക്ഷമമാക്കിയിട്ടില്ല; പ്രവർത്തനക്ഷമമാക്കുന്നതിന് പ്രധാന വിൻഡോയിലെ സമന്വയ ബട്ടൺ ക്ലിക്കുചെയ്യുക.
preferences-synchronize-audio-and-images-too = ഓഡിയോയും ചിത്രങ്ങളും സമന്വയിപ്പിക്കുക
preferences-this-will-reset-any-cards-in = ഇത് പഠനത്തിലെ ഏത് കാർഡുകളും പുനസജ്ജമാക്കും, ഫിൽട്ടർ ചെയ്ത ഡെക്കുകൾ മായ്‌ക്കുകയും ഷെഡ്യൂളർ പതിപ്പ് മാറ്റുകയും ചെയ്യും. മുന്നോട്ട് പോകണോ?
preferences-timebox-time-limit = ടൈംബോക്സ് സമയ പരിധി
preferences-user-interface-size = ഉപയോക്തൃ ഇന്റർഫേസ് വലുപ്പം
preferences-when-adding-default-to-current-deck = ചേർക്കുമ്പോൾ, നിലവിലെ ഡെക്കിലേക്ക് സ്ഥിരസ്ഥിതി ചെയ്യുക
preferences-you-can-restore-backups-via-fileswitch = ഫയൽ> സ്വിച്ച് പ്രൊഫൈൽ വഴി നിങ്ങൾക്ക് ബാക്കപ്പുകൾ പുനസ്ഥാപിക്കാൻ കഴിയും.
preferences-legacy-timezone-handling = ലെഗസി സമയമേഖല കൈകാര്യം ചെയ്യൽ (പ്രശ്ന സുലഭം, പക്ഷേ Ankidroid-നു ആവശ്യമാണ് <= 2.14)
preferences-default-search-text = സ്ഥിരസ്ഥിതിയിലുള്ള തിരച്ചിൽ വാചകം
preferences-default-search-text-example = ഉദാ. 'ഡെക്ക്: നിലവിലുള്ളത്'
