adding-add-shortcut-ctrlandenter = 新增（快速鍵：Ctrl+Enter）
adding-added = 已新增
adding-close-and-lose-current-input = 關閉並捨棄當前輸入？
adding-edit = 編輯 "{ $val }"
adding-history = 歷史記錄
adding-note-deleted = （已刪除筆記）
adding-shortcut = 快速鍵：{ $val }
adding-the-first-field-is-empty = 第一個欄位是空的。
adding-you-have-a-cloze-deletion-note = 正在使用克漏字筆記類型，但尚未加入空格。繼續？
adding-cloze-outside-cloze-notetype = 只能在克漏字筆記類型中建立空格。
adding-cloze-outside-cloze-field = 克漏字空格只能用於使用了 'cloze:' 篩選器的欄位。通常為第一個欄位
