fields-add-field = 新增欄位
fields-delete-field-from = 刪除{ $val }的欄位？
fields-editing-font = 編輯時使用的字型
fields-field = 欄位：
fields-field-name = 欄位名稱：
fields-description = 描述
fields-description-placeholder = 欄位沒有內容時顯示的文字
fields-fields-for = { $val } 的欄位
fields-font = 字型：
fields-new-position-1 = 新位置 (1...{ $val })：
fields-notes-require-at-least-one-field = 筆記至少要有一個欄位。
fields-reverse-text-direction-rtl = 反轉書寫方向為由右至左 (RTL)
fields-collapse-by-default = 預設摺疊此欄位
fields-html-by-default = 預設使用 HTML 編輯器
fields-size = 大小：
fields-sort-by-this-field-in-the = 依此欄位在瀏覽器中排序
fields-that-field-name-is-already-used = 此欄位名稱已被使用。
fields-name-first-letter-not-valid = 欄位名稱不應始於「#」、「^」或「/」。
fields-name-invalid-letter = 欄位名稱不應包含「:」、「"」、{ "「{」" }或 { "「}」" }。
