statistics-cards-per-min = { $cards-per-minute } บัตรคำ/นาที
statistics-cards = { $cards } บัตรคำ
statistics-reviews = ทบทวน { $reviews } รายการ
statistics-counts-suspended-cards = ถูกแขวนแล้ว
statistics-future-due-title = ประมาณการ
statistics-reviews-title = ตรวจทาน
statistics-counts-learning-cards = การเรียนรู้
statistics-total = ทั้งหมด
statistics-average = ต้นทุนเฉลี่ย
