actions-add = Πρόσθηκη
actions-all-selected = Όλα επιλεγμένα
actions-any-selected = Οποιοδήποτε επιλεγμένο
actions-cancel = Άκυρο
actions-choose = Επιλογή
actions-close = Κλείσιμο
actions-copy = Αντιγραφή
actions-create-copy = Δημιουργία Αντιγράφου
actions-custom-study = Προσαρμοσμένη Μελέτη
actions-decks = Τράπουλες
actions-delete = Διαγραφή
actions-export = Εξαγωγή
actions-filter = Φιλτράρισμα
actions-help = Βοήθεια
actions-import = Εισαγωγή
actions-manage = Διαχείριση...
actions-name = Όνομα:
actions-new = Νέο
actions-new-name = Νέο όνομα:
actions-options = Επιλογές
actions-options-for = Επιλογές για { $val }
actions-preview = Προεπισκόπηση
actions-rebuild = Αναδόμηση
actions-rename = Μετονομασία
actions-rename-deck = Μετονομασία στοίβας
actions-rename-tag = Μετονομασία ετικέτας
actions-rename-with-parents = Μετονομασία μαζί με τα υπερκείμενα στοιχεία
actions-remove-tag = Αφαίρεση ετικέτας
actions-replay-audio = Επανέναρξη ακουστικού
actions-reposition = Αλλαγή θέσης
actions-save = Αποθήκευση
actions-search = Αναζήτηση
actions-select = Επιλογή
actions-shortcut-key = Σύμβολο συντόμευσης: { $val }
actions-suspend-card = Αναστολή κάρτας
actions-set-due-date = Ορισμός διορίας
actions-answer-card = Απάντηση κάρτας
actions-unbury-unsuspend = Άρση αναβολής/αναστολής
actions-add-deck = Προσθήκη στοίβας
actions-add-note = Προσθήκη καταχώρησης
actions-update-tag = Ενημέρωση ετικέτας
actions-update-note = Ενημέρωση καταχώρησης
actions-update-card = Ενημέρωση κάρτας
actions-update-deck = Ενημέρωση στοίβας
actions-forget-card = Επανεκκίνηση κάρτας
actions-build-filtered-deck = Χτίσιμο τράπουλας
actions-add-notetype = Προσθήκη Προτύπου Καταχώρησης
actions-remove-notetype = Διαγραφή Προτύπου Καταχώρησης
actions-update-notetype = Ενημέρωση Προτύπου Καταχώρησης
actions-update-config = Ενημέρωση Παραμέτρων
actions-card-info = Πληροφορίες κάρτας
actions-previous-card-info = Πληροφορίες προηγούμενης κάρτας
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = Αυτή η ενέργεια δεν υποστηρίζεται στο σύστημά σας μέχρι στιγμής.

## Flags

actions-flag-number = Σήμανση { $number }
actions-flag-red = Κόκκινο
actions-flag-orange = Πορτοκαλί
actions-flag-green = Πράσινο
actions-flag-blue = Μπλε
actions-flag-pink = Ροζ
actions-flag-turquoise = Τυρκουάζ
actions-flag-purple = Μωβ
actions-set-flag = Σήμανση
