editing-add-media = Προσθήκη πολυμέσων
editing-an-error-occurred-while-opening = Προέκυψε σφάλμα κατά το άνοιγμα του/της  { $val }
editing-cards = Κάρτες
editing-cut = Αποκοπή
editing-edit-current = Επεξεργασία τρέχοντος
editing-edit-html = Επεξεργασία HTML
editing-fields = Πεδία
editing-html-editor = Επεξεργαστής HTML
editing-latex = Latex
editing-latex-equation = Εξίσωση LaTeX
editing-paste = Επικόλληση
editing-show-duplicates = Προβολή διπλοεγγραφής
editing-tags = Ετικέτες
