notetypes-front-field = Μπροστά
notetypes-back-field = Πίσω
notetypes-add-reverse-field = Προσθήκη αναστροφής
notetypes-text-field = Κείμενο
notetypes-basic-name = Βασικό
notetypes-basic-reversed-name = Βασική (και αντεστραμμένη κάρτα)
notetypes-basic-optional-reversed-name = Βασική (κατ'επιλογή αντεστραμμένη κάρτα)
notetypes-cloze-name = Κλείσιμο
notetypes-card-2-name = Κάρτα 2
notetypes-card-1-name = Κάρτα 1
notetypes-add = Προσθέστε: { $val }
notetypes-add-note-type = Προσθήκη Τύπου Σημείωσης
notetypes-cards = Κάρτες...
notetypes-clone = Κλώνος: { $val }
notetypes-copy = { $val } αντίγραφο
notetypes-delete-this-note-type-and-all = Διαγραφή αυτού του τύπου σημείωσης και όλων των καρτών τους;
notetypes-delete-this-unused-note-type = Διαγραφή αυτού του μη χρησιμοποιημένου τύπου σημείωσης;
notetypes-fields = Πεδία...
notetypes-footer = Υποσέλιδο
notetypes-header = Επικεφαλίδα
notetypes-note-types = Τύποι Σημειώσεων
notetypes-options = Επιλογές...
