actions-add = Hozzáadás
actions-blue-flag = Megjelölés kékkel
actions-cancel = Mégsem
actions-choose = Kiválasztás
actions-close = Bezárás
actions-copy = Másolás
actions-custom-study = Egyéni tanulás
actions-decks = Paklik
actions-delete = Törlés
actions-export = Exportálás
actions-filter = Szűrő
actions-green-flag = Megjelölés zölddel
actions-help = Súgó
actions-import = Importálás
actions-manage = Műveletek...
actions-name = Név:
actions-new = Új
actions-new-name = Új név:
actions-options = Beállítások
actions-options-for = Beállítások ehhez: { $val }
actions-orange-flag = Megjelölés naranccsal
actions-preview = Előnézet
actions-rebuild = Újraépítés
actions-red-flag = Megjelölés pirossal
actions-rename = Átnevezés
actions-rename-deck = Pakli átnevezése
actions-replay-audio = Hang lejátszása újból
actions-reposition = Sorrendmódosítás
actions-save = Mentés
actions-search = Keresés
actions-shortcut-key = Gyorsbillentyű: { $val }
actions-suspend-card = Kártya felfüggesztése
