card-stats-added = Hozzáadva
card-stats-first-review = Első ismétlés
card-stats-latest-review = Legutóbbi ismétlés
card-stats-interval = Időköz
card-stats-ease = Könnyűség
card-stats-review-count = Ismétlések
card-stats-lapse-count = Elakadások
card-stats-average-time = Átlagos idő
card-stats-total-time = Időráfordítás összesen
card-stats-new-card-position = Sorrendi hely
card-stats-card-template = Kártyatípus
card-stats-note-type = Jegyzettípus
card-stats-deck-name = Csomag
card-stats-note-id = Jegyzetazonosító
card-stats-card-id = Kártyaazonosító
card-stats-review-log-rating = Értékelés
card-stats-review-log-type = Típus
card-stats-review-log-date = Dátum
card-stats-review-log-time-taken = Idő
card-stats-review-log-type-learn = Tanulás
card-stats-review-log-type-review = Ismétlés
card-stats-review-log-type-relearn = Újratanulás
card-stats-review-log-type-filtered = Szűrt
card-stats-review-log-type-rescheduled = Átütemezés
