custom-study-all-cards-in-random-order-dont = Az összes kártya véletlenszerű sorrendben (ne ütemezze újra)
custom-study-all-review-cards-in-random-order = Az összes ismétlőkártya véletlenszerű sorrendben
custom-study-cards = kártya
custom-study-cards-from-the-deck = kártyát a pakliból
custom-study-choose-tags = Címkék kiválasztása
custom-study-custom-study-session = Egyéni tanulásmenet
custom-study-due-cards-only = Csak az esedékes kártyák
custom-study-increase-todays-new-card-limit = Új kártyák mai limitjének növelése
custom-study-increase-todays-new-card-limit-by = Új kártyák mai limitjének növelése ennyivel:
custom-study-increase-todays-review-card-limit = Ismétlőkártyák mai limitjének növelése
custom-study-increase-todays-review-limit-by = Ismétlőkártyák mai limitjének növelése ennyivel:
custom-study-new-cards-in-deck-over-today = Mai új kártyák száma korlátozva: { $val }
custom-study-new-cards-only = Csak az új kártyák
custom-study-no-cards-matched-the-criteria-you = A megadott feltételeknek egyetlen kártya sem felelt meg.
custom-study-ok = OK
custom-study-preview-new-cards = Új kártyák előnézete
custom-study-preview-new-cards-added-in-the = Az elmúlt időszakban hozzáadott új kártyák előnézete:
custom-study-require-one-or-more-of-these = Az alábbi címkék közül legalább egy szerepeljen:
custom-study-review-ahead = Előzetes ismétlés
custom-study-review-ahead-by = Előzetes ismétlés erre az időszakra:
custom-study-review-cards-forgotten-in-last = Az elmúlt időszakban elfelejtett ismétlőkártyák:
custom-study-review-forgotten-cards = Elfelejtett kártyák ismétlése
custom-study-reviews-due-in-deck-over-today = Ma esedékes ismétlések száma korlátozva: { $val }
custom-study-select = Kijelölés
custom-study-select-tags-to-exclude = Kizárandó címkék:
custom-study-selective-study = Célzott tanulás
custom-study-study-by-card-state-or-tag = Tanulás a kártyák állapota vagy címkéje szerint
