notetypes-front-field = Előlap
notetypes-back-field = Hátlap
notetypes-add-reverse-field = Ellenkező irány hozzáadása
notetypes-text-field = Szöveg
notetypes-basic-name = Alap
notetypes-basic-reversed-name = Alap (mindkét irányban)
notetypes-basic-optional-reversed-name = Alap (egyik vagy mindkét irányban)
notetypes-cloze-name = Lyukas szöveg
notetypes-basic-type-answer-name = Alap (írja be a választ)
notetypes-card-2-name = 2. kártya
notetypes-card-1-name = 1. kártya
notetypes-add = Hozzáadás: { $val }
notetypes-add-note-type = Jegyzettípus hozzáadása
notetypes-cards = Kártyák...
notetypes-clone = Klónozás: { $val }
notetypes-copy = { $val } másolata
notetypes-create-scalable-images-with-dvisvgm = Méretezhető képek készítése a dvisvgm segítségével
notetypes-delete-this-note-type-and-all = Törlöd ezt a jegyzettípust és az összes hozzá tartozó kártyát?
notetypes-delete-this-unused-note-type = Törli ezt a nem használt jegyzettípust?
notetypes-fields = Mezők...
notetypes-footer = Lábléc
notetypes-header = Fejléc
notetypes-note-types = Jegyzettípusok
notetypes-options = Beállítások…
notetypes-please-add-another-note-type-first = Kérjük, adjon meg előbb egy új jegyzettípust.
notetypes-type = Típus
