preferences-anki-21-scheduler-beta = Anki 2.1 ütemező (béta)
preferences-automatically-sync-on-profile-openclose = Automatikus szinkronizálás a profil megnyitásakor és bezárásakor
preferences-backups = Biztonsági mentések
preferences-backups2 = megelőző változat másolata
preferences-backupsanki-will-create-a-backup-of = <b>Biztonsági másolat</b><br>Bezáráskor és szinkronizáláskor az Anki mindig készít egy biztonsági másolatot az Ön gyűjteményéről.
preferences-basic = Alap
preferences-change-deck-depending-on-note-type = Pakliváltás a jegyzettípus függvényében
preferences-changes-will-take-effect-when-you = A módosítások akkor lépnek érvénybe, amikor újraindítja az Ankit.
preferences-hardware-acceleration-faster-may-cause-display = Hardvergyorsítás (gyorsabb, de megjelenítési problémákat okozhat)
preferences-hours-past-midnight = órával éjfél után
preferences-interface-language = Felhasználói felület nyelve:
preferences-interrupt-current-audio-when-answering = Aktuális hanganyag megszakítása válaszadáskor
preferences-keep = Megőrzendő:
preferences-learn-ahead-limit = Előrehozott tanulás határa
preferences-mins = perc
preferences-network = Hálózat
preferences-next-day-starts-at = Új nap kezdete:
preferences-night-mode = Éjszakai mód
preferences-note-media-is-not-backed-up = Megjegyzés: a médiaállományról nem készül biztonsági mentés. Kérjük, készítsen mentést rendszeresen az Anki-mappájáról.
preferences-on-next-sync-force-changes-in = A legközelebbi szinkronizáláskor kényszerítsen módosítást az egyik irányban.
preferences-paste-clipboard-images-as-png = Vágólapon lévő képek beillesztése PNG-ként
preferences-paste-without-shift-key-strips-formatting = SHIFT nélküli beillesztéskor a formázás törlése
preferences-please-restart-anki-to-complete-language = A nyelv módosításának befejezéséhez, kérjük, indítsa újra az Ankit.
preferences-preferences = Testreszabás
preferences-scheduling = Átütemezés
preferences-show-learning-cards-with-larger-steps = Előbb a nagyobb lépésekkel ellátott tanulókártyákat mutassa, aztán az ismételendőket
preferences-show-next-review-time-above-answer = Következő ismétlés idejének kijelzése a válaszgombok fölött
preferences-show-play-buttons-on-cards-with = Lejátszás gomb megjelenítése a hanganyagot tartalmazó kártyákon
preferences-show-remaining-card-count-during-review = Hátralévő kártyák számának kijelzése ismétléskor
preferences-some-settings-will-take-effect-after = Egyes beállítások csak az Anki újraindítása után lépnek életbe.
preferences-synchronisation = <b>Szinkronizálás</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Szinkronizálás</b><br> Jelenleg nem üzemel; a főablak „sync” gombjával lehet bekapcsolni.
preferences-synchronize-audio-and-images-too = Hang- és képanyag szinkronizálása is
preferences-this-will-reset-any-cards-in = Ez alaphelyzetbe állítja a tanuláshoz szükséges összes kártyát, törli a szűrt paklikat, és visszaállítja az ütemezőt. Biztos benne?
preferences-timebox-time-limit = Időkeret
preferences-user-interface-size = A felhasználói felület mérete
preferences-when-adding-default-to-current-deck = Bővítéskor az aktuális pakli legyen az alapértelmezés
preferences-you-can-restore-backups-via-fileswitch = A biztonsági mentéseket visszaállíthatja a Fájl> Profilváltás menüponttal.
