profiles-anki-could-not-read-your-profile = Az Ankinak nem sikerült beolvasnia az Ön profiladatait. A beállított ablakméretek és a szinkronizálás bejelentkezési adatai törlődtek.
profiles-anki-could-not-rename-your-profile = Az Anki nem tudta átnevezni az Ön profilját, mert a profil mappája nem nevezhető át a merevlemezen. Kérjük, ellenőrizze, van-e Önnek írási jogosultsága a Documents/Anki mappához, és nem használja-e más program az Ön profilmappáit, majd próbálkozzon újra.
profiles-folder-already-exists = A mappa már létezik.
profiles-open = Megnyitás
profiles-open-backup = Biztonsági mentés megnyitása...
profiles-please-remove-the-folder-and = Kérjük, törölje a(z) { $val } mappát, és próbálkozzon újra.
profiles-profile-corrupt = Profil sérült
profiles-profiles = Profilok
profiles-quit = Kilépés
profiles-user-1 = 1. felhasználó
