decks-add-new-deck-ctrlandn = Neuen Stapel hinzufügen (Strg+N)
decks-build = Erstellen
decks-cards-selected-by = Karten, ausgewählt nach
decks-create-deck = Stapel erstellen
decks-custom-steps-in-minutes = Benutzerdefinierte Lernstufen (in Minuten)
decks-deck = Stapel
decks-decreasing-intervals = Intervall (absteigend)
decks-delete-deck = Stapel löschen
decks-enable-second-filter = Zweiten Filter aktivieren
decks-filter = Filter:
decks-filter-2 = Filter 2
decks-get-shared = Stapel herunterladen
decks-import-file = Datei importieren
decks-increasing-intervals = Intervall (ansteigend)
decks-latest-added-first = Erstelldatum (neuste zuerst)
decks-limit-to = Beschränken auf
decks-minutes = Minuten
decks-most-lapses = Fehlerzahl (häufigste zuerst)
decks-name-for-deck = Stapelname:
decks-new-deck-name = Neuer Stapelname:
decks-no-deck = [kein Stapel]
decks-oldest-seen-first = erstem Lerntag (älteste zuerst)
decks-order-added = Erstelldatum (älteste zuerst)
decks-order-due = Fälligkeit
decks-please-select-something = Bitte etwas auswählen.
decks-random = Zufall
decks-relative-overdueness = Überfällig relativ zum Intervall
decks-repeat-failed-cards-after = Erfolglos gelernte Karten wiederholen nach
decks-reschedule-cards-based-on-my-answers = Meine Antworten in diesem Auswahlstapel sollen die Zeitplanung von Karten beeinflussen
decks-study = Lernen
decks-study-deck = Stapel lernen
decks-filtered-deck-search-empty = Es wurden keine Karten mit dem angegebenen Suchbegriff gefunden. Bestimmte Karten könnten von der Suche ausgeschlossen gewesen sein, weil sie sich in einem anderen benutzerdefinierten Stapel befinden oder ausgesetzt sind.
decks-unmovable-cards = Alle ausgeschlossenen Karten anzeigen
