editing-actual-size = In tatsächlicher Größe anzeigen/nicht anzeigen
editing-add-media = Medien hinzufügen
editing-align-left = Links ausrichten
editing-align-right = Rechts ausrichten
editing-an-error-occurred-while-opening = Beim Öffnen von { $val } ist ein Fehler aufgetreten
editing-attach-picturesaudiovideo = Bilder/Audio/Video anfügen
editing-bold-text = Fett ausgezeichneter Text
editing-cards = Karten
editing-center = Zentrieren
editing-change-color = Farbe ändern
editing-cloze-deletion = Lücke (neue Karte)
editing-cloze-deletion-repeat = Lücke (selbe Karte)
editing-couldnt-record-audio-have-you-installed = Die Audioaufnahme konnte nicht durchgeführt werden. Haben Sie die Software 'lame' installiert?
editing-customize-card-templates = Kartenvorlagen anpassen
editing-customize-fields = Felder anpassen
editing-cut = Ausschneiden
editing-double-click-image = Bild doppelklicken
editing-double-click-to-expand = (zum Erweitern doppelklicken)
editing-double-click-to-collapse = Zum Einklappen doppelklicken
editing-edit-current = Angezeigte Karte bearbeiten
editing-edit-html = HTML eingeben
editing-fields = Felder
editing-float-left = Nach links gleiten
editing-float-right = Nach rechts gleiten
editing-float-none = Nicht gleiten
editing-indent = Einrückung vergrößern
editing-italic-text = Kursiver Text
editing-jump-to-tags-with-ctrlandshiftandt = Mit Strg+Umschalt+T zu den Schlagwörtern springen
editing-justify = Blocktext
editing-latex = LaTeX
editing-latex-equation = LaTeX-Formel
editing-latex-math-env = LaTeX-Mathematikumgebung
editing-mathjax-block = Abgesetzes MathJax-Element
editing-mathjax-chemistry = MathJax-Chemieformel
editing-mathjax-inline = Inzeiliges MathJax-Element
editing-mathjax-placeholder = Zum Akzeptieren { $accept } drücken, für eine neue Zeile { $newline } drücken
editing-media = Medien
editing-ordered-list = Geordnete Liste
editing-outdent = Einrückung verringern
editing-paste = Einfügen
editing-record-audio = Audio aufnehmen
editing-remove-formatting = Formatierung löschen
editing-restore-original-size = Originalgröße wiederherstellen
editing-select-remove-formatting = Zu löschende Formatierung auswählen
editing-show-duplicates = Duplikate anzeigen
editing-subscript = Tiefstellen
editing-superscript = Hochstellen
editing-tags = Schlagwörter
editing-tags-add = Schlagwort hinzufügen
editing-tags-copy = Schlagwörter kopieren
editing-tags-remove = Schlagwörter entfernen
editing-tags-select-all = Alle Schlagwörter auswählen
editing-text-color = Textfarbe
editing-text-highlight-color = Texthervorhebungsfarbe
editing-to-make-a-cloze-deletion-on = Um einen Lückentext zu einer bereits vorhandenen Notiz hinzuzufügen, muss dieser erst der Notiztyp Lückentext zugewiesen werden. Dazu wählen Sie oben links in diesem Menü: 'Bearbeiten > Notiztyp ändern'
editing-toggle-html-editor = Setze HTML Editor um
editing-toggle-visual-editor = Setze den Optischen Editor um
editing-toggle-sticky = Beibehalten ein-/ausschalten
editing-expand-field = Feld ausklappen
editing-collapse-field = Feld einklappen
editing-underline-text = Text unterstreichen
editing-unordered-list = Ungeordnete Liste
editing-warning-cloze-deletions-will-not-work = Achtung! Lückentext wird nur korrekt angezeigt, wenn oben als Notiztyp »Lückentext« gewählt wird.
editing-mathjax-preview = MathJax-Vorschau
editing-shrink-images = Bilder verkleinern
editing-close-html-tags = HTML-Tags automatisch schließen

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML-Editor
