fields-add-field = Feld hinzufügen
fields-delete-field-from = Feld aus { $val } entfernen?
fields-editing-font = Schriftart festlegen
fields-field = Feld:
fields-field-name = Feldname:
fields-description = Beschreibung
fields-description-placeholder = Tooltip, welches neben dem Feldnamen im Bearbeitungsfenster angezeigt werden soll
fields-fields-for = Felder für { $val }
fields-font = Schrift:
fields-new-position-1 = Neue Position (1 … { $val }):
fields-notes-require-at-least-one-field = Notizen benötigen mindestens ein Feld.
fields-reverse-text-direction-rtl = Textrichtung umkehren
fields-collapse-by-default = Standardmäßig einklappen
fields-html-by-default = HTML-Editor standardmäßig benutzen
fields-size = Größe:
fields-sort-by-this-field-in-the = In der Kartenverwaltung nach diesem Feld sortieren
fields-that-field-name-is-already-used = Dieser Feldname ist schon vergeben.
fields-name-first-letter-not-valid = Der Feldname sollte nicht mit #, ^ oder / beginnen.
fields-name-invalid-letter = Der Feldname sollte kein :, ", { "{" } oder { "}" } enthalten.
