preferences-automatically-sync-on-profile-openclose = Beim Öffnen/Schließen eines Profils automatisch synchronisieren
preferences-backups = Sicherungskopien
preferences-basic = Einfach
preferences-change-deck-depending-on-note-type = Stapel abhängig vom Notiztyp zuweisen
preferences-changes-will-take-effect-when-you = Die Änderungen werden nach einem Neustart von Anki wirksam.
preferences-hours-past-midnight = Stunden nach Mitternacht
preferences-language = Sprache
preferences-interrupt-current-audio-when-answering = Audiowiedergabe beim Antworten unterbrechen
preferences-learn-ahead-limit = Grenzwert für vorgezogenes Lernen
preferences-mins = Min.
preferences-network = Netzwerk
preferences-next-day-starts-at = Neuer Tag beginnt um
preferences-media-is-not-backed-up = Medien sind ungesichert. Bitte erstellen Sie zur Sicherheit regelmäßig Kopien Ihres Anki-Ordners.
preferences-on-next-sync-force-changes-in = Bei der nächsten Synchronisation Änderungen in eine Richtung erzwingen
preferences-paste-clipboard-images-as-png = Bilder aus der Zwischenablage im PNG-Bildformat einfügen
preferences-paste-without-shift-key-strips-formatting = Text aus der Zwischenablage ohne Formatierung einfügen
preferences-periodically-sync-media = Medien regelmäßig synchronisieren
preferences-please-restart-anki-to-complete-language = Bitte starten sie Anki neu um die Änderung der Sprache abzuschließen.
preferences-preferences = Einstellungen
preferences-scheduling = Zeitplanung
preferences-show-learning-cards-with-larger-steps = Lernkarten mit größeren Lernstufen vor Wiederholungskarten zeigen
preferences-show-next-review-time-above-answer = Zeit für nächste Wiederholung über Antworttaste anzeigen
preferences-show-play-buttons-on-cards-with = Wiedergabesteuerelemente auf Karten mit Audiodateien anzeigen
preferences-show-remaining-card-count = Anzahl restlicher Karten zeigen
preferences-some-settings-will-take-effect-after = Einige Einstellungen werden erst nach einem Neustart von Anki wirksam.
preferences-tab-synchronisation = Synchronisierung
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Synchronisierung</b><br> Im Moment nicht aktiviert; bitte im Hauptfenster den »Synchronisieren«-Knopf klicken, um sie zu aktivieren.
preferences-synchronize-audio-and-images-too = Tonaufnahmen und Bilder ebenfalls synchronisieren
preferences-timebox-time-limit = Zeitbegrenzung für Sitzungen
preferences-user-interface-size = Schriftgröße der Benutzeroberfläche
preferences-when-adding-default-to-current-deck = Beim Hinzufügen aktuellen Stapel als Standard festlegen
preferences-you-can-restore-backups-via-fileswitch = Sie können eine Sicherungskopie über den Menüpunkt Datei > "Profil wechseln" wiederherstellen.
preferences-legacy-timezone-handling = Veralteter Umgang mit Zeitzonen (fehleranfällig, aber für AnkiDroid <= 2.14 vorausgesetzt)
preferences-default-search-text = Standardmäßig eingestellter Suchtext
preferences-default-search-text-example = z.B. 'deck:current'
preferences-theme = Theme
preferences-theme-follow-system = System befolgen
preferences-theme-light = Hell
preferences-theme-dark = Dunkel
preferences-v3-scheduler = V3-Zeitplaner
preferences-ignore-accents-in-search = Akzente in der Suche ignorieren (langsamer)
preferences-backup-explanation = Anki erstellt regelmäßig Sicherungskopien Ihrer Sammlung, wenn es beendet wird. Sicherungskopien, die älter als 2 Tage sind, werden ggf. gelöscht, um nicht zu viel Speicherplatz zu belegen.
preferences-daily-backups = Beizubehaltende tägliche Sicherungskopien:
preferences-weekly-backups = Beizubehaltende wöchentliche Sicherungskopien:
preferences-monthly-backups = Beizubehaltende monatliche Sicherungskopien:
preferences-minutes-between-backups = Minuten zwischen automatisch erstellten Sicherungskopien:
preferences-reduce-motion = Animationen deaktivieren
preferences-reduce-motion-tooltip = Deaktiviert diverse Animationen und Übergangsanimationen auf der Benutzeroberfläche
preferences-custom-sync-url = Selbstgehosteter Synchronisierungsserver
preferences-custom-sync-url-disclaimer = Für fortgeschrittene Benutzer - bitte verwenden Sie die Bedinungsanleitung
preferences-hide-top-bar-during-review = Oberen Balken während Wiederholung ausblenden
preferences-hide-bottom-bar-during-review = Unteren Balken während Wiederholung ausblenden
preferences-always = Immer
preferences-full-screen-only = Nur Vollbildmodus
preferences-appearance = Erscheinungsbild
preferences-general = Allgemein
preferences-style = Stil
preferences-review = Revision
preferences-reviewer = Wiederholer
preferences-distractions = Ablenkungen
preferences-minimalist-mode = Minimalistischer Modus
preferences-editing = Bearbeiten
preferences-browsing = Durchsuchen
preferences-default-deck = Standardstapel
preferences-account = AnkiWeb-Account
preferences-media = Medien
preferences-note = Notiz
preferences-scheduler = Aufgabenplaner
preferences-user-interface = Nutzeroberfläche
preferences-import-export = Import/Export
