actions-add = Lisää
actions-all-selected = Kaikki valitut
actions-any-selected = Mikä tahansa valittu
actions-cancel = Peruuta
actions-choose = Valitse
actions-close = Sulje
actions-copy = Kopioi
actions-create-copy = Luo kopio
actions-custom-study = Mukautettu opiskelu
actions-decks = Pakat
actions-decrement-value = Pienennä arvoa
actions-delete = Poista
actions-export = Vie
actions-filter = Suodatin
actions-help = Ohje
actions-increment-value = Kasvata arvoa
actions-import = Tuo
actions-manage = Hallinnoi...
actions-name = Nimi:
actions-new = Uudet
actions-new-name = Uusi nimi:
actions-options = Valinnat
actions-options-for = Valinnat kohteessa { $val }
actions-preview = Esikatselu
actions-rebuild = Koosta uudelleen
actions-rename = Nimeä uudelleen
actions-rename-deck = Nimeä pakka uudelleen
actions-rename-tag = Nimeä tunniste uudelleen
actions-rename-with-parents = Nimeä uudelleen ml. vanhemmat
actions-remove-tag = Poista tunniste
actions-replay-audio = Toista äänitiedosto
actions-reposition = Uuden sijainnin määrittäminen
actions-save = Tallenna
actions-search = Etsi
actions-select = Valitse
actions-shortcut-key = Pikavalintanäppäin: { $val }
actions-suspend-card = Hyllytä kortti
actions-set-due-date = Aseta eräpäivä
actions-answer-card = Vastaa korttiin
actions-unbury-unsuspend = Poista piilotus/hyllytys
actions-add-deck = Lisää pakka
actions-add-note = Lisää muistiinpano
actions-update-tag = Päivitä tunniste
actions-update-note = Päivitä muistiinpano
actions-update-card = Päivitä kortti
actions-update-deck = Päivitä pakka
actions-forget-card = Unohda kortti
actions-build-filtered-deck = Rakenna pakka
actions-add-notetype = Lisää muistiinpanotyyppi
actions-remove-notetype = Poista muistiinpanotyyppi
actions-update-notetype = Päivitä muistiinpanotyyppi
actions-update-config = Päivitä asetukset
actions-card-info = Kortin tiedot
actions-previous-card-info = Edellisen kortin tiedot
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = Tätä toimintoa ei tällä hetkellä tueta järjestelmässäsi.

## Flags

actions-flag-number = Lippu { $number }
actions-flag-red = Punainen
actions-flag-orange = Oranssi
actions-flag-green = Vihreä
actions-flag-blue = Sininen
actions-flag-pink = Pinkki
actions-flag-turquoise = Turkoosi
actions-flag-purple = Violetti
actions-set-flag = Aseta lippu
