preferences-automatically-sync-on-profile-openclose = Synkronoi automaattisesti kun käyttäjätili avataan/suljetaan
preferences-backups = Varmuuskopiot
preferences-basic = Perusasetukset
preferences-change-deck-depending-on-note-type = Vaihda pakkaa muistiinpanotyypistä riippuen
preferences-changes-will-take-effect-when-you = Muutokset tulevat voimaan, kun käynnistät Ankin uudelleen.
preferences-hours-past-midnight = tuntia yli keskiyön
preferences-language = Kieli
preferences-interrupt-current-audio-when-answering = Keskeytä nykyinen ääni vastatessa
preferences-learn-ahead-limit = Ennalta opiskeltavien yläraja
preferences-mins = min
preferences-network = Verkko
preferences-next-day-starts-at = Uusi päivää alkaa
preferences-media-is-not-backed-up = Mediaa ei ole varmuuskopioitu. Luo säännöllisesti varmuuskopio Anki-kansiostasi kaiken varalta.
preferences-on-next-sync-force-changes-in = Seuraavassa synkronoinnissa pakota muutokset yhteen suuntaan
preferences-paste-clipboard-images-as-png = Liitä leikepöydän kuvat PNG-muodossa
preferences-paste-without-shift-key-strips-formatting = Liittäminen ilman vaihtonäppäintä poistaa muotoilut
preferences-periodically-sync-media = Synkronoi media ajoittain
preferences-please-restart-anki-to-complete-language = Käynnistä Anki uudelleen, niin että kielivalinnan muutos tulee voimaan.
preferences-preferences = Asetukset
preferences-scheduling = Ajastus
preferences-show-learning-cards-with-larger-steps = Näytä opittavat kortit joilla on suuremmat askeleet ennen kertausta
preferences-show-next-review-time-above-answer = Näytä seuraava kertausaika vastauspainikkeiden yläpuolella
preferences-show-play-buttons-on-cards-with = Näytä toistopainike korteissa, joissa on ääni
preferences-show-remaining-card-count = Näytä jäljellä olevien korttien määrä
preferences-some-settings-will-take-effect-after = Osa asetuksista tulee voimaan vasta Ankin uudelleenkäynnistyksen jälkeen.
preferences-tab-synchronisation = Synkronisaatio
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Synkronointi</b><br> Synkronointi ei ole päällä. Klikkaa Synkronoi-painiketta pääikkunassa laittaaksesi sen päälle.
preferences-synchronize-audio-and-images-too = Synkronoi myös äänitiedostot ja kuvat
preferences-timebox-time-limit = Määritetyn ajan yläraja
preferences-user-interface-size = Käyttöliittymän koko
preferences-when-adding-default-to-current-deck = Kun lisätään, on oletuksena nykyinen pakka
preferences-you-can-restore-backups-via-fileswitch = Voit palauttaa varmuuskopioita valitsemalla Tiedosto>Vaihda profiilia.
preferences-legacy-timezone-handling = Vanha aikavyöhykkeiden käsittely (sisältää virheitä, mutta vaaditaan AnkiDroidin versioissa <= 2.14)
preferences-default-search-text = Oletusarvoinen hakuteksti
preferences-default-search-text-example = esim. 'deck:current'
preferences-theme = Teema
preferences-theme-follow-system = Seuraa järjestelmän asetuksia
preferences-theme-light = Vaalea
preferences-theme-dark = Tumma
preferences-v3-scheduler = V3-aikataulutusohjelma
preferences-ignore-accents-in-search = Jätä aksentit huomiotta haun yhteydessä (hitaampi)
preferences-backup-explanation =
    Anki varmuuskopioi kokoelmasi säännöllisesti, kun se on suljettu. Kun varmuuskopiot ovat yli 2 päivää vanhoja,
    Anki alkaa poistaa niistä joitakin vapauttaakseen levytilaa.
preferences-daily-backups = Säilytettävien päivittäisten varmuuskopioiden määrä:
preferences-weekly-backups = Säilytettävien viikottaisten varmuuskopioiden määrä:
preferences-monthly-backups = Säilytettävien kuukausittaisten varmuuskopioiden määrä:
preferences-minutes-between-backups = Automaattisten varmuuskopioiden välinen aika minuuteissa:
preferences-reduce-motion = Vähennä liikettä
preferences-reduce-motion-tooltip = Poistaa käytöstä useita käyttöliittymän animaatioita ja siirtymiä.
preferences-custom-sync-url = Itsehallinnoitu synkronointipalvelin
preferences-custom-sync-url-disclaimer = Edistyneille käyttäjille - lue lisää käyttöoppaasta
preferences-hide-top-bar-during-review = Piilota yläpalkki kertauksen aikana
preferences-hide-bottom-bar-during-review = Piilota alapalkki kertauksen aikana
preferences-always = Aina
preferences-full-screen-only = Vain koko näytöllä
preferences-appearance = Ulkoasu
preferences-general = Yleiset
preferences-style = Tyyli
preferences-review = Kertaus
preferences-reviewer = Kertaaja
preferences-distractions = Häiriöt
preferences-minimalist-mode = Minimalistinen tila
preferences-editing = Muokkaus
preferences-browsing = Selaaminen
preferences-default-deck = Oletuspakka
preferences-account = AnkiWeb-tunnus
preferences-media = Media
preferences-note = Muistiinpano
preferences-scheduler = Ajastinohjelma
preferences-user-interface = Käyttöliittymä
preferences-import-export = Tuonti/Vienti
