qt-accel-about = &Тухай...
qt-accel-edit = &Засварла
qt-accel-exit = &Гарах
qt-accel-file = &Файл
qt-accel-find = &Хайлт
qt-accel-find-and-replace = Хайж &орлуулах...
qt-accel-go = &Оч
qt-accel-guide = &Гарын авлага...
qt-accel-help = &Тусламж
qt-accel-invert-selection = &Сонголтыг чанх эсрэг
qt-accel-next-card = &Дараагийн карт
qt-accel-previous-card = &Өмнөх карт
qt-accel-reschedule = &Дахин төлөвлөх...
qt-accel-select-all = &Бүгдийг сонго
qt-accel-tools = &Багаж
qt-accel-undo = &Буцаа
