adding-add-shortcut-ctrlandenter = បន្ថែម (ផ្លូវកាត់: ctrl+enter)
adding-added = បានបន្ថែម
adding-close-and-lose-current-input = បិទ និងបាត់បង់កាតកំពុងបញ្ចូល?
adding-edit = កែប្រែ "{ $val }"
adding-history = ប្រវត្តិ
adding-note-deleted = (កាតត្រូវបានលុបចោល)
adding-shortcut = ផ្លូវកាត់: { $val }
adding-the-first-field-is-empty = ប្រអប់ទី១មិនមានអក្សរ
adding-you-have-a-cloze-deletion-note = អ្នកមានប្រភេទកាតលុបចោលខ្លូស ប៉ុន្តែមិនបានបង្កើតការលុបចោលខ្លូសណាមួយ។ បន្តទៅមុខ?
