browsing-add-notes = បន្ថែមកាត
browsing-add-tags = បន្ថែមធែក
browsing-add-tags2 = បន្ថែមធែក
browsing-added-today = បានបន្ថែមថ្ងៃនេះ
browsing-addon = គ្រឿង​បន្ថែម
browsing-again-today = ម្តងទៀតនៅថ្ងៃនេះ
browsing-all-card-types = ប្រភេទកាតទាំងអស់
browsing-all-fields = ប្រអប់ទាំងអស់
browsing-answer = ចម្លើយ
browsing-any-cards-mapped-to-nothing-will = កាតណាមួយដែលបានបញ្ចូលទៅគ្មានអក្សរនឹងត្រូវលុបចោល។ ប្រសិនបើកំណត់ត្រាមិនមានកាតដែលនៅសល់ វានឹងត្រូវបាត់បង់។ តើអ្នកប្រាកដថាចង់បន្តឬ?
browsing-any-flag = ទង់ណាមួយ
browsing-browser-appearance = រូបរាងរបស់កម្មវិធី
browsing-browser-options = ជម្រើសរបស់កម្មវិធី
browsing-buried = ត្រូវបានកប់ចោល
browsing-card = កាត
browsing-card-list = បញ្ជីកាត
browsing-card-state = សភាពកាត
browsing-cards-cant-be-manually-moved-into = កាតមិនអាចត្រូវបានផ្លាស់ប្តូរទៅក្នុងហ៊ូដែលបានច្រោះនោះទេ។
browsing-change-deck = ប្តូរហ៊ូ
browsing-change-deck2 = ប្តូរហ៊ូ...
browsing-change-note-type = ប្តូរប្រភេទកំណត់ត្រា
browsing-change-note-type2 = ប្តូរប្រភេទកំណត់ត្រា...
browsing-change-to = ប្តូរ { $val } ទៅ:
browsing-clear-unused = លុបចោលរបស់មិនបានប្រើ
browsing-clear-unused-tags = លុបចោលធែកមិនបានប្រើ
browsing-created = បានបង្កើត
browsing-ctrlandshiftande = Ctrl+Shift+E
browsing-current-deck = ហ៊ូកំពុងរៀន
browsing-current-note-type = ប្រភេទកំណត់ត្រាកំពុងរៀន
browsing-delete-notes = លុបកំណត់ត្រា
browsing-delete-tags = លុបធែក
browsing-duplicate = ស្ទួន
browsing-ease = ភាពងាយស្រួល
browsing-end = បញ្ចប់
browsing-enter-tags-to-add = បញ្ចូលធែកដើម្បីបន្ថែមៈ
browsing-enter-tags-to-delete = បញ្ចូលធែកដើម្បីលុបៈ
browsing-filter = ច្រោះ...
browsing-filtered = (បានដកស្រង)
browsing-find = <b>ស្វែងរក</b>:
browsing-find-and-replace = ស្វែងរក ហើយជំនួស
browsing-find-duplicates = ស្វែងរកស្ទួន
browsing-first-card = កាតទី១
browsing-flag = ទង់
browsing-font = <b>ពុម្ភអក្សរ</b>:
browsing-font-size = <b>ទំហំអក្សរ</b>:
browsing-found-as-across-bs = បានរកឃើញ { $part } ពីក្នុង{ $whole }.
browsing-home = ទំព័រ​ដើម
browsing-ignore-case = មិនអើពើករណី
browsing-in = <b>ក្នុង</b>:
browsing-interval = ចន្លោះពេល
browsing-last-card = កាតចុងក្រោយ
browsing-learning = (កំពុងរៀន)
browsing-line-size = <b>ទំហំបន្ទាត់</b>:
browsing-manage-note-types = រៀបចំប្រភេទកំណត់ត្រា...
browsing-move-cards = ប្តូរទីតាំងកាត
browsing-move-cards-to-deck = ប្តូរទីតាំងកាតទៅហ៊ូៈ
browsing-nd-names = { $num }: { $name }
browsing-new = (ថ្មី)
browsing-new-note-type = ប្រែភេទកំណត់ត្រាថ្មី
browsing-no-flag = មិនមានទង់
browsing-note = កំណត់ត្រា
browsing-notes-tagged = កំណត់ត្រាត្រូវបានធែក។
browsing-nothing = គ្មានអ្វីទាំងអស់
browsing-only-new-cards-can-be-repositioned = មានតែកាតថ្មីប៉ុណ្ណោះដែលអាចប្តូរទីតាំងបាន។
browsing-optional-filter = ចម្រោះដែលអាចជ្រើសរើសបានៈ
browsing-override-back-template = កែប្រែទំរង់ផ្នែកខាងក្រោយៈ
browsing-override-font = កែប្រែពុម្ភអក្សរៈ
browsing-override-front-template = កែប្រែទំរង់ផ្នែកខាងមុខៈ
browsing-place-at-end-of-new-card = ដាក់នៅខាងចុងនៃជួររបស់កាតថ្មីៗ
browsing-place-in-review-queue-with-interval = ដាក់នៅក្នុងជួររៀនឡើងវិញក្នុងចន្លោះពេលៈ
browsing-please-give-your-filter-a-name = សុំដាក់ឈ្មោះចម្រោះរបស់អ្នកៈ
browsing-please-select-cards-from-only-one = សុំជ្រើសរើសកាតមកពីប្រភេទតែមួយ។
browsing-preview-selected-card = មើលទុកមុននូវកាតដែលបានជ្រើស ({ $val })
browsing-question = សំណួរ
browsing-queue-bottom = ខាងចុងនៃជួរ: { $val }
browsing-queue-top = ដំបូងនៃជួរ: { $val }
browsing-randomize-order = មិនតាមលំដាប់
browsing-remove-current-filter = ដកចេញនូវតម្រងកំពុងប្រើ...
browsing-remove-from-your-saved-searches = លុប { $val } ចេញពីការស្វែងរកដែលបានរក្សារទុក?
browsing-remove-tags = លុបធែក...
browsing-replace-with = <b>ប្តូរដោយ</b>:
browsing-reposition = ការប្តូរទីតាំង...
browsing-reposition-new-cards = ប្តូរទីតាំងកាតថ្មី
browsing-reschedule = កំណត់កាលវិភាគឡើងវិញ
browsing-save-current-filter = រក្សាទុកនូវតម្រងកំពុងប្រើ...
browsing-search-in = ស្វែងរកក្នុងៈ
browsing-search-within-formatting-slow = ស្វែងរកក្នុងទ្រង់ទ្រាយ (យឺត)
browsing-shift-position-of-existing-cards = ប្តូរទីតាំងកាតមានស្រាប់
browsing-sidebar = របារចំហៀង
browsing-sort-field = តម្រៀបប្រអប់
browsing-sorting-on-this-column-is-not = មិនអាចតម្រៀបលើជួរឈរនេះ។ សូមជ្រើសរើសជួរមួយផ្សេងទៀត។
browsing-start-position = ទីតាំងចាប់ផ្តើមៈ
browsing-step = ជំហានៈ
browsing-studied-today = បានរៀនថ្ងៃនេះ
browsing-suspended = បានផ្អាក
browsing-tag-duplicates = ធែកស្ទួន
browsing-tag-rename-warning-empty = អ្នកមិនអាចប្តូរឈ្មោះធែកដែលមិនមានកំណត់ត្រាបានទេ។
browsing-target-field = ប្រអប់គោលដៅៈ
browsing-today = ថ្ងៃនេះ
browsing-toggle-mark = សញ្ញាបិទបើក
browsing-toggle-suspend = សញ្ញាបិទបើកពន្យារ
browsing-treat-input-as-regular-expression = ចាត់ទុកការបញ្ចូលជាធម្មតា
browsing-type-here-to-search = <សរសេរទីនេះដើម្បីស្វែងរក; ចុចenter ដើម្បីបង្ហាញកាតកំពុងប្រើ>
browsing-whole-collection = បណ្តុំទាំងមូល
browsing-you-must-have-at-least-one = ត្រូវមានជួរយ៉ាងហោចមួយ។
browsing-group =
    { $count ->
       *[other] ផ្សេងទៀត (ឧទាហរណ៍ ០)
    }
browsing-note-count =
    { $count ->
       *[other] ផ្សេងទៀត (ឧទាហរណ៍ ០)
    }
