[package]
name = "tugger-snapcraft"
version = "0.15.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Snapcraft packaging primitives"
keywords = ["package", "snapcraft", "tugger"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[dependencies]
anyhow = "1.0"
duct = "0.13"
log = "0.4"
remove_dir_all = "0.7"
serde_yaml = "0.9"
serde = { version = "1.0", features = ["derive"] }
simple-file-manifest = "0.11"

[dependencies.tugger-common]
version = "0.10.0-pre"
path = "../tugger-common"
