actions-add = Thêm
actions-all-selected = Chọn tất cả
actions-any-selected = Chọn bất kì
actions-cancel = Hủy
actions-choose = Chọn
actions-close = Đóng
actions-copy = Chép
actions-custom-study = Học Tùy biến
actions-decks = Bộ thẻ
actions-delete = Xóa
actions-export = Xuất
actions-filter = Lọc
actions-help = Trợ giúp
actions-import = Nhập
actions-manage = Quản lý...
actions-name = Tên:
actions-new = Mới
actions-new-name = Tên mới:
actions-options = Tuỳ chọn
actions-options-for = Tùy chọn bộ thẻ { $val }
actions-preview = Xem trước
actions-rebuild = Tái tạo
actions-rename = Đổi tên
actions-rename-deck = Đổi tên Bộ thẻ
actions-rename-tag = Đổi tên Dấu
actions-rename-with-parents = Đổi tên Thẻ mẹ
actions-remove-tag = Xóa Dấu
actions-replay-audio = Phát lại Âm thanh
actions-reposition = Định vị lại
actions-save = Lưu
actions-search = Tìm
actions-select = Chọn
actions-shortcut-key = Phím tắt: { $val }
actions-suspend-card = Dừng Thẻ
actions-set-due-date = Đặt ngày đến hạn
actions-forget = Quên
actions-answer-card = Thẻ đáp án
actions-unbury-unsuspend = Bỏ hoãn/Bỏ ngừng
actions-add-deck = Thêm bộ thẻ
actions-add-note = Thêm Phiếu
actions-update-tag = Cập nhật Dấu
actions-update-note = Cập nhật Phiếu
actions-update-card = Cập nhật Thẻ
actions-update-deck = Cập nhật Bộ thẻ
actions-forget-card = Quên thẻ
actions-build-filtered-deck = Lập bộ thẻ
actions-expand-collapse = Mở rộng/Thu gọn
actions-add-notetype = Thêm Kiểu Phiếu
actions-remove-notetype = Xóa Kiểu Phiếu
actions-update-notetype = Cập nhật Kiểu phiếu
actions-update-config = Cập nhật cấu hình
actions-card-info = Thông tin thẻ
actions-previous-card-info = Thông tin thẻ trước

## Flags

actions-flag-number = Cờ
actions-flag-red = Đỏ
actions-flag-orange = Cam
actions-flag-green = Xanh lá
actions-flag-blue = Xanh da trời
actions-flag-pink = Hồng
actions-flag-turquoise = Ngọc lam
actions-flag-purple = Tím
actions-set-flag = Đặt cờ
