custom-study-must-rename-deck = Hãy đổi tên bộ thẻ Học tập tùy chỉnh hiện có trước.
custom-study-all-cards-in-random-order-dont = Tất cả các thẻ ôn tập theo thứ tự ngẫu nhiên (không đổi lịch)
custom-study-all-review-cards-in-random-order = Tất cả các thẻ ôn tập theo thứ tự ngẫu nhiên
custom-study-cards = thẻ
custom-study-cards-from-the-deck = thẻ từ bộ thẻ
custom-study-choose-tags = Chọn Nhãn
custom-study-custom-study-session = Phiên Học Tùy biến
custom-study-due-cards-only = Chỉ thẻ nợ
custom-study-increase-todays-new-card-limit = Tăng giới hạn thẻ mới cho hôm nay
custom-study-increase-todays-new-card-limit-by = Tăng giới hạn thẻ mới cho hôm nay với
custom-study-increase-todays-review-card-limit = Tăng giới hạn thẻ ôn tập cho hôm nay
custom-study-increase-todays-review-limit-by = Tăng giới hạn thẻ ôn tập cho hôm nay với
custom-study-new-cards-in-deck-over-today = Các thẻ mới trong bộ thẻ vượt quá giới hạn ngày hôm nay: { $val }
custom-study-new-cards-only = Chỉ thẻ mới
custom-study-no-cards-matched-the-criteria-you = Không có thẻ ứng với tiêu chí bạn đã đưa.
custom-study-ok = Đồng ý
custom-study-preview-new-cards = Xem trước thẻ mới
custom-study-preview-new-cards-added-in-the = Xem trước thẻ mới thêm vào sau cùng
custom-study-require-one-or-more-of-these = Yêu cầu một hoặc một số nhãn sau:
custom-study-review-ahead = Ôn trước
custom-study-review-ahead-by = Ôn trước
custom-study-review-cards-forgotten-in-last = Ôn thẻ quên sau cùng
custom-study-review-forgotten-cards = Ôn thẻ quên
custom-study-reviews-due-in-deck-over-today = Các thẻ ôn tập trong bộ thẻ vượt quá giới hạn ngày hôm nay: { $val }
custom-study-select = Chọn
custom-study-select-tags-to-exclude = Chọn nhãn để loại trừ:
custom-study-selective-study = Học tập Lựa chọn
custom-study-study-by-card-state-or-tag = Học theo trạng thái thẻ hay nhãn
