editing-actual-size = Bật/tắt hiển thị kích thước thực
editing-add-media = Thêm dữ liệu Phương tiện
editing-align-left = Căn lề trái
editing-align-right = Căn lề phải
editing-an-error-occurred-while-opening = Có lỗi xảy ra khi mở { $val }
editing-attach-picturesaudiovideo = Đính kèm hình ảnh/âm thanh/video
editing-bold-text = In đậm
editing-cards = Thẻ
editing-center = Căn giữa
editing-change-color = Đổi màu
editing-cloze-deletion = Xóa khoảng điền
editing-couldnt-record-audio-have-you-installed = Không thể ghi âm. Bạn đã cài đặt 'lame' chưa?
editing-customize-card-templates = Tùy chỉnh mẫu thẻ
editing-customize-fields = Tùy chỉnh Trường
editing-cut = Cắt
editing-edit-current = Sửa Ghi chú Hiện hành
editing-edit-html = Sửa HTML
editing-fields = Trường tin
editing-float-left = Nổi bên trái
editing-float-right = Nổi bên phải
editing-float-none = Không nổi lên
editing-html-editor = Trình soạn thảo HTML
editing-indent = Tăng thụt lề
editing-italic-text = In nghiêng
editing-jump-to-tags-with-ctrlandshiftandt = Nhảy đến nhãn với Ctrl+Shift+T
editing-justify = Căn đều
editing-latex = LaTeX
editing-latex-equation = Phương trình LaTeX
editing-latex-math-env = Môi trường toán LaTeX
editing-mathjax-block = MathJax ô trống
editing-mathjax-chemistry = MathJax hóa học
editing-mathjax-inline = MathJax nội tuyến
editing-media = Phương tiện
editing-ordered-list = Danh sách được yêu cầu
editing-outdent = Giảm thụt lề
editing-paste = Dán
editing-record-audio = Ghi âm
editing-remove-formatting = Xóa định dạng
editing-set-text-color = Đặt màu chữ
editing-set-text-highlight-color = Đặt màu nền chữ
editing-show-duplicates = Hiện Thẻ trùng
editing-subscript = Chỉ số dưới
editing-superscript = Chỉ số trên
editing-tags = Nhãn
editing-to-make-a-cloze-deletion-on = Để tạo chỗ điền trống trong phiếu hiện có, trước tiên cần chuyển nó sang kiểu phiếu điền chỗ trống, bằng cách chọn Chỉnh sửa>Đổi Kiểu Phiếu.
editing-toggle-sticky = Bật/tắt tính năng giữ lại những lần tìm kiếm
editing-underline-text = Gạch chân văn bản
editing-unordered-list = Danh sách không được yêu cầu
editing-warning-cloze-deletions-will-not-work = Cảnh báo, nút tạo chỗ trống sẽ không hoạt động được cho đến khi bạn chuyển kiểu phiếu ở trên cùng sang kiểu Điền chỗ trống.

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-bold-text-ctrlandb = In đậm (Ctrl+B)
editing-italic-text-ctrlandi = In nghiêng (Ctrl+I)
editing-underline-text-ctrlandu = Gạch chân (Ctrl+U)
editing-subscript-ctrland = Chỉ số dưới (Ctrl+=)
editing-superscript-ctrlandand = Chỉ số trên (Ctrl++)
editing-remove-formatting-ctrlandr = Xóa định dạng (Ctrl+R)
editing-record-audio-f5 = Tự ghi âm
editing-attach-picturesaudiovideo-f3 = Đính kèm hình ảnh/âm thanh/video (F3)
editing-cloze-deletion-ctrlandshiftandc = Xóa khoảng điền (Ctrl+Shift+C)
editing-change-colour-f8 = thay đổi màu sắc
editing-set-foreground-colour-f7 = Đặt màu cho nền trước (F7)
editing-customize-card-templates-ctrlandl = Tùy chỉnh mẫu thẻ (Ctrl+L)
editing-set-foreground-color = Đặt màu cho nền trước
