preferences-automatically-sync-on-profile-openclose = Tự động đồng bộ khi đóng/mở hồ sơ
preferences-backups = Sao lưu
preferences-backups2 = sao lưu
preferences-backupsanki-will-create-a-backup-of = <b>Sao lưu</b><br>Anki sẽ sao lưu bộ sưu tập của bạn mỗi khi thoát hoặc thực hiện đồng bộ.
preferences-basic = Cơ bản
preferences-change-deck-depending-on-note-type = Đổi bộ thẻ theo như kiểu phiếu
preferences-changes-will-take-effect-when-you = Các thay đổi sẽ có hiệu lực khi bạn khởi động lại Anki.
preferences-hours-past-midnight = giờ qua nửa đêm
preferences-interface-language = Ngôn ngữ Giao diện:
preferences-interrupt-current-audio-when-answering = Ngắt âm thanh hiện tại khi trả lời
preferences-keep = Giữ
preferences-learn-ahead-limit = Giới hạn học trước
preferences-mins = phút
preferences-network = Mạng
preferences-next-day-starts-at = Ngày kế tiếp bắt đầu lúc
preferences-night-mode = Chế độ ban đêm
preferences-note-media-is-not-backed-up = Lưu ý: Dữ liệu phương tiện sẽ không được sao lưu. Xin vui lòng sao lưu định kỳ thư mục Anki của bạn để phòng xa.
preferences-on-next-sync-force-changes-in = Ở lần đồng bộ kế tiếp, bắt buộc thay đổi trong một hướng
preferences-paste-clipboard-images-as-png = Dán hình ảnh clipboard với dạng PNG
preferences-paste-without-shift-key-strips-formatting = án mà không cần thay đổi định dạng dải phím
preferences-periodically-sync-media = Định kỳ đồng bộ hóa phương tiện
preferences-please-restart-anki-to-complete-language = Vui lòng khởi động lại Anki để hoàn tất việc thay đổi ngôn ngữ.
preferences-preferences = Tùy chỉnh
preferences-scheduling = Lập lịch lại
preferences-show-learning-cards-with-larger-steps = Hiển thị thẻ học tập với các bước lớn hơn trước khi ôn tập
preferences-show-next-review-time-above-answer = Hiện thời gian ôn tập kế tiếp trên các nút trả lời
preferences-show-play-buttons-on-cards-with = Hiển thị nút phát trên thẻ có âm thanh
preferences-show-remaining-card-count-during-review = Hiện số thẻ còn lại trong lúc ôn tập
preferences-some-settings-will-take-effect-after = Một số thiết lập chỉ có hiệu lực sau khi chạy lại Anki.
preferences-synchronisation = <b>Đồng bộ hóa</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Đồng bộ hóa</b><br> Hiện đang tắt; nhấp nút đồng bộ trong cửa sổ chính để bật đồng bộ.
preferences-synchronize-audio-and-images-too = Đồng bộ cả âm thanh và hình ảnh
preferences-this-will-reset-any-cards-in = Thao tác này sẽ đặt lại bất kỳ thẻ nào trong quá trình học, xóa các bộ bài được lọc và thay đổi phiên bản của bộ lập thời gian biểu. Tiếp tục?
preferences-timebox-time-limit = Giới hạn khung thời gian
preferences-user-interface-size = Kích thước giao diện người dùng
preferences-when-adding-default-to-current-deck = Khi thêm mới, mặc định thực hiện với bộ thẻ hiện hành
preferences-you-can-restore-backups-via-fileswitch = Bạn có thể khôi phục các bản sao lưu thông qua Tệp> Chuyển đổi Hồ sơ.
preferences-legacy-timezone-handling = Xử lý múi giờ cũ (lỗi, bắt buộc đối với AnkiDroid <= 2.14)
preferences-default-search-text = Mẫu tìm kiếm mặc định
preferences-default-search-text-example = vd. 'bộ thẻ:hiện tại '
preferences-theme = Giao diện
preferences-editing = Chỉnh sửa
